### ISSUE TITLE
Unresolved reference 'ImageDataGenerator'

### ISSUE THREAD

**Issue by yangqx** [WZMIAOMIAO/deep-learning-for-image-processing#10]
问题：在pycharm 工具打开的，下面的模块不能正常解析，但是代码能运行成功
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, Model, Sequential

环境：pycharm   TensorFlow 2.1  ，Python 3.6.10  测试如下
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow import keras

print(tf.__path__)
print(keras.__path__)
print(ImageDataGenerator)
输出：
['C:\\tools\\Anaconda3\\envs\\tf-gpu-pytorch\\lib\\site-packages\\tensorflow']
['C:\\tools\\Anaconda3\\envs\\tf-gpu-pytorch\\lib\\site-packages\\tensorflow_core\\python\\keras\\api\\_v2\\keras']
<class 'tensorflow.python.keras.preprocessing.image.ImageDataGenerator'>

**Comment by WZMIAOMIAO** [comment]
这个问题在我之前的视频中有说过，你更新下pycharm就行了。你更到2019.3之后的版本都可以查看源码。

**Comment by yangqx** [comment]
之前的是2019.1，重新安装了最新的社区版，2019.3.3，可以正常提示了 ！非常感谢！
