### ISSUE TITLE
求训练好的权重

### ISSUE THREAD

**Issue by mochaojie** [WZMIAOMIAO/deep-learning-for-image-processing#108]
本人没有GPU，想用下训练好的权重文件，求分享，谢谢

**Comment by mochaojie** [comment]
faster rcnn的

**Comment by WZMIAOMIAO** [comment]
链接：https://pan.baidu.com/s/16RdGlEc1NNGCzgA3BLXcuA 
提取码：05za 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by mochaojie** [comment]
> 链接：https://pan.baidu.com/s/16RdGlEc1NNGCzgA3BLXcuA
> 提取码：05za
> 复制这段内容后打开百度网盘手机App，操作更方便哦

谢谢
