### ISSUE TITLE
YOLOv3_spp的IOU计算问题

### ISSUE THREAD

**Issue by Rashfu** [WZMIAOMIAO/deep-learning-for-image-processing#109]
yolov3spp项目utils.py中的wh_iou是直接假设GT和anchor中心重合，然后取较短的w和h算IOU吗？

**Comment by WZMIAOMIAO** [comment]
我理解的是假设GT与所有anchors左上角重合，然后计算他们的IOU，选取IOU大于设定阈值的所有anchors。

**Comment by Rashfu** [comment]
这样计算方式是相同的，但是左上角重合是更容易接受和理解的

**Comment by WZMIAOMIAO** [comment]
计算方式不一样，计算结果是一样的
