### ISSUE TITLE
distributed

### ISSUE THREAD

**Issue by kszlk** [WZMIAOMIAO/deep-learning-for-image-processing#110]
您好，我跑您的代码当进行多GPU训练时，出现错误：not using distributed mode，请问这个错误应该怎么解决

**Comment by kszlk** [comment]
请问window下有nccl吗

**Comment by WZMIAOMIAO** [comment]
说明你的GPU环境配置有问题，检查下你的GPU驱动，CUDA等环境是否符合要求
