### ISSUE TITLE
关于proposal问题

### ISSUE THREAD

**Issue by mochaojie** [WZMIAOMIAO/deep-learning-for-image-processing#112]
您好，关于faster rcnn的proposal，我有些疑惑，用一张图片进行预测，预测结果没问题，但中间过程的proposal框与预想的差别很大，很奇怪，毕竟预测结果是没问题的。我有在b站上私信您，希望能具体谈到下

**Comment by mochaojie** [comment]
b站名称是莫莫705

**Comment by WZMIAOMIAO** [comment]
RPN的proposal就是粗选，Fast r-cnn部分是精选。如果第一步粗选就能达到很好的效果，那干嘛还要做第二部

**Comment by mochaojie** [comment]
不好意思哈，因为没有图，问题没有阐述清楚，具体问题已经在b站结合图重新私聊阐述了，感谢您的回复
