### ISSUE TITLE
我数据集是灰度图像，当我的输入in_channels改成1时为什么报错？

### ISSUE THREAD

**Issue by roseif** [WZMIAOMIAO/deep-learning-for-image-processing#12]
RuntimeError: Given groups=1, weight of size 64 1 3 3, expected input[32, 3, 224, 224] to have 1 channels, but got 3 channels instead

**Comment by roseif** [comment]
期待您的回答，谢谢

**Comment by WZMIAOMIAO** [comment]
你使用的是pytorch还是tensorflow

**Comment by WZMIAOMIAO** [comment]
因为在pytorch图像预处理部分将灰度图像转成三通道的图像了，所以图像预处理部分也需要修改一下。

**Comment by WZMIAOMIAO** [comment]
我刚调试了一下，发现问题出现在torch.utils.data.DataLoader这个函数，通过这个方法读入的图像无论是RGB图像（channel=3）还是灰度图像（channel=1）得到的tensor的channel都是等于3的。所以虽然你的数据集是灰度图像，但是通过torch.utils.data.DataLoader方法载入的数据都变成3通道的图像了，所以在卷积层1输入特征矩阵的channel（3）与卷积核的channel（1）不匹配就报错了。建议你自己写个dataloader别用官方提供的方法了。

**Comment by WZMIAOMIAO** [comment]
我看了下代码，发现问题在datasets.ImageFolder这个方法，它的默认default_loader官方是 这么实现的：
`
def pil_loader(path):
    # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
    with open(path, 'rb') as f:
        img = Image.open(f)
        return img.convert('RGB')
`
也就说无论你的图片是什么类型，它都会给你转成RGB图像，所以在卷积层一的输入特征矩阵channel=3并不是你以为的channel=1所以才会报错。你如果想入读gray类型的话，你需要在datasets.ImageFolder方法中传入自定的loader不让它转成RGB图像。
`
def my_loader(path):
    with open(path, 'rb') as f:
        img = Image.open(f)
        img = img.convert('L')
        return img
`
然后在datasets.ImageFolder中传入loader=my_loader就能够成功读取灰度图像了。再提醒你一点，如果你使用transforms.Normalize方法处理灰度图像时，应该通过如下方式使用：
`
transforms.Normalize(mean=(0.5,), std=(0.5,))
`

**Comment by WZMIAOMIAO** [comment]
我看了下代码，发现问题在datasets.ImageFolder这个方法，它的默认default_loader官方是 这么实现的：
def pil_loader(path):  
    with open(path, 'rb') as f: 
        img = Image.open(f) 
        return img.convert('RGB')
也就说无论你的图片是什么类型，它都会给你转成RGB图像，所以在卷积层一的输入特征矩阵channel=3并不是你以为的channel=1所以才会报错。你如果想入读gray类型的话，你需要在datasets.ImageFolder方法中传入自定的loader不让它转成RGB图像。
def my_loader(path): 
    with open(path, 'rb') as f: 
        img = Image.open(f) 
        img = img.convert('L') 
        return img
然后在datasets.ImageFolder中传入loader=my_loader就能够成功读取灰度图像了。再提醒你一点，如果你使用transforms.Normalize方法处理灰度图像时，应该通过如下方式使用：
transforms.Normalize(mean=(0.5,), std=(0.5,))

**Comment by roseif** [comment]
非常感谢。

> 我看了下代码，发现问题在datasets.ImageFolder这个方法，它的默认default_loader官方是 这么实现的：
> def pil_loader(path):
> with open(path, 'rb') as f:
> img = Image.open(f)
> return img.convert('RGB')
> 也就说无论你的图片是什么类型，它都会给你转成RGB图像，所以在卷积层一的输入特征矩阵channel=3并不是你以为的channel=1所以才会报错。你如果想入读gray类型的话，你需要在datasets.ImageFolder方法中传入自定的loader不让它转成RGB图像。
> def my_loader(path):
> with open(path, 'rb') as f:
> img = Image.open(f)
> img = img.convert('L')
> return img
> 然后在datasets.ImageFolder中传入loader=my_loader就能够成功读取灰度图像了。再提醒你一点，如果你使用transforms.Normalize方法处理灰度图像时，应该通过如下方式使用：
> transforms.Normalize(mean=(0.5,), std=(0.5,))

非常感谢

**Comment by linluying** [comment]
你好，我使用的是您的代码&nbsp;tensorflow_learning/Test3_vgg/


现在只能单张检测图片，并且输出图片中概率最大的一个目标，如果图中有多个目标需要检测，怎么才能输出多个目标的检测概率呢？另外，是否能够实现批量检测？
