### ISSUE TITLE
我直接运行的train_res50_fpn代码，数据用的VOC2012数据。分别用有/无预训练模型训练，效果差的非常远。

### ISSUE THREAD

**Issue by mjq93** [WZMIAOMIAO/deep-learning-for-image-processing#128]
我理解有无预训练模型效果会有一些差别，但是现在看上去没有预训练模型，网络完全无法收敛，可能的原因是什么呢？这样的话我修改模型用在自己的数据集上，没有预训练模型的话，又该怎么办呢？

首先没有用预训练模型，效果如下：
DONE (t=4.33s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.068
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.164
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.040
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.030
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.086
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.164
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.245
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.248
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.038
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.119
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.297

然后加载了COCO预训练模型，效果如下：
DONE (t=1.48s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.468
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.740
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.511
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.160
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.335
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.523
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.424
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.580
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.584
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.247
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.640

**Comment by WZMIAOMIAO** [comment]
- 如果没什么差别就不需要什么迁移学习了。
- 包括论文中训练模型都是先将backbone在imagenet上训练好后，再接着训练整个网络的，没有哪个目标检测网络什么预训练权重都不用直接训练的。
- 如果自己要改结构就要自己按照原论文去训练。

**Comment by HEFORSHEe** [comment]
**使用pascalvoc数据集运行train.py出现以下问题 请问是什么原因**

Epoch: [0] Total time: 0:10:35 (0.6667 s / it)
Traceback (most recent call last):
  File "train_mobilenetv2.py", line 197, in <module>
    main()
  File "train_mobilenetv2.py", line 118, in main
    coco_info = utils.evaluate(model, val_data_set_loader, device=device)
  File "/home/hyj/anaconda3/envs/torch/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/train_eval_utils.py", line 75, in evaluate
    coco = get_coco_api_from_dataset(data_loader.dataset)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/coco_utils.py", line 54, in get_coco_api_from_dataset
    return convert_to_coco_api(dataset)
  File "/home/hyj/pytorch_object_detection/faster_rcnn/train_utils/coco_utils.py", line 15, in convert_to_coco_api
    hw, targets = ds.coco_index(img_idx)
AttributeError: 'VOC2012DataSet' object has no attribute 'coco_index'
