### ISSUE TITLE
 Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by WkEEn** [WZMIAOMIAO/deep-learning-for-image-processing#13]
你好，在我使用GPU训练时会报上述错误，但注释掉loss.backward()就不会报错，但这样就灭有意义了，另外，使用CPU训练不会报错，但速度太慢。希望能帮忙解答！万分感谢

**Comment by WkEEn** [comment]
@WZMIAOMIAO

**Comment by WZMIAOMIAO** [comment]
你训练的是什么模型

**Comment by WkEEn** [comment]
vgg
环境：pytorch1.3.1+cu92+python3.7

**Comment by WkEEn** [comment]
@WZMIAOMIAO

**Comment by WZMIAOMIAO** [comment]
我初步怀疑是你的GPU内存不够，因为VGG 网络模型参数太大了，你可以尝试一下步骤来排除问题：
1）你使用alexnet的训练脚本调用GPU进行训练（如果没问题说明你的GPU环境是正常的）
2）如果第一步没问题再使用VGG的训练脚本，将batchsize设置成1进行训练（如果能够正常训练说明是内存不足的问题）

**Comment by WkEEn** [comment]
我尝试自己搭建的简单网络，还会报这样的错，请问是GPU的原因吗？
@WZMIAOMIAO

**Comment by WZMIAOMIAO** [comment]
你GPU的内存多大，也有可能是你GPU环境配置的问题。

**Comment by WkEEn** [comment]
![image](https://user-images.githubusercontent.com/39771251/77816732-1c7b4200-7100-11ea-90cd-c91a804e500e.png)

**Comment by WkEEn** [comment]
@WZMIAOMIAO

**Comment by WZMIAOMIAO** [comment]
你的GPU配置挺好的，应该是你GPU环境配置问题。
建议试下这个配置pytorch1.3 + CUDA10.1 + cuDNN7.6 
我的所有代码都是在这个环境下跑的。

**Comment by roseif** [comment]
安装多一个环境安装最新的Pytorch试下，我的没有问题

**Comment by WkEEn** [comment]
ok，确实是版本问题
@roseif
