### ISSUE TITLE
faster-rcnn输入大小疑惑

### ISSUE THREAD

**Issue by mjq93** [WZMIAOMIAO/deep-learning-for-image-processing#135]
![image](https://user-images.githubusercontent.com/11666931/105686128-da927680-5f31-11eb-87c2-342b52b8ce23.png)

博主：
我打了个断点调试faster-rcnn，发现网络输入image的shape是[3, H, W]，target内的boxes的顺序是[x1, y1, x2, y2]，为什么输入image和boxes的shape不对应呢？照我的理解image的shape得是[3, W, H]才能对应boxes坐标。
因为后期准备改成3d版的faster-rcnn，所以想深入弄清楚原因，期待博主回复，感谢！

**Comment by WZMIAOMIAO** [comment]
你问的这两者的shape本来就没什么关系，往后多读读代码吧。
