### ISSUE TITLE
怎么改写代码？

### ISSUE THREAD

**Issue by linluying** [WZMIAOMIAO/deep-learning-for-image-processing#14]
请问使用VGG检测的时候怎么实现批量检测，如果检测图中有多个目标，可以输出多个目标的概率吗？我现在用的是您的tensorflow-VGG 和PYTORCH-VGG

**Comment by WZMIAOMIAO** [comment]
批量检测时你把多张图片打成一个batch输入就行了，你想检测图片中是否存在多个目标的话，你可以了解下目标检测

**Comment by linluying** [comment]
你好,我刚接触不久，请问具体的过程您能详细说明下或者帮我写个批量检测的代码吧，万分感谢

**Comment by lilin198196** [comment]
@WZMIAOMIAO  你好，我在用mobilenet 替换resnet作为一个代码的主干网络，通过卷积把输出设置成跟残差一样的通道和大小，而且已经实现，但是再运算过程中还是有个地方报错，tensor的尺度不对，我不知道有没有说清楚，我的疑问是按理说主干网络的输出都处理成一样的了， 其他部分就直接调用就可以了，但是竟然有报错。我的邮箱是2510283860   qq的  请指教

**Comment by lixuxin3793** [comment]
抱歉，你好像发错邮箱了，我也刚刚开始学习深度学习，你确认一下邮箱，再发送正确的联系人吧



---原始邮件---
发件人: "LI LIN"<notifications@github.com&gt;
发送时间: 2020年4月20日(周一) 下午3:41
收件人: "WZMIAOMIAO/deep-learning-for-image-processing"<deep-learning-for-image-processing@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 怎么改写代码？ (#14)




 
@WZMIAOMIAO  你好，我在用mobilenet 替换resnet作为一个代码的主干网络，通过卷积把输出设置成跟残差一样的通道和大小，而且已经实现，但是再运算过程中还是有个地方报错，tensor的尺度不对，我不知道有没有说清楚，我的疑问是按理说主干网络的输出都处理成一样的了， 其他部分就直接调用就可以了，但是竟然有报错。我的邮箱是2510283860   qq的  请指教

**Comment by WZMIAOMIAO** [comment]
@linluying 你读入多张图片后分别进行预处理，然后放在一个list里面，通过torch.stack()函数将list中的所有图片tensor打包成一个batch就行了

**Comment by WZMIAOMIAO** [comment]
@lilin198196 你的问题我没听懂， 你直接在bilibili上私信我吧
