### ISSUE TITLE
想请教一句代码问题

### ISSUE THREAD

**Issue by THEBEST-cloud** [WZMIAOMIAO/deep-learning-for-image-processing#167]
width = int(out_channel * (width_per_group / 64.)) * groups
请问这句话的计算依据是什么啊，刚接触ResNet没看懂这个，视频中好像没有这句话，有点不一样

**Comment by WZMIAOMIAO** [comment]
这是为了兼容后面搭建resnext设置的。

**Comment by THEBEST-cloud** [comment]
请问为什么是这样计算的呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WuZhe"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 晚上8:31
收件人: "WZMIAOMIAO/deep-learning-for-image-processing"<deep-learning-for-image-processing@noreply.github.com&gt;; 
抄送: "李俊杰"<1543012632@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 想请教一句代码问题 (#167)





 
这是为了兼容后面搭建resnext设置的。

**Comment by WZMIAOMIAO** [comment]
我讲pytorch搭建resnext时有讲，有空自己去看下
