### ISSUE TITLE
 validation脚本报错

### ISSUE THREAD

**Issue by vintinshaw** [WZMIAOMIAO/deep-learning-for-image-processing#174]
line 172, in main
    stats, _ = summarize(coco_eval, catId=i)
line 72, in summarize
    stats[0], print_list[0] = _summarize(1)
line 47, in _summarize
    s = s[:, :, catId, aind, mind]
IndexError: index 9 is out of bounds for axis 2 with size 9
该修改的参数都改过了，这几行代码看不懂，不知道怎么改这个bug

**Comment by WZMIAOMIAO** [comment]
1.确保你的数据集格式和PASCAL VOC2012一致
2.确保--num-classes参数设置正确
3.确保--data-path参数设置正确
4.确保pascal_voc_classes.json文件与数据集中的标签一致

其他的都不需要你改动，如果有什么问题，请看下我之前写的博客：
https://blog.csdn.net/qq_37541097/article/details/112248194

**Comment by vintinshaw** [comment]
感谢回复，我明天再去研究一下。

WuZhe ***@***.***>于2021年3月10日 周三23:09写道：

**Comment by vintinshaw** [comment]
我仔细检查了一下数据集，找到了原因所在：
如果在选择的val中，某种类型的标注框正好一个也没有，就会出现这种问题。

for i in range(len(category_index)):

在这一行中，i不应该是range(len(category_index))，而应该是K。

但这样一来又回有新的问题，即最后的计算结果与laebl不对应，因为无法知道究竟是哪类label数量为0

你可以提供一个思路吗？

范天啸 ***@***.***> 于2021年3月10日周三 下午11:19写道：

**Comment by WZMIAOMIAO** [comment]
如果你要检测一类物体，验证时你又没这个类别的检测目标，那你检测它干嘛？
既然缺少目标导致的问题，你加上这个类别的数据不就行了。
