### ISSUE TITLE
使用自己的数据集    for obj in data["object"]: KeyError: 'object'

### ISSUE THREAD

**Issue by will-qzq** [WZMIAOMIAO/deep-learning-for-image-processing#175]
使用自己的数据集出现这个错误，请问该如何解决    
for obj in data["object"]:
KeyError: 'object'

**Comment by WZMIAOMIAO** [comment]
说明有的标注文件中没有目标，所以对应的xml文件中没有"object"属性

**Comment by will-qzq** [comment]
> 说明有的标注文件中没有目标，所以对应的xml文件中没有"object"属性
解决后报错
   iscrowd = [int(o['iscrowd']) for o in gt]
KeyError: 'iscrowd'

**Comment by WZMIAOMIAO** [comment]
应该是你自己改代码改出的问题，自己去检查吧

**Comment by will-qzq** [comment]
> 应该是你自己改代码改出的问题，自己去检查吧

好的谢谢
