### ISSUE TITLE
yolov3-spp的代码用自己的数据集训练时会偶尔出现RuntimeError: The size of tensor a (16) must match the size of tensor b (13) at non-singleton dimension 3

### ISSUE THREAD

**Issue by TTTTTTTXL** [WZMIAOMIAO/deep-learning-for-image-processing#176]
Epoch: [2] Total time: 0:00:03 (0.2055 s / it)
Traceback (most recent call last):
  File "train.py", line 288, in <module>
    train(hyp)
  File "train.py", line 208, in train
    coco=coco, device=device)
  File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/qin/TANGXL/yolo/train_utils/train_eval_utils.py", line 127, in evaluate
    pred = model(imgs)[0]  # only get inference result
  File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/qin/TANGXL/yolo/models.py", line 224, in forward
    return self.forward_once(x, verbose=verbose)
  File "/home/qin/TANGXL/yolo/models.py", line 243, in forward_once
    yolo_out.append(module(x))
  File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/qin/TANGXL/yolo/models.py", line 198, in forward
    io[..., :2] = torch.sigmoid(io[..., :2]) + self.grid  # xy 计算在feature map上的xy坐标
RuntimeError: The size of tensor a (16) must match the size of tensor b (13) at non-singleton dimension 3
出错比较随机，有时候训练几十次出错有时候几次就出错，请问大概会是什么原因

**Comment by WZMIAOMIAO** [comment]
用的是最新代码吗？

**Comment by TTTTTTTXL** [comment]
> 用的是最新代码吗？

是的

**Comment by WZMIAOMIAO** [comment]
如果你训练VOC数据集没问题训练自己的数据有问题，那就说明你的数据标注有问题

**Comment by WZMIAOMIAO** [comment]
或者你能提供给我一个可以复现bug的示例

**Comment by TTTTTTTXL** [comment]
> 如果你训练VOC数据集没问题训练自己的数据有问题，那就说明你的数据标注有问题

应该是我的数据集有问题，这里对数据集的图片尺寸有什么要求，或者会不会可能我的图片全都是黑白的所以会出问题。就是这个错误会导致训练中止而且出错比较随机所以我觉得很奇怪。但是训练出来的模型还是有效果的。很感谢你的教程，讲的超好。

**Comment by Kakaluoto** [comment]
> Epoch: [2] Total time: 0:00:03 (0.2055 s / it) Traceback (most recent call last): File "train.py", line 288, in train(hyp) File "train.py", line 208, in train coco=coco, device=device) File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context return func(*args, **kwargs) File "/home/qin/TANGXL/yolo/train_utils/train_eval_utils.py", line 127, in evaluate pred = model(imgs)[0] # only get inference result File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/qin/TANGXL/yolo/models.py", line 224, in forward return self.forward_once(x, verbose=verbose) File "/home/qin/TANGXL/yolo/models.py", line 243, in forward_once yolo_out.append(module(x)) File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/qin/TANGXL/yolo/models.py", line 198, in forward io[..., :2] = torch.sigmoid(io[..., :2]) + self.grid # xy 计算在feature map上的xy坐标 RuntimeError: The size of tensor a (16) must match the size of tensor b (13) at non-singleton dimension 3 出错比较随机，有时候训练几十次出错有时候几次就出错，请问大概会是什么原因

朋友，你最后是怎么解决的，我遇到了一摸一样的问题

**Comment by OKAIOK** [comment]
> > Epoch: [2] Total time: 0:00:03 (0.2055 s / it) Traceback (most recent call last): File "train.py", line 288, in train(hyp) File "train.py", line 208, in train coco=coco, device=device) File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context return func(*args, **kwargs) File "/home/qin/TANGXL/yolo/train_utils/train_eval_utils.py", line 127, in evaluate pred = model(imgs)[0] # only get inference result File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/qin/TANGXL/yolo/models.py", line 224, in forward return self.forward_once(x, verbose=verbose) File "/home/qin/TANGXL/yolo/models.py", line 243, in forward_once yolo_out.append(module(x)) File "/home/qin/.conda/envs/pytorch1.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl result = self.forward(*input, **kwargs) File "/home/qin/TANGXL/yolo/models.py", line 198, in forward io[..., :2] = torch.sigmoid(io[..., :2]) + self.grid # xy 计算在feature map上的xy坐标 RuntimeError: The size of tensor a (16) must match the size of tensor b (13) at non-singleton dimension 3 出错比较随机，有时候训练几十次出错有时候几次就出错，请问大概会是什么原因
> 
> 朋友，你最后是怎么解决的，我遇到了一摸一样的问题

哥们，你解决这个问题了吗，同样遇到了这个问题
