### ISSUE TITLE
faster_rcnn_res50_fpn.pth 模型转换为pt文件的时候出错

### ISSUE THREAD

**Issue by ihg1992** [WZMIAOMIAO/deep-learning-for-image-processing#178]
**System information**
* Have I written custom code:
* OS Platform(Linux Ubuntu 16.04):
* Python version:anaconda3  python3.7.6 
* Deep learning framework and version(e.g., Pytorch1.6):
* Use GPU or not:GPU
* CUDA/cuDNN version(if you use GPU):CUDA10.1 Cudnn7.5
* The network you trained(e.g., Resnet34 network):fater_rcnn_resnet50_fpn

**Describe the current behavior**
when I write a script trace test.pth to test.pt ,It occurred this errors

模型转换代码如下: 代码在另外一台电脑上跑,用sunlogin remote control的,没法复制就先截图了,后面补上代码(苦笑)
![image](https://user-images.githubusercontent.com/21332665/111074618-c83ebd00-851e-11eb-9c67-3bc986a99497.png)

**Error info / logs**
![image](https://user-images.githubusercontent.com/21332665/111074573-7d24aa00-851e-11eb-8b75-61b5c27a8ac1.png)

**Comment by WZMIAOMIAO** [comment]
暂不支持tracing，你可以使用官方faster rcnn源码试下

**Comment by ihg1992** [comment]
好的好的,感谢感谢,哈哈
