### ISSUE TITLE
大佬，有/save_weights/model.pth方便提供一下吗

### ISSUE THREAD

**Issue by ctlddey** [WZMIAOMIAO/deep-learning-for-image-processing#179]
报错
AssertionError: ./save_weights/model.pth file dose not exist.

**Comment by WZMIAOMIAO** [comment]
这是你自己训练得到的

**Comment by WZMIAOMIAO** [comment]
我的是　->　链接:https://pan.baidu.com/s/1ifilndFRtAV5RDZINSHj5w 提取码:dsz8

**Comment by ctlddey** [comment]
非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月15日(星期一) 中午12:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 大佬，有/save_weights/model.pth方便提供一下吗 (#179)





 
我的是　-&gt;　链接:https://pan.baidu.com/s/1ifilndFRtAV5RDZINSHj5w 提取码:dsz8
 
&mdash;
