### ISSUE TITLE
运行train_res50_fpn.py，报如下错误。windows10环境，python3.7，pytorch1.5，谢谢！

### ISSUE THREAD

**Issue by brucezheng2020** [WZMIAOMIAO/deep-learning-for-image-processing#18]
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::cat(Tensor[] tensors, int dim=0) -> (Tensor):
  Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'Tensor'.
  
  aten::cat.out(Tensor[] tensors, int dim=0, *, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'List[Tensor]' for argument 'tensors' but instead found type 'Tensor'.

The original call is:
  File "C:\faster_rcnn\network_files\det_utils.py", line 216
        assert isinstance(rel_codes, torch.Tensor)
        boxes_per_image = [b.size(0) for b in boxes]
        concat_boxes = torch.cat(boxes, dim=0)
                                  ~~~~~~~~~ <--- HERE

        box_sum = 0

第一次在github上提问题，谢谢

**Comment by WZMIAOMIAO** [comment]
我这边pytorch1.5GPU（linux环境）1.5CPU（windows环境）都没有任何问题。你是编译器没设置好还是自己改了代码。

**Comment by brucezheng2020** [comment]
找到原因了，我看到 # type: (float, float, bool)，编辑器报错，就将类似这样的行注释了，导致了错误，改回来就ok了。谢谢。还有就是你的readme中说的windows环境安装那个pycocotools-win报错的问题，我发现用pip install pycocotools-windows就可以了。

**Comment by WZMIAOMIAO** [comment]
好的，我一会把readme修改下
