### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by coderhukai** [WZMIAOMIAO/deep-learning-for-image-processing#185]
![image](https://user-images.githubusercontent.com/68494594/111596558-41346200-8808-11eb-94bd-a74bd86555e1.png)
![image](https://user-images.githubusercontent.com/68494594/111596608-4db8ba80-8808-11eb-932c-f3540ba75772.png)

**Comment by WZMIAOMIAO** [comment]
你是不是自己改了网络结构，如果改了就不能使用预训练权重了

**Comment by coderhukai** [comment]
嗯嗯，找到原因了，谢谢
