### ISSUE TITLE
这没错吧，是我编译的问题吗？

### ISSUE THREAD

**Issue by coderhukai** [WZMIAOMIAO/deep-learning-for-image-processing#193]
![image](https://user-images.githubusercontent.com/68494594/111964062-2ecf6680-8b2f-11eb-9526-a5e687f2b554.png)

**Comment by Rashfu** [comment]
直接把network_files删了就行。

**Comment by WZMIAOMIAO** [comment]
看下我《使用代码注意事项》视频。

**Comment by coderhukai** [comment]
好的，谢谢谢谢，问题解决了
