### ISSUE TITLE
关于dataloader的num_workers

### ISSUE THREAD

**Issue by robbiewongBD** [WZMIAOMIAO/deep-learning-for-image-processing#198]
你好，最近在用pytorch调其他项目，不过是在win下，在win下dataloader的num_worker如果不为0会报错，在linux下面就没问题；然而我看你的pytorch_object_detection里的datapoader在win下，num_worker不设为0也没问题，想知道是如何避免的？看源码没看出所以然。

**Comment by WZMIAOMIAO** [comment]
你用的哪个脚本不能设置num_worker，是最新代码嘛？

**Comment by robbiewongBD** [comment]
> 你用的哪个脚本不能设置num_worker，是最新代码嘛？
是最新的，deep-learning-for-image-processing/pytorch_object_detection/faster_rcnn/train_res50_fpn.py 
不是不能设置，在windows下，是我设置为8跟设置为0，发现并没有提速；
我查过pytorch dataloader 的num_worker，发现在Windows下如果不设为0会报错，而你的代码没有，但是并不能提速。

**Comment by WZMIAOMIAO** [comment]
你是使用CPU训练还是GPU训练的，如果使用CPU肯定是没变化的。还有建议使用linux系统去跑深度学习，不建议使用windows

**Comment by robbiewongBD** [comment]
用的GPU，Linux下的确正常
