### ISSUE TITLE
faster-rcnn-pytorch-master的训练 数据（图片，XML文件等）--可以提供？？

### ISSUE THREAD

**Issue by lys0796** [WZMIAOMIAO/deep-learning-for-image-processing#199]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
请仔细看下我的代码讲解视频，以及readme文件，说的写的都很清楚，链接都在readme里。
