### ISSUE TITLE
大神 这边的tensorflow2内容有木有tensorflow1的对应的 ？比如rest 迁移 在tensorflow1的版本？ 这差异太大啦

### ISSUE THREAD

**Issue by nanfangyuan** [WZMIAOMIAO/deep-learning-for-image-processing#226]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
没有哦
