### ISSUE TITLE
pytorch GPU显存利用率不高问题

### ISSUE THREAD

**Issue by coderhukai** [WZMIAOMIAO/deep-learning-for-image-processing#236]
你好，我训练batch_size=64，cpu利用率40%多，gpu利用率20%，batch_size=128又显存不足，这该怎么解决呢？怎么提高我的GPU利用率加快训练呢？

**Comment by Rashfu** [comment]
https://www.zhihu.com/question/265963699
你没有理解GPU利用率和显存的关系，一般任务管理器要看CUDA的窗口

**Comment by WZMIAOMIAO** [comment]
> 你好，我训练batch_size=64，cpu利用率40%多，gpu利用率20%，batch_size=128又显存不足，这该怎么解决呢？怎么提高我的GPU利用率加快训练呢？

在确定你看的信息都是准确的前提下，可以尝试以下方法提升训练速度：
1. 在dataloder中设置合适的num_workers，一般设置到8就行了（windows系统好像有问题，linux是正常的）
2. 在dataloder中将pin_memory设置为True
3. 有条件使用固态硬盘可以提升数据读取速度。
