### ISSUE TITLE
多GPU训练报错：subprocess.CalledProcessError: Command '['/opt/anaconda3/envs/py37/bin/python', '-u', 'train_multi_GPU.py']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Taylor-X76** [WZMIAOMIAO/deep-learning-for-image-processing#241]
(py37) xiamingyang@AI-02:~/PyTorch/PyTorch_Object_detection/faster_rcnn$ CUDA_VISIBLE_DEVICES=4,6 python -m torch.distributed.launch --nproc_per_node=2 --use_env train_multi_GPU.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 1): env://
| distributed init (rank 0): env://
Traceback (most recent call last):
  File "train_multi_GPU.py", line 249, in <module>
    main(args)
  File "train_multi_GPU.py", line 40, in main
    init_distributed_mode(args)
  File "/Ai-Data/home/users/xiamingyang/PyTorch/PyTorch_Object_detection/faster_rcnn/train_utils/distributed_utils.py", line 320, in init_distributed_mode
    world_size=args.world_size, rank=args.rank)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 397, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 168, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/anaconda3/envs/py37/bin/python', '-u', 'train_multi_GPU.py']' returned non-zero exit status 1.

**Comment by WZMIAOMIAO** [comment]
```RuntimeError: Address already in use```
你使用的GPU被别的程序在占用。使用```nvidia smi```查看GPU的占用详情，看看哪些程序正在使用。

**Comment by kekexixili** [comment]
你好，请问你这个问题解决了么，我使用多卡训练也出现了这个问题

**Comment by zzzhhh1031** [comment]
Hello, please ask you to solve it, I also encountered this problem

**Comment by zzzhhh1031** [comment]
> （py37） xiamingyang@AI-02：~/PyTorch/PyTorch_Object_detection/faster_rcnn$ CUDA_VISIBLE_DEVICES=4，6 python -m torch.distributed.launch --nproc_per_node=2 --use_env train_multi_GPU.py
> 
> 默认情况下，将每个进程OMP_NUM_THREADS环境变量设置为 1，以避免系统过载，请根据需要进一步调整该变量以在应用程序中获得最佳性能。
> 
> |分布 init （排名 1）： env:// |分布式初始化（排名 0）：env:// 跟踪（最近一次调用最后一次）：文件“train_multi_GPU.py”，第 249 行，在 main（args） 文件“train_multi_GPU.py”中，第 40 行，在主init_distributed_mode（args） 文件中“/Ai-Data/home/user/xiamingyang/PyTorch/PyTorch_Object_detection/faster_rcnn/train_utils/distributed_utils.py”，第 320 行，init_distributed_mode world_size=args.world_size， rank=args.rank） 文件 “/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py”， 第 397 行， 在 init_process_group 存储中， rank， world_size = next（rendezvous_iterator） 文件 “/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/rendezvous.py”， 第 168 行， 在 _env_rendezvous_handler 存储 = TCPStore（master_addr， master_port， world_size， start_daemon） RuntimeError：已在使用的地址 Traceback（最近一次调用）：文件“/opt/anaconda3/envs/py37/lib/python3.7/runpy.py”，第 193 行，_run_module_as_main “**main**”，mod_spec） 文件 “/opt/anaconda3/envs/py37/lib/python3.7/runpy.py”，第 85 行，_run_code exec（code， run_globals） 文件 “/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py”，第 263 行， 在 main（） file “/opt/anaconda3/envs/py37/lib/python3.7/site-packages/torch/distributed/launch.py”中，第 259 行，在主 cmd=cmd） 子进程中。CalledProcessError：命令'['/opt/anaconda3/envs/py37/bin/python'， '-u'， 'train_multi_GPU.py']'返回非零退出状态1。

Hello, please ask you to solve it, I also encountered this problem

**Comment by Sofina0528** [comment]
> 你好，请问你这个问题解决了么，我使用多卡训练也出现了这个问题

您好，我也遇到了同样的问题，请问您解决了吗？

**Comment by Sofina0528** [comment]
> 你好，请问你这个问题解决了么，我使用多卡训练也出现了这个问题

您好，我也遇到了同样的问题，请问您解决了吗？

> 你好，请问你这个问题解决了么，我使用多卡训练也出现了这个问题
