### ISSUE TITLE
Loss is nan, stopping training . I use your faster-rcnn code to train my own dateset that I have transfered it into VOC2012 mode ,then I run 'train_mobilenetv2' in my pc, it got the result 'loss is nan'.

### ISSUE THREAD

**Issue by 618-ssdu** [WZMIAOMIAO/deep-learning-for-image-processing#244]
platform：win10 and Linux（I try both）
Using cuda device training.
Using 4 dataloader workers
Epoch: [0]  [   0/1985]  eta: 1:08:57.381961  lr: 0.000500  loss: 2.7721 (2.7721)  loss_classifier: 1.9666 (1.9666)  loss_box_reg: 0.0388 (0.0388)  loss_objectness: 0.6976 (0.6976)  loss_rpn_box_reg: 0.0691 (0.0691)  time: 2.0843  data: 0.1230  max mem: 1212
Epoch: [0]  [  50/1985]  eta: 0:09:10.796689  lr: 0.000500  loss: 0.6686 (1.0468)  loss_classifier: 0.2676 (0.4887)  loss_box_reg: 0.0100 (0.0280)  loss_objectness: 0.3348 (0.4657)  loss_rpn_box_reg: 0.0498 (0.0644)  time: 0.2467  data: 0.1051  max mem: 1792
Epoch: [0]  [ 100/1985]  eta: 0:08:22.285547  lr: 0.000500  loss: 0.5700 (0.8217)  loss_classifier: 0.2172 (0.3628)  loss_box_reg: 0.0152 (0.0238)  loss_objectness: 0.2737 (0.3753)  loss_rpn_box_reg: 0.0571 (0.0597)  time: 0.2487  data: 0.1067  max mem: 1792
Epoch: [0]  [ 150/1985]  eta: 0:07:57.971424  lr: 0.000500  loss: 0.5219 (0.7306)  loss_classifier: 0.1708 (0.3102)  loss_box_reg: 0.0147 (0.0212)  loss_objectness: 0.2607 (0.3394)  loss_rpn_box_reg: 0.0590 (0.0599)  time: 0.2477  data: 0.1055  max mem: 1792
Loss is nan, stopping training

**Comment by WZMIAOMIAO** [comment]
应该是数据集的问题，你可以尝试克隆最新代码，能够检测你的数据集中是否有错误的GTBOX
