### ISSUE TITLE
数据分布及更换数据集的问题

### ISSUE THREAD

**Issue by zmz125** [WZMIAOMIAO/deep-learning-for-image-processing#248]
感谢大佬的耐心解答，Faster R-CNN终于跑起来了😁
现有一个新的问题，在原来VOC数据集时，为什么Epoch只训练了5823个数据？
如今我更换了一个新的数据集，有5000张图片及其对应的5000个xml文件，
通过使用split_data.py划分了2500条train.txt和2500条val.txt，
为什么跑起来Epoch只用313条数据？
![image](https://user-images.githubusercontent.com/64347292/117539379-eddad500-b03c-11eb-8c3e-4ca251ca96b8.png)

**Comment by WZMIAOMIAO** [comment]
你先搞清楚什么是epoch再问吧
