### ISSUE TITLE
多GPU并行训练问题

### ISSUE THREAD

**Issue by coderhukai** [WZMIAOMIAO/deep-learning-for-image-processing#249]
AttributeError: module 'torch.distributed' has no attribute 'init_process_group'
你好，我在用多GPU训练的时候报这个错，是什么原因呢？

**Comment by WZMIAOMIAO** [comment]
请仔细阅读项目中的readme，把环境配置正确，还有多GPU暂只支持linux环境

**Comment by coderhukai** [comment]
torch.nn.DataParallel 这个包可以在window上进行多GPU吗？

**Comment by WZMIAOMIAO** [comment]
没用过DP，只用过DDP，官方也推荐使用DDP。所有关于GPU的测试都是在linux环境下进行的，windows没测过。但根据以往的反馈，window一堆问题。
