### ISSUE TITLE
YOLOV3_spp运行问题

### ISSUE THREAD

**Issue by dudiaoxifenglie** [WZMIAOMIAO/deep-learning-for-image-processing#251]
**System information**:
处理器	Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz   2.30 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
系统类型: 64 位操作系统, 基于 x64 的处理器
DirectX 版本：	12.0 
GPU 处理器：		NVIDIA GeForce GTX 960M
驱动程序版本：			466.27
驱动器类型：			DCH
Direct3D 功能级别：		11_0
CUDA 核心：		640 
核心时钟：			1097 MHz 
内存数据速率：			5.01 Gbps
内存接口：			128-位 
内存带宽：			80.16 GB/秒
全部可用的图形内存：		10184MB
* Have I written custom code: No
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):  Win10
* Python version: 3.6.13
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): torch1.6.0
* Use GPU or not: Single GPU
* CUDA/cuDNN version(if you use GPU):  CUDA Version 10.2.89 / cuDNN version 8.0.4
* The network you trained(e.g., Resnet34 network):  YOLOV3_spp
**Describe the current behavior**
按照哔哩哔哩视频上的教程，做好了准备工作，然后开始进行训练
**Error info / logs**
D:\Anaconda\envs\py36\python.exe C:/Users/FuGuodong/Desktop/pytorch_Study/Study_Video/yolov3_spp/train.py
Namespace(batch_size=4, cache_images=False, cfg='cfg/yolov3-spp.cfg', data='data/my_data.data', device='cuda:0', epochs=30, freeze_layers=False, hyp='cfg/hyp.yaml', img_size=512, multi_scale=True, name='', notest=False, rect=False, savebest=False, single_cls=False, weights='weights/yolov3spp-voc-512.pt')
Start Tensorboard with "tensorboard --logdir=runs", view at http://localhost:6006/
Using cuda device training.
Using multi_scale training, image range[320, 736]
Model Summary: 225 layers, 6.29987e+07 parameters, 6.29987e+07 gradients
Caching labels (5717 found, 0 missing, 0 empty, 0 duplicate, for 5717 images): 100%|██████████| 5717/5717 [00:00<00:00, 9569.73it/s]
Caching labels (5823 found, 0 missing, 0 empty, 0 duplicate, for 5823 images): 100%|██████████| 5823/5823 [00:00<00:00, 10243.12it/s]
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\build_utils\layers.py:66: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nx == na:  # same shape 如果channel相同，直接相加
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\models.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (self.nx, self.ny) != (nx, ny) or self.grid is None:  # fix no grid bug
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\models.py:148: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  self.ng = torch.tensor(ng, dtype=torch.float)
C:\Users\FuGuodong\Desktop\pytorch_Study\Study_Video\yolov3_spp\models.py:148: TracerWarning: Converting a tensor to a Python float might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  self.ng = torch.tensor(ng, dtype=torch.float)
Traceback (most recent call last):
  File "C:/Users/FuGuodong/Desktop/pytorch_Study/Study_Video/yolov3_spp/train.py", line 292, in <module>
    train(hyp)
  File "C:/Users/FuGuodong/Desktop/pytorch_Study/Study_Video/yolov3_spp/train.py", line 187, in train
    w.add_graph(model.cpu(),input_data)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\utils\tensorboard\writer.py", line 714, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\utils\tensorboard\_pytorch_graph.py", line 285, in graph
    trace = torch.jit.trace(model, args)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\jit\__init__.py", line 955, in trace
    check_tolerance, strict, _force_outplace, _module_class)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\jit\__init__.py", line 1119, in trace_module
    check_tolerance, strict, _force_outplace, True, _module_class)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\py36\lib\site-packages\torch\jit\__init__.py", line 742, in _check_trace
    raise TracingCheckError(*diag_info)
torch.jit.TracingCheckError: Tracing failed sanity checks!
ERROR: Graphs differed across invocations!
	Graph diff:
		  graph(%self.1 : __torch__.models.Darknet,
		        %input.1 : Tensor):
		    %2 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="module_list"](%self.1)
		    %3 : __torch__.models.YOLOLayer = prim::GetAttr[name="113"](%2)
		    %4 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="module_list"](%self.1)
		    %5 : __torch__.torch.nn.modules.container.Sequential = prim::GetAttr[name="112"](%4)
		    %6 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="module_list"](%self.1)
。。。

**Comment by WZMIAOMIAO** [comment]
你说你没有改代码，但是我看你的报错信息中，train脚本的187的内容并不是我提供的脚本中的。
```
File "C:/Users/FuGuodong/Desktop/pytorch_Study/Study_Video/yolov3_spp/train.py", line 187, in train
w.add_graph(model.cpu(),input_data)
``

建议你先把我提供的代码跑通了在去自己改代码。

**Comment by dudiaoxifenglie** [comment]
非常感谢大佬，我这还没跑通呢，怎么会修改代码。这个YOLO_spp是你的教程中较早的版本，我这已经下载了最新的进行运行。
