### ISSUE TITLE
采用pytorch1.4跑YOLOv3-spp版本，删除双精度部分代码，程序out of memory

### ISSUE THREAD

**Issue by Taylor-X76** [WZMIAOMIAO/deep-learning-for-image-processing#252]
由于pytorch1.4版本不支持双精度（无from torch.cuda import amp）
所以修改有关双精度的代码
1.在train_eval_utils.py中，注释29和30行的  
    # enable_amp = True if "cuda" in device.type else False
    # scaler = amp.GradScaler(enabled=enable_amp)
2.注释61行        # with amp.autocast(enabled=enable_amp):
3. 并将85行的代码修改如下（删除scaler部分）：       
        # backward
        # scaler.scale(losses).backward()
        losses.backward()
        # optimize
        if ni % accumulate == 0:
            # scaler.step(optimizer)
            # scaler.update()
            # optimizer.zero_grad()
            optimizer.step()
            optimizer.zero_grad()
报错：RuntimeError: CUDA error: out of memory
解决办法：将torch.utils.data.DataLoader中pin_memory改成False

疑问：为什么单精度情况下pin_memory=True会报错？

**Comment by Taylor-X76** [comment]
但是经过训练，无mAP值
Accumulating evaluation results...
DONE (t=0.03s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000

**Comment by WZMIAOMIAO** [comment]
我没用1.4测试过，我也不清楚。
```
RuntimeError: CUDA error: out of memory
```
提示你GPU显存不够，可以尝试减少batch_size。
amp不是双精度，是混合精度。

**Comment by Taylor-X76** [comment]
> 我没用1.4测试过，我也不清楚。
> 
> ```
> RuntimeError: CUDA error: out of memory
> ```
> 
> 提示你GPU显存不够，可以尝试减少batch_size。
> amp不是双精度，是混合精度。

在VOC数据集上运行正常，加载预训练模型，训练五代的结果如下：
Accumulating evaluation results...
DONE (t=5.99s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.362
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.674
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.346
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.066
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.251
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.444
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.339
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.506
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.526
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.126
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.436
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.598

请问还有什么原因会导致，相同的网络在自己的数据集上AP为0的情况么，自己的数据集有4500张图片。

**Comment by WZMIAOMIAO** [comment]
可能你数据集标注的有问题，也可能索引和标签对不上。如果你的数据集是严格按照VOC来的是不会有问题的。

**Comment by Taylor-X76** [comment]
尝试了一下，不加载预训练模型.pt，训练VOC数据集，但是效果很差。
第一代mAP几乎为0，训练30代后mAP为0.1。
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.045
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.105
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.031
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.002
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.012
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.063
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.089
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.123
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.126
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.005
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.051
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.158
这种情况应该不太正常。
（而加载.pt后，前几个epoch就可以达到0.6+的mAP。）

**Comment by jay985735639** [comment]
> 实验试验，不加载预训练模型.pt，训练VOC数据集，但效果很差。
> 第一代mAP几乎为0，30代后mAP为0.1。
> IoU metric: bbox
> Average Precision (AP) @[ IoU = 0.50：0.95 | 面积=全部| maxDets=100 ] = 0.045
> 平均精度 (AP) @[ IoU=0.50 | 面积=全部| maxDets=100 ] = 0.105
> 平均精度 (AP) @[ IoU=0.75 | 面积=全部| maxDets=100 ] = 0.031
> 平均精度 (AP) @[ IoU=0.50:0.95 | 面积=小| maxDets=100 ] = 0.002
> 平均精度 (AP) @[ IoU=0.50:0.95 | 面积=中等 | maxDets=100 ] = 0.012
> 平均精度 (AP) @[ IoU=0.50:0.95 | 面积=大| maxDets=100 ] = 0.063
> 平均召回率 (AR) @[ IoU=0.50:0.95 | 面积=全部| maxDets= 1 ] = 0.089
> 平均召回率 (AR) @[ IoU=0.50:0.95 | 面积=全部| maxDets= 10 ] = 0.123
> 平均召回率 (AR) @[ IoU=0.50:0.95 | 面积=全部| maxDets = 100] = 0.126
> 平均召回率（AR）@ [IoU = 0.50：0.95 | 面积=小| maxDets=100 ] = 0.005
> 平均召回率 (AR) @[ IoU=0.50:0.95 | 面积=中等 | maxDets = 100] = 0.051
> 平均召回率（AR）@ [IoU = 0.50：0.95 | 面积=大| maxDets=100 ] = 0.158
> 这种情况应该不太正常。
> （而加载.pt后，前几个epoch就可以达到0.6+的mAP。）

那怎么办呢 我也遇到了这样的情况
