### ISSUE TITLE
在VOC07上跑的结果比原论文低了约7%的mAP[0.5]

### ISSUE THREAD

**Issue by LinfengYuan1997** [WZMIAOMIAO/deep-learning-for-image-processing#254]
在VOC2007的trainval图片上训练，在VOC2007test图片上测试结果是63%mAP[0.5] 但是Faster RCNN论文中提到的 测试结果应该是接近70%的（不过论文中proposals是300） 请问是因为某些设定不一样嘛？ 必如 冻结了backbone的一些层，可是如果VOC数据不够的话 冻结了效果不该更好吗？
![image](https://user-images.githubusercontent.com/79844318/117721788-dd7c5300-b212-11eb-886c-f00c56df32e8.png)

**Comment by WZMIAOMIAO** [comment]
你用的backbone是vgg吗？你确定你backbone改的是正确的吗？你确定你载入的backbone预训练权重是正确的吗？
