### ISSUE TITLE
为什么只有train loss 没有validation loss

### ISSUE THREAD

**Issue by HEFORSHEe** [WZMIAOMIAO/deep-learning-for-image-processing#258]
在good fit情况下，模型在若干轮过后，两个loss曲线都开始收敛，而且两者之间并没有肉眼的差距。是不是应该将这两类曲线画在一个图像中才能比较出来啊。

**Comment by WZMIAOMIAO** [comment]
需要可以自己加，参考train模式计算loss方法即可。
