### ISSUE TITLE
在VOC07上跑的结果比原论文低了约7%的mAP[0.5] (不好意思之前您回复我的问题我没看见问题关闭了)

### ISSUE THREAD

**Issue by LinfengYuan1997** [WZMIAOMIAO/deep-learning-for-image-processing#265]
原问题 ：

在VOC2007的trainval图片上训练，在VOC2007test图片上测试结果是63%mAP[0.5] 但是Faster RCNN论文中提到的 测试结果应该是接近70%的（不过论文中proposals是300） 请问是因为某些设定不一样嘛？ 必如 冻结了backbone的一些层，可是如果VOC数据不够的话 冻结了效果不该更好吗？

您的回复是：
你用的backbone是vgg吗？你确定你backbone改的是正确的吗？你确定你载入的backbone预训练权重是正确的吗？

回复：
我用的是vgg， 关于backbone我使用的是您在train_mobilenetv2.py里面注释的部分，然后把mobilev2注释掉了,载入的backbone是Pytorch官方下载的VGG。
![image](https://user-images.githubusercontent.com/79844318/119214953-24b0f080-bafd-11eb-991a-8c3db653aa1c.png)

另外还有个现象我不知道是不是造成这个现象的原因，我设置batchsize=1的时候VGG 可以达到68的mAP，但是设置bs=8的时候VGG就只有63了。。。。

最后感谢您的代码和快速的回复~~

**Comment by LinfengYuan1997** [comment]
bs=1的训练结果是符合论文的。。。。。但是我很好奇为什么BS=1效果比BS=8要好呀，是因为没有BN层 所以更新方向不那么稳定反而可以找到更优的点吗？
关于上面的结果我跑了至少三次，每次结果都是这样。。。。。
而且我用cityscapes的语义label生成的bbox来训练网络也是这个结果，对于VGG bs=1比bs=8效果要好 甚至可以逼近resnet-fpn

**Comment by WZMIAOMIAO** [comment]
一般数据集很小就可以冻结浅层，但如果数据量比较大就建议训练整个网络。
你说的batch_size 1比8要好，你可以尝试batch_size=8时把初始的learning rate放大5倍试下（要把warmup开启）。我个人猜测的是，训练同样的epoch，batch_size大则总的steps就会少，所以需要加大Learning rate

**Comment by LinfengYuan1997** [comment]
好的好的 我这就去试试看

**Comment by LinfengYuan1997** [comment]
> 一般数据集很小就可以冻结浅层，但如果数据量比较大就建议训练整个网络。
> 你说的batch_size 1比8要好，你可以尝试batch_size=8时把初始的learning rate放大5倍试下（要把warmup开启）。我个人猜测的是，训练同样的epoch，batch_size大则总的steps就会少，所以需要加大Learning rate

其实对于您提及的step问题 我是设置了足够多的epoch用来训练的 看曲线其实都是在结束前已经收敛了，不过可能learning rate的更新会有影响，多谢您的回复 我会去试试的

**Comment by frelwx** [comment]
> > 一般数据集很小就可以冻结浅层，但如果数据量比较大就建议训练整个网络。
> > 你说的batch_size 1比8要好，你可以尝试batch_size=8时把初始的learning rate放大5倍试下（要把warmup开启）。我个人猜测的是，训练同样的epoch，batch_size大则总的steps就会少，所以需要加大Learning rate
> 
> 其实对于您提及的step问题 我是设置了足够多的epoch用来训练的 看曲线其实都是在结束前已经收敛了，不过可能learning rate的更新会有影响，多谢您的回复 我会去试试的

后续如何呢，我可以问一下在learning_rate上你做了哪些尝试吗，谢谢
