### ISSUE TITLE
关于faster rcnn的评价指标

### ISSUE THREAD

**Issue by 745234332** [WZMIAOMIAO/deep-learning-for-image-processing#269]
您好，关于关于faster rcnn的评价指标有点问题向您请教下。就是您代码中给出的评价指标是map，是按照coco数据集的格式给出的，但是现在我想指导具体的每一类的ap指，不知道应该从哪里去修改代码呢？

**Comment by WZMIAOMIAO** [comment]
用validation文件

**Comment by wujihua628** [comment]
你好，validation.py文件好像是用的验证集的图片，但是实际上比较Map时用的是测试集的图片，是把验证集的图片改成测试集的图片就得到论文比较时用到的Map了嘛？  希望能能回复下~谢谢
