### ISSUE TITLE
cource_pdf

### ISSUE THREAD

**Issue by fighting-boy1** [WZMIAOMIAO/deep-learning-for-image-processing#27]
你好！从你的cource_pdf下载的课件ppt为什么总是提示无法打开文件，说是因为不支持该类型文件或已损坏。我用的wps,下载的文件也是没问题的，谁知道怎么解决吗？谢谢！

**Comment by WZMIAOMIAO** [comment]
单独下载是有问题，你直接下载整个项目，里面的pdf文件就是正常的。
