### ISSUE TITLE
分类模型的选择

### ISSUE THREAD

**Issue by mozeqiu** [WZMIAOMIAO/deep-learning-for-image-processing#276]
前辈你好，如果要训练上百个类的分类模型选择哪种网络结构比较好呢。后续会在移动设备上实验测试。数据集的每个类在几百张图片到一千多图片不等。

**Comment by WZMIAOMIAO** [comment]
自己多多拿几个模型试试呗，轻量级的像mobilenetv3，shufflenetv2等等

**Comment by mozeqiu** [comment]
> 自己多多拿几个模型试试呗，轻量级的像mobilenetv3，shufflenetv2等等
那如果我训练的分类数更多是不是提供的那个预训练模型就不能用了，只能自己从新开始训练，那应该怎么改呢

**Comment by WZMIAOMIAO** [comment]
你先去了解下什么是迁移学习好吧，然后看下我讲resnet的那几个视频。
