### ISSUE TITLE
fasterrcnn_resnet50_fpn_coco.pth这个预训练模型是不是在coco上面训练过了？

### ISSUE THREAD

**Issue by Senwang98** [WZMIAOMIAO/deep-learning-for-image-processing#279]
fasterrcnn_resnet50_fpn_coco.pth这个预训练模型是在coco上面训练过来在voc2012上面finetune？
那这样的话其实在voc12上面的结果其实不能用作比较了。

**Comment by WZMIAOMIAO** [comment]
1. 视频里说的很清楚哦，是pytorch官方提供的coco预训练权重。
2. 我并没有拿这个结果和别的比较。

**Comment by Senwang98** [comment]
哦哦，好
