### ISSUE TITLE
faster-rcnn的mobilenetv2版的validation和predict 可以有吗

### ISSUE THREAD

**Issue by HEFORSHEe** [WZMIAOMIAO/deep-learning-for-image-processing#280]
尝试了一下把代码中的resnet50+FPN改成了mobilenetv2 其他没变 载入权重以后 确实不行

**Comment by WZMIAOMIAO** [comment]
在视频里我有讲使用train_mobile的模型使用predict脚本时要将创建模型以及载入权重部分进行修改，仔细看下视频哦。validation文件也是一样的，需要该创建模型以及载入权重部分，readme里的注意事项写的很清楚。
