### ISSUE TITLE
为什么没有预训练的MobileNetV2，我多加了20个epoch但是效果还是好差

### ISSUE THREAD

**Issue by jay985735639** [WZMIAOMIAO/deep-learning-for-image-processing#281]
我感觉是不是我训练有问题

**Comment by WZMIAOMIAO** [comment]
那你可以问下pytorch官方为什么不提供mobilenetv2预训练模型，我在train_coco项目里提供了基于vgg的预训练模型，需要可以试下。

**Comment by jay985735639** [comment]
> 那你可以问下pytorch官方为什么不提供mobilenetv2预训练模型，我在train_coco项目里提供了基于vgg的预训练模型，需要可以试下。

好的谢谢了

**Comment by jay985735639** [comment]
我想我提错了问题 ，就是我在训练faster-rcnn的时候，backbone 这里 我把MobileNetV2中的weight参数删掉了，跑出来的效果不好，我这里主要是想改个backbone且backbone没有预训练模型。

**Comment by WZMIAOMIAO** [comment]
如果把MobileNetV2中的weight参数删掉效果还能好那我还加它干嘛，自己去了解下什么是迁移学习，仔细读下论文，看论文写的怎么训练的。没有预训练权重自己去coco上预训练。

**Comment by jay985735639** [comment]
> 如果把MobileNetV2中的weight参数删掉效果还能好那我还加它干嘛，自己去了解下什么是迁移学习，仔细读下论文，看论文写的怎么训练的。没有预训练权重自己去coco上预训练。

谢谢大佬，

**Comment by jay985735639** [comment]
大佬，我想问下就是我有model.py 就像你之前课里讲的那些分类网络一样，我应该用什么数据集训练 能够得到一个比较好的权重的.pth， 有没有trian脚本可以给我参考参考。跪求了谢谢大佬

**Comment by WZMIAOMIAO** [comment]
imagenet，随便找篇分类网络的文章里面都写的很清楚，在什么数据上训练，训练参数是什么，多读读论文。我没有训练脚本。

**Comment by jay985735639** [comment]
> imagenet，随便找篇分类网络的文章里面都写的很清楚，在什么数据上训练，训练参数是什么，多读读论文。我没有训练脚本。

好的 多谢大佬
