### ISSUE TITLE
faster-rcnn 中Validation .py 使用mobilenet模型验证失败

### ISSUE THREAD

**Issue by HEFORSHEe** [WZMIAOMIAO/deep-learning-for-image-processing#282]
readme 好像没写怎么换backbone,只说了改三个参数调用rsn50,视频里有讲吗？

**Comment by WZMIAOMIAO** [comment]
predice脚本里就有使用mobilenet的backbone的代码啊，我视频里也说了predict脚本里怎么使用mobilenet的backbone，说实话自己多读读代码，代码里都写得很清楚。

**Comment by HEFORSHEe** [comment]
不是predict ，是validation.py那个脚本，运行这个脚本就是想看看每个类别的精度，但是只有import rsn50的模型。

**Comment by WZMIAOMIAO** [comment]
是你没懂我说的，创建模型载入权重都是一样的步骤，predict里面就有，如果你看懂了自己就可以改validation
