### ISSUE TITLE
预测速度的问题

### ISSUE THREAD

**Issue by projektarbeit1** [WZMIAOMIAO/deep-learning-for-image-processing#289]
楼主，你好，我利用你的代码在pytorch框架下用resnet训练了一个40类的图像分类模型，准确率还不错，但是用这个模型来进行批量图片预测和打标的时候，速度不是很快，大概一张需要1.5秒左右，我这里大概有100万张图片要打标，你这里有没有什么比较好的方法推荐呢？谢谢

**Comment by WZMIAOMIAO** [comment]
最简单的方法换个好点的GPU去推理。
麻烦的方法，量化或者剪枝。

**Comment by projektarbeit1** [comment]
好的，谢谢楼主，我去了解一下量化和剪枝，这个issue可以关了哈。不太会弄这个，不知道怎么发私信。
