### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by ChineseHuang** [WZMIAOMIAO/deep-learning-for-image-processing#291]
您好，我将DOTA的数据集转为VOC格式后，使用train_res50_fpn.py进行训练会出现CUDA out of memory，之前根据您的讲解，使用
train_mobilenetv2.py跑VOC2012的数据是可以的，请问有什么好的解决办法吗，我已经将batch_size调为1了。

RuntimeError: CUDA out of memory. Tried to allocate 350.00 MiB (GPU 0; 4.00 GiB total capacity; 2.53 GiB already allocated; 252.61 MiB free; 2.58 GiB reserved in total by PyTorch)

**Comment by ChineseHuang** [comment]
wh = (rb - lt).clamp(min=0)  # [N,M,2]
在这一步报错的

**Comment by WZMIAOMIAO** [comment]
换个显存大点的GPU，现在要跑深度学习，最低8G显存。你这4G吃不消。

**Comment by ChineseHuang** [comment]
好的
