### ISSUE TITLE
用了tf.function修饰器就出现了警告

### ISSUE THREAD

**Issue by dianjxu** [WZMIAOMIAO/deep-learning-for-image-processing#292]
WARNING:tensorflow:AutoGraph could not transform <bound method MyModel.call of <model.MyModel object at 0x00000172D60EA898>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: No module named 'tensorflow_core.estimator'

警告如上，重新安装tensorflow-estimator也没用，好像是转换图结构有问题，如果不用修饰器，就不会出现警告，请问怎么解决了？大佬

**Comment by WZMIAOMIAO** [comment]
没遇到过你说的情况，你的tf版本是2.4或者以上吗？如果是的还有这个问题，你就去官方提bug吧。

**Comment by dianjxu** [comment]
我用的版本是2.1的cpu版本，问题今天解决了，是tensorflow-estimator版本不匹配造成的，我从2.5降级到2.1就没有这个警告了
