### ISSUE TITLE
数据集下载不了

### ISSUE THREAD

**Issue by jolt2017** [WZMIAOMIAO/deep-learning-for-image-processing#299]
http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar 
数据集链接打不开

**Comment by WZMIAOMIAO** [comment]
最近网络不太稳定，可以尝试用百度云下载：
链接：https://pan.baidu.com/s/1EldOUxNH04esU-nfA4YbDQ 
提取码：qimg

**Comment by jolt2017** [comment]
> 最近网络不太稳定，可以尝试用百度云下载：
> 链接：https://pan.baidu.com/s/1EldOUxNH04esU-nfA4YbDQ
> 提取码：qimg

好的 非常感谢
