### ISSUE TITLE
问一个faster 模型细节 为什么有两个回归

### ISSUE THREAD

**Issue by macqueen09** [WZMIAOMIAO/deep-learning-for-image-processing#301]
RPN部分中，每个anchor可以给出9种尺度，也就是9个方块，训练分类器判断是否是目标的二分类，训练回归器回归其边界（使得边界更准确）
如果是目标，再给fast RNN模型，进行多分类，边框回归。
那么，为啥RPN部分还要回归，二分类完给fast RCNN不可以吗？

**Comment by WZMIAOMIAO** [comment]
我理解是的
