### ISSUE TITLE
yolov3label数据缓存读取

### ISSUE THREAD

**Issue by coderhukai** [WZMIAOMIAO/deep-learning-for-image-processing#302]
![image](https://user-images.githubusercontent.com/68494594/122183535-e7523f80-cebd-11eb-9c33-277e4cf20fff.png)
你好，我有2个问题：
1、为什么我执行并不会生成npy缓存文件，还是从文件中读取的数据？
2、npy缓存中读取和从文件中读取哪个快？

**Comment by WZMIAOMIAO** [comment]
文件生成在对应train和val目录下，你是没找对位置吧。

**Comment by coderhukai** [comment]
解决了，谢谢！
