### ISSUE TITLE
 def __getitem__(self, index):

### ISSUE THREAD

**Issue by why228430** [WZMIAOMIAO/deep-learning-for-image-processing#307]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by why228430** [comment]
你好！请问在哪使用的datasets中LoadImagesAndLabels函数的这个方法。

**Comment by WZMIAOMIAO** [comment]
DataLoader会自动调用，建议你去看下我之前讲的自定义数据集的视频。
