### ISSUE TITLE
请问时候支持多标签任务呢？

### ISSUE THREAD

**Issue by shihanyu** [WZMIAOMIAO/deep-learning-for-image-processing#316]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by shihanyu** [comment]
你好我是从BILIBILI过来的，讲得特别好。有个问题。
1.跟标题一样是否支持多标签分类。在predict.py文件中有，在预测的过程中有一句softmax（），是不是不用softmax，直接将最后一层输出卡个阈值就能实现多标签分类呢？

**Comment by carolxiege** [comment]
额，我跟你一样是学生，我也刚学这个，你说的是哪一节的？你是不是找错人了？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月5日(星期一) 晚上7:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 请问时候支持多标签任务呢？ (#316)





 
你好我是从BILIBILI过来的，讲得特别好。有个问题。
 1.跟标题一样是否支持多标签分类。在predict.py文件中有，在预测的过程中有一句softmax（），是不是不用softmax，直接将最后一层输出卡个阈值就能实现多标签分类呢？

**Comment by shihanyu** [comment]
mobilenet的predict.py

**Comment by WZMIAOMIAO** [comment]
抱歉，我暂时还没做过多标签的图像分类任务，我觉得也不是改个softmax这么简单。我这里提供的只能进行单分类。多标签分类的话训练的数据输入，损失函数等都需要做修改。

**Comment by shihanyu** [comment]
谢谢，我会持续关注你，期待会有相关的课程。
