### ISSUE TITLE
Roadmap - 2021 (今年计划)

### ISSUE THREAD

**Issue by WZMIAOMIAO** [WZMIAOMIAO/deep-learning-for-image-processing#328]
图像分类：
- [x] EfficientNetV2
- [x] VisionTransformer
- [x] SwinTransformer

目标检测：
- [x] 补完SSD代码讲解
- [x] 补完yolov3 spp代码讲解

图像分割：
- [x] FCN

**Comment by Seperendity** [comment]
希望up能在v3中讲讲大概怎么在cfg形式的网络文件中加入注意力或者什么其他的模块应该大概怎么修改代码，暂时没找到具体怎么针对这种形式的就网络修改

**Comment by Mankvis** [comment]
Efficientdet 会加入吗
