### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Darknet: Missing key(s) in state_dict: "total_ops", "total_params", "module_list.total_ops", "

### ISSUE THREAD

**Issue by Lqqqying** [WZMIAOMIAO/deep-learning-for-image-processing#330]
跑validation.py和predict.py时，加载模型会报错
RuntimeError: Error(s) in loading state_dict for Darknet:
	Missing key(s) in state_dict: "total_ops", "total_params", "module_list.total_ops", "module_list.total_params", "module_list.0.total_ops", "module_list.0.total_params", "module_list.1.total_ops", "module_list.1.total_params", "module_list.2.total_ops", "module_list.2.total_params", "module_list.3.total_ops", "module_list.3.total_params", "module_list.4.total_ops", "module_list.4.total_params", "module_list.5.total_ops", "module_list.5.total_params", "module_list.6.total_ops", "module_list.6.total_params", "module_list.7.total_ops", "module_list.7.total_params", "module_list.8.total_ops", "module_list.8.total_params", "module_list.9.total_ops", "module_list.9.total_params", "module_list.10.total_ops", "module_list.10.total_params", "module_list.11.total_ops", "module_list.11.total_params", "module_list.12.total_ops", "module_list.12.total_params", "module_list.13.total_ops", "module_list.13.total_params", "module_list.14.total_ops", "module_list.14.total_params", "module_list.15.total_ops", "module_list.15.total_params", "module_list.16.total_ops", "module_list.16.total_params", "module_list.17.total_ops", "module_list.17.total_params", "module_list.18.total_ops", "module_list.18.total_params", "module_list.19.total_ops", "module_list.19.total_params", "module_list.20.total_ops", "module_list.20.total_params", "module_list.21.total_ops", "module_list.21.total_params", "module_list.22.total_ops", "module_list.22.total_params", "module_list.23.total_ops", "module_list.23.total_params", "module_list.24.total_ops", "module_list.24.total_params", "module_list.25.total_ops", "module_list.25.total_params", "module_list.26.total_ops", "module_list.26.total_params", "module_list.27.total_ops", "module_list.27.total_params", "module_list.28.total_ops", "module_list.28.total_params", "module_list.29.total_ops", "module_list.29.total_params", "module_list.30.total_ops", "module_list.30.total_params", "module_list.31.total_ops", "module_list.31.total_params", "module_list.32.total_ops", "module_list.32.total_params", "module_list.33.total_ops", "module_list.33.total_params", "module_list.34.total_ops", "module_list.34.total_params", "module_list.35.total_ops", "module_list.35.total_params", "module_list.36.total_ops", "module_list.36.total_params", "module_list.37.total_ops", "module_list.37.total_params", "module_list.38.total_ops", "module_list.38.total_params", "module_list.39.total_ops", "module_list.39.total_params", "module_list.40.total_ops", "module_list.40.total_params", "module_list.41.total_ops", "module_list.41.total_params", "module_list.42.total_ops", "module_list.42.total_params", "module_list.43.total_ops", "module_list.43.total_params", "module_list.44.total_ops", "module_list.44.total_params", "module_list.45.total_ops", "module_list.45.total_params", "module_list.46.total_ops", "module_list.46.total_params", "module_list.47.total_ops", "module_list.47.total_params", "module_list.48.total_ops", "module_list.48.total_params", "module_list.49.total_ops", "module_list.49.total_params", "module_list.50.total_ops", "module_list.50.total_params", "module_list.51.total_ops", "module_list.51.total_params", "module_list.52.total_ops", "module_list.52.total_params", "module_list.53.total_ops", "module_list.53.total_params", "module_list.54.total_ops", "module_list.54.total_params", "module_list.55.total_ops", "module_list.55.total_params", "module_list.56.total_ops", "module_list.56.total_params", "module_list.57.total_ops", "module_list.57.total_params", "module_list.58.total_ops", "module_list.58.total_params", "module_list.59.total_ops", "module_list.59.total_params", "module_list.60.total_ops", "module_list.60.total_params", "module_list.61.total_ops", "module_list.61.total_params", "module_list.62.total_ops", "module_list.62.total_params", "module_list.63.total_ops", "module_list.63.total_params", "module_list.64.total_ops", "module_list.64.total_params", "module_list.65.total_ops", "module_list.65.total_params", "module_list.66.total_ops", "module_list.66.total_params", "module_list.67.total_ops", "module_list.67.total_params", "module_list.68.total_ops", "module_list.68.total_params", "module_list.69.total_ops", "module_list.69.total_params", "module_list.70.total_ops", "module_list.70.total_params", "module_list.71.total_ops", "module_list.71.total_params", "module_list.72.total_ops", "module_list.72.total_params", "module_list.73.total_ops", "module_list.73.total_params", "module_list.74.total_ops", "module_list.74.total_params", "module_list.75.total_ops", "module_list.75.total_params", "module_list.76.total_ops", "module_list.76.total_params", "module_list.77.total_ops", "module_list.77.total_params", "module_list.79.total_ops", "module_list.79.total_params", "module_list.81.total_ops", "module_list.81.total_params", "module_list.83.total_ops", "module_list.83.total_params", "module_list.84.total_ops", "module_list.84.total_params", "module_list.85.total_ops", "module_list.85.total_params", "module_list.86.total_ops", "module_list.86.total_params", "module_list.87.total_ops", "module_list.87.total_params", "module_list.88.total_ops", "module_list.88.total_params", "module_list.89.total_ops", "module_list.89.total_params", "module_list.90.total_ops", "module_list.90.total_params", "module_list.91.total_ops", "module_list.91.total_params", "module_list.93.total_ops", "module_list.93.total_params", "module_list.94.total_ops", "module_list.94.total_params", "module_list.95.total_ops", "module_list.95.total_params", "module_list.96.total_ops", "module_list.96.total_params", "module_list.97.total_ops", "module_list.97.total_params", "module_list.98.total_ops", "module_list.98.total_params", "module_list.99.total_ops", "module_list.99.total_params", "module_list.100.total_ops", "module_list.100.total_params", "module_list.101.total_ops", "module_list.101.total_params", "module_list.102.total_ops", "module_list.102.total_params", "module_list.103.total_ops", "module_list.103.total_params", "module_list.105.total_ops", "module_list.105.total_params", "module_list.106.total_ops", "module_list.106.total_params", "module_list.107.total_ops", "module_list.107.total_params", "module_list.108.total_ops", "module_list.108.total_params", "module_list.109.total_ops", "module_list.109.total_params", "module_list.110.total_ops", "module_list.110.total_params", "module_list.111.total_ops", "module_list.111.total_params", "module_list.112.total_ops", "module_list.112.total_params", "module_list.113.total_ops", "module_list.113.total_params".

这是什么原因呢？

**Comment by WZMIAOMIAO** [comment]
没遇到过你说的问题
1. 自己检查下是不是按照requirements.txt配置的环境
2. 自己是否成功训练了网络
3. 预测脚本中使用的cfg文件以及权重是否是你训练生成的

**Comment by WZMIAOMIAO** [comment]
我刚搜了一下，是因为你安装了thop包，thop会导致total_params以及total_ops被注册到网络中。但权重里并没有这个参数。最简单的方式就是卸载thop包即可。
```
pip uninstall thop
```
