### ISSUE TITLE
Temporal Action Localization

### ISSUE THREAD

**Issue by KingQino** [WZMIAOMIAO/deep-learning-for-image-processing#34]
老哥，我好崇拜你啊。你看能不能找机会做一下这篇文章，"Rethinking the Faster R-CNN Architecture for Temporal Action Localization"，原作者没有提供代码。

**Comment by dayfixer** [comment]
图像分割还没讲到，这个时序动作定位估计。。。

**Comment by KingQino** [comment]
哈哈哈
