### ISSUE TITLE
up大大 好像发现个问题

### ISSUE THREAD

**Issue by lblbk** [WZMIAOMIAO/deep-learning-for-image-processing#345]
这个地方参数是不是应该是 `args.cuda` 因为并没有定义 `gpu` 这个参数呀

https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/5ec12a2f39078621a0c7e3ed4f6ca1dde0c2c2b0/pytorch_classification/train_multi_GPU/train_multi_gpu_using_launch.py#L122

**Comment by WZMIAOMIAO** [comment]
在```init_distributed_mode```函数中已经```torch.cuda.set_device(args.gpu)```指定当前设备了，所以可以不用，我记得在1.9版本还是哪个版本之前是没有问题的。之后的版本好像会报warning，后续可能需要加上。

**Comment by WZMIAOMIAO** [comment]
在```init_distributed_mode```初始化函数中有指定这个参数哦:
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_classification/train_multi_GPU/multi_train_utils/distributed_utils.py#L11

**Comment by lblbk** [comment]
> 在`init_distributed_mode`初始化函数中有指定这个参数哦:
> https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_classification/train_multi_GPU/multi_train_utils/distributed_utils.py#L11

哎呀 尴尬 没好好看源码🌚
