### ISSUE TITLE
up，你好想问一下出现w/h小于0的什么原因？

### ISSUE THREAD

**Issue by ily666666** [WZMIAOMIAO/deep-learning-for-image-processing#352]
up，你好想问一下，在训练FasterRCNN的时候 出现some boxes的w/h小于0的什么原因？
是因为 用labelImg 标注的数据的时候只能从左上角向右下角标注吗？反着标就小于0了？还是什么别的原因，困惑好久了

**Comment by WZMIAOMIAO** [comment]
自己标注过程中可能误操作，出现w或者h小于等于0的情况。根据提示可以查看对应xml文件，查看里面目标的w和h。然后重新标注一下就行了。
