### ISSUE TITLE
faster_rcnn/predict.py issues

### ISSUE THREAD

**Issue by SakuraLH** [WZMIAOMIAO/deep-learning-for-image-processing#356]
**System information**
* OS Platform: linux
* Python version: 3.6
* torch version: 1.6.0
* Use GPU or not: GPU
* The network you trained: res50+fpn

**Describe the current behavior**
up你好，我按照你的方式生成了自己的PascalVOC数据集，重写了Jason文件，修改了train_res50_fpn.py，可以成功训练模型，并生成save_weights。
但在运行predic.py的时候，显示如下错误：
Traceback (most recent call last):
  File "/root/Code/my_faster_rcnn/predict.py", line 112, in <module>
    main()
  File "/root/Code/my_faster_rcnn/predict.py", line 58, in main
    model.load_state_dict(torch.load(train_weights, map_location=device)["model"])
  File "/root/anaconda3/envs/fasterRCNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FasterRCNN:
	size mismatch for roi_heads.box_predictor.cls_score.weight: copying a param with shape torch.Size([2, 1024]) from checkpoint, the shape in current model is torch.Size([1, 1024]).
	size mismatch for roi_heads.box_predictor.cls_score.bias: copying a param with shape torch.Size([2]) from checkpoint, the shape in current model is torch.Size([1]).
	size mismatch for roi_heads.box_predictor.bbox_pred.weight: copying a param with shape torch.Size([8, 1024]) from checkpoint, the shape in current model is torch.Size([4, 1024]).
	size mismatch for roi_heads.box_predictor.bbox_pred.bias: copying a param with shape torch.Size([8]) from checkpoint, the shape in current model is torch.Size([4]).
我猜测是由于我自己的数据集只有一种类别导致predict.py中的model.load_state_dict()出现导入参数不匹配的问题，但不清楚torch.Size([1, 1024])、torch.Size[2]、torch.Size([4, 1024])等的含义，可以告诉我这些参数的意义和在代码中的位置并且如何解决这个bug么？非常感谢up

**Comment by cp1108** [comment]
我也有类似的问题，不过我是对pytorch 官方的fasterrcnn_resnet50_fpn_coco.pth模型再次用coco数据集训练几轮后，将训练得到的模型当做预训练的模型进行加载时，出现类似的size mismatch

**Comment by cp1108** [comment]
应该是num_class的问题，和模型的不一致

**Comment by WZMIAOMIAO** [comment]
应该是你num_classes设置的不对，create_model传入的num_classes是要加上背景的。

**Comment by SakuraLH** [comment]
> 应该是你num_classes设置的不对，create_model传入的num_classes是要加上背景的。

感谢，已经解决
