### ISSUE TITLE
faster-rcnn res50-fpn网络改为res101-fpn

### ISSUE THREAD

**Issue by cp1108** [WZMIAOMIAO/deep-learning-for-image-processing#358]
大佬您好，我想把网络从res50_fpn改为res101_fpn，但因为涉及到fpn，想请问大概需要修改哪些部分的代码呢？

**Comment by WZMIAOMIAO** [comment]
把https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/4fa8c4ffcebf3db1845d6bc574288469b22aba55/pytorch_object_detection/faster_rcnn/backbone/resnet50_fpn_model.py#L252-L254

改成：
```python
import torchvision
resnet_backbone = torchvision.models.resnet101(pretrained=True, norm_layer=norm_layer)
```
但改后就无法使用coco的预训练权重了。
