### ISSUE TITLE
googlenet

### ISSUE THREAD

**Issue by 1579109909** [WZMIAOMIAO/deep-learning-for-image-processing#36]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by 1579109909** [comment]
hello, thanks to your code here for my sdudies,i want to know what version is the googlenet ?
inception v3 or other version? 
Thanks !!

**Comment by super-wz** [comment]
googlenet is inception v1.
