### ISSUE TITLE
加载预训练模型之后，又想修改inputchannel应该怎么改呢

### ISSUE THREAD

**Issue by happysheep224** [WZMIAOMIAO/deep-learning-for-image-processing#397]
您好，
      我想用Resnet跑我的高光谱数据，我的高光谱数据的channels是35，然后我还想用迁移学习，但是我改动之后，每次还是会报错，说expected 3， 但是我给的是35， 我该怎么修改才可以呢？

**Comment by WZMIAOMIAO** [comment]
改了就不能用迁移学习

**Comment by happysheep224** [comment]
> 改了就不能用迁移学习

谢谢
