### ISSUE TITLE
COCO class num 问题

### ISSUE THREAD

**Issue by a751565522** [WZMIAOMIAO/deep-learning-for-image-processing#40]
为什么测试faster RCNN 官方的resnet50 rpn网络权重时，num_classes要设成91， coco不应该是81吗？

顺便问一下，哪里可以找到coco类别的json文件啊？

**Comment by WZMIAOMIAO** [comment]
coco官方给的介绍："80 object categories, 91 stuff categories", "Whereas the detection task addresses thing classes (person, car, elephant), the stuff task focuses on stuff classes (grass, wall, sky) and the newly introduced panoptic task addresses both simultaneously." 我个人的理解是可根据不同的任务选择不同的检测类别数，我看过一些目标检测项目确实有使用80类的也有使用90类的。
coco类别的json文件你可以自己写个python脚本生成一个，网上都能搜到具体哪些类别的。

**Comment by a751565522** [comment]
> coco官方给的介绍："80 object categories, 91 stuff categories", "Whereas the detection task addresses thing classes (person, car, elephant), the stuff task focuses on stuff classes (grass, wall, sky) and the newly introduced panoptic task addresses both simultaneously." 我个人的理解是可根据不同的任务选择不同的检测类别数，我看过一些目标检测项目确实有使用80类的也有使用90类的。
> coco类别的json文件你可以自己写个python脚本生成一个，网上都能搜到具体哪些类别的。

thank you！
