### ISSUE TITLE
请问这个和u版的精度比起来怎么样？

### ISSUE THREAD

**Issue by Dandelion111** [WZMIAOMIAO/deep-learning-for-image-processing#400]

**Comment by WZMIAOMIAO** [comment]
我是用的之前yolov3spp老版的代码，后来作者又更新了。应该更新后的会好些。

**Comment by Dandelion111** [comment]
> 我是用的之前yolov3spp老版的代码，后来作者又更新了。应该更新后的会好些。

好的，谢谢大佬，原作者更新是加了一些技巧吧，基本的理论框架应该没有变吧？用大佬的代码学习一下算法的流程可以吗？原版的代码实在是太不精简了

**Comment by WZMIAOMIAO** [comment]
模型框架基本还是一样的，仅仅用来学习是没问题的
