### ISSUE TITLE
求教segmentation for Swin

### ISSUE THREAD

**Issue by Lsz-20** [WZMIAOMIAO/deep-learning-for-image-processing#402]
大神你好，看了讲解真的非常清晰啦！小白一枚想要魔改，有些地方想要请教一下。!
目前是在跑官方mmsgementation下的swin和原作者‘segmentation for Swin’这两个代码
1.关于您说的多尺度问题，查看了两个原代码，发现这部分好像并没有您说的使用固定尺寸的问题（附图：）
![image](https://user-images.githubusercontent.com/60343452/141601154-9fc4f292-1027-41c4-b6c1-3c675bbac162.png)
2.不知道您是否尝试过运行这部分的内容，发现在官方提供的pretrain下原作者的code运行结果很差，但是mmsegmentation下效果较好，出现了以下参数不对应的问题：
![image](https://user-images.githubusercontent.com/60343452/141601006-1eb72c68-8e24-4e4e-a51b-ca1a954f1562.png)

感谢解答~

**Comment by WZMIAOMIAO** [comment]
没对比过，建议去官方提issue

**Comment by Lsz-20** [comment]
> 没对比过，建议去官方提issue

好的，就是因为一直没有回复，也找不到类似的问题/(ㄒoㄒ)/~~

**Comment by Lsz-20** [comment]
> 没对比过，建议去官方提issue

不好意思再打扰一下，上图1的两个code关于attention mask部分的是否保证了多尺度呀？并非您视频中所说官方代码是固定尺寸？（我认为是多尺度的，并非固定尺寸）

**Comment by WZMIAOMIAO** [comment]
我说的固定尺度是原论文对应的仓库：
https://github.com/microsoft/Swin-Transformer

我没看过对应分割的仓库，暂不清楚。

**Comment by Lsz-20** [comment]
> 我说的固定尺度是原论文对应的仓库： https://github.com/microsoft/Swin-Transformer
> 
> 我没看过对应分割的仓库，暂不清楚。

哦哦这样 好的 谢谢解答！
