### ISSUE TITLE
请教collate_fn

### ISSUE THREAD

**Issue by ssssww0905** [WZMIAOMIAO/deep-learning-for-image-processing#410]
Up！我想请教一下，如果继承自 `torch.utils.data.Dataset` 的类中 `__getitem__`返回的是一个字典，还需要特意设定`torch.utils.data.DataLoader`中的`collate_fn`参数吗？

**Comment by WZMIAOMIAO** [comment]
看个人需求，像目标检测这种比较麻烦的任务一般都要自己写collate_fn
