### ISSUE TITLE
关于可视化的问题

### ISSUE THREAD

**Issue by Lsz-20** [WZMIAOMIAO/deep-learning-for-image-processing#412]
大神你好 想问一下关于您feature map可视化的问题？
这种办法是否使用于transformer模型呢（非官方，自定义的model）
还有就是transformer中如果想要可视化attention map的话（就是QKV计算那里，也是自定义模型），这种方法也适用吗？
感谢回复！

**Comment by WZMIAOMIAO** [comment]
按照视频里的方法可以获取任何层的feature map，不过前提是你得知道每个层的具体名称。要获取attention map的话，另外需要自己修改对应的自定义模型部分。
