### ISSUE TITLE
一些困惑

### ISSUE THREAD

**Issue by leileilin** [WZMIAOMIAO/deep-learning-for-image-processing#416]
你好，
我对/pytorch_classification/train_multi_GPU/train_multi_gpu_using_launch.py文件的101行不是很理解，为什么初始化权重不一致？
非常感谢！

**Comment by WZMIAOMIAO** [comment]
初始化都是随机的

**Comment by leileilin** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    那如果我调用huggingface的预训练模型，在此基础上微调，应该不需要做这个同步权重的操作吧？非常感谢！
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1299192319
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年12月6日 ***@***.***> 写道： 




初始化都是随机的



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leileilin** [comment]
你好，
我这两天实现了ddp的机制，代码能够成功跑通，但是训练的meanloss不降低，不知道为什么？
你能帮我解答一下吗？
非常感谢！

**Comment by WZMIAOMIAO** [comment]
实现ddp？官方有现成优化好的方法呀、

**Comment by WZMIAOMIAO** [comment]
你自己多看看官方文档吧，https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

**Comment by leileilin** [comment]
> 实现ddp？官方有现成优化好的方法呀、

我说的实现是指你代码那块的ddp迁移到我这边，不是从头实现。
