### ISSUE TITLE
请问为什么pytorch训练Faster-RCNN，出来的权重文件那么大？能不能修改只get它模型的权重？

### ISSUE THREAD

**Issue by nit-hmz** [WZMIAOMIAO/deep-learning-for-image-processing#417]
不知道为什么，训练出来的的权重文件有几百MB大，我训练的是faster-rcnn+mobilenetv2，按道理来说应该只有十几MB，是不是包含了其他的东西？

**Comment by WZMIAOMIAO** [comment]
保存的信息中还包含了优化器等信息，如果只要模型的权重，只需保存```model.state_dict()```即可

https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/34a06af362ff54a23e0a112a633e9dbac83d94cf/pytorch_object_detection/faster_rcnn/train_mobilenetv2.py#L205-L209

**Comment by nit-hmz** [comment]
感谢您的回复
