### ISSUE TITLE
大佬您好，我昨天向您提问为什么faster-rcnn-mobilenetv2训练出来的模型为什么这么大，现在还是没有解决！

### ISSUE THREAD

**Issue by nit-hmz** [WZMIAOMIAO/deep-learning-for-image-processing#418]
save_files = {
                'model': model.state_dict(),
                #'optimizer': optimizer.state_dict(),
                #'lr_scheduler': lr_scheduler.state_dict(),
                #'epoch': epoch
                }
            torch.save(save_files, "./save_weights/mobile-model-{}.pth".format(epoch))
上面我已经是把其他的备注#了，只留下model，但是训练出来的mobile-model-2.pth有322MB大，应该是还有其他东西在吧？我看出来的pretrin.pth也是这么大？是不是还需要修改其他的地方？

**Comment by WZMIAOMIAO** [comment]
那就是正常的，因为使用的预测特征层的channels太大了（1280），导致权重很大。如果换个channels小点的特征层就会小很多。

**Comment by nit-hmz** [comment]
请问大佬，加入输入的尺寸是224-224，Faster-rcnn的RPN是取resnet-50的14-14尺寸的特征图，还是取7-7的特征图？我看到您的是取7-7的特征图，但是我看其他有的人的代码是取14-14的特征图？请问那种更好呢？

**Comment by WZMIAOMIAO** [comment]
建议14x14的，即下采样16倍的。

**Comment by nit-hmz** [comment]
好的谢谢回复
