### ISSUE TITLE
faster rcnn的transform问题

### ISSUE THREAD

**Issue by heyxhh** [WZMIAOMIAO/deep-learning-for-image-processing#42]
感谢分享，我有个问题想请教一下作者。
在faster rcnn的transform.py中有将多张图像在resize后打包成batch的操作。
而transform是在dataset类的get_item中调用的：
if self.transforms is not None:
            image, target = self.transforms(image, target)
但是dataset类中是每次拿取一张图像，batch size应该是在调用dataloader时才指定的，在这里是如何打包成batch的呢？

**Comment by WZMIAOMIAO** [comment]
有两个transform函数，network_files下的transform函数不是在dataset中调用的，在源码解析视频里说的很清楚。

**Comment by heyxhh** [comment]
> 有两个transform函数，network_files下的transform函数不是在dataset中调用的，在源码解析视频里说的很清楚。

找到了 谢谢

**Comment by heyxhh** [comment]
封装图像成batch时是使用填充的方法，而不是把所有image resize成一样尺寸，前面做resize是为了做图像增强吗

**Comment by WZMIAOMIAO** [comment]
前面的resize是限制输入图像的最大最小边长
