### ISSUE TITLE
大佬你好，我是从b站过来的；我想修改一下ResNet50+FPN的网络，在里面添加一些模块，但是没有对应的预训练权重，可以上传一下ResNet50+FPN的训练的代码吗

### ISSUE THREAD

**Issue by RooKichenn** [WZMIAOMIAO/deep-learning-for-image-processing#423]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
麻烦你仔细看下视频或者项目的readme，清清楚楚写了权重在哪下载。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/tree/master/pytorch_object_detection/faster_rcnn

**Comment by WZMIAOMIAO** [comment]
你要是想在coco上训练，就参考train_coco的项目
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/tree/master/pytorch_object_detection/train_coco_dataset

**Comment by RooKichenn** [comment]
谢谢大哥，我去看看coco数据集！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月10日(星期五) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 大佬你好，我是从b站过来的；我想修改一下ResNet50+FPN的网络，在里面添加一些模块，但是没有对应的预训练权重，可以上传一下ResNet50+FPN的训练的代码吗 (Issue #423)





 
麻烦你仔细看下视频或者项目的readme，清清楚楚写了权重在哪下载。
 https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/tree/master/pytorch_object_detection/faster_rcnn
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
