### ISSUE TITLE
ddp spawn启动方式

### ISSUE THREAD

**Issue by lblbk** [WZMIAOMIAO/deep-learning-for-image-processing#426]
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/2c825cd5f9b26a91a3701dc9ba64d5912ebba4e3/pytorch_classification/train_multi_GPU/train_multi_gpu_using_spawn.py#L21

up大大 我看另一个作者的启动方式也是不传 `rank` 参数，链接在这儿，这个 `rank` 参数可以自动获取吗 
https://github.com/PeterL1n/RobustVideoMatting/blob/f8a26e27198a93a94bfd06e96b8d5a34d0660f81/train.py#L502

还有就是launch的启动方式中声明的device好像系统不会默认修改，导致我多卡训练时第一块儿显存特别高，不知道是不是我启动命令的原因

**Comment by WZMIAOMIAO** [comment]
自动获取
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/2c825cd5f9b26a91a3701dc9ba64d5912ebba4e3/pytorch_classification/train_multi_GPU/multi_train_utils/distributed_utils.py#L7-L18
