### ISSUE TITLE
About how to continue train the model-X.pth file.

### ISSUE THREAD

**Issue by JieJayCao** [WZMIAOMIAO/deep-learning-for-image-processing#427]
Thank you very much for reproducing the various image classification models.
When I use the ViT to classify my own dataset for some epoches, I get the model-X.pth file, but I would like to ask how to load these trained models (pth file) to continue training.

I look forward to your answers.

**Comment by WZMIAOMIAO** [comment]
自己参考之前讲的目标检测代码自己改吧。
- 保存权重等：
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/2c825cd5f9b26a91a3701dc9ba64d5912ebba4e3/pytorch_object_detection/faster_rcnn/train_res50_fpn.py#L157-L165

- 载入之前的权重等：
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/2c825cd5f9b26a91a3701dc9ba64d5912ebba4e3/pytorch_object_detection/faster_rcnn/train_res50_fpn.py#L118-L127
