### ISSUE TITLE
大佬问下VGG分类model里面最后输出是batch_size*num_class但是label是batch_size*1这个没法算loss吧程序会报错

### ISSUE THREAD

**Issue by liufeng34** [WZMIAOMIAO/deep-learning-for-image-processing#428]

**Comment by WZMIAOMIAO** [comment]
建议你好好看看文档：
https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html?highlight=cross#torch.nn.CrossEntropyLoss
