### ISSUE TITLE
关于目标检测指标的问题

### ISSUE THREAD

**Issue by maodong2056** [WZMIAOMIAO/deep-learning-for-image-processing#43]
你好，我在B站看了您的视频，觉得讲的特别好，我在实际应用中也遇到了一些问题；
类似于目标检测的问题，我研究的是时间行为定位（一个2D，一个1D）计算指标的方式差不多，现在我要计算mAP

前提：一共20类行为，213个测试视频，每个视频提取200个proposals。
问题：对于其中一类行为，GT有41个，prediction有2000个，
首先不是这一类视频中的proposal算FP，接着计算剩余proposals与GT的IoU，按照IoU从高到低排序，IoU小于0.5的算FP，IoU大于0.5的算TP，但如果之后检测到重叠的也算FP。这样算下来我TP最高也就是41，但是FP差不多2000，结果precision算的就会非常低。
想请教下您，不知道这样算有没有问题？

参数设置是论文中的，代码是 https://github.com/activitynet/ActivityNet/blob/master/Evaluation/eval_detection.py
论文：BSN: Boundary Sensitive Network for Temporal Action Proposal Generation

“On THUMOS14, we use top-2 video-level classes generated by UntrimmedNet [48] for proposals generated by BSN and other methods.Following previous works, on THUMOS14, we also implement SCNN-classifier on BSN proposals for proposal-level classification and adopt Greedy NMS as [7]. We use 100 and 200 proposals per video on ActivityNet-1.3 and THUMOS14 datasets separately.”

**Comment by WZMIAOMIAO** [comment]
抱歉，我没有研究过视频行为检测相关内容哦，在不同的任务中计算mAP的方法应该也是不同的，比如在图像目标检测领域对于预测的proposal通常会先经过NMS处理，滤除小概率目标等，这样剩下的目标基本都只有几个或几十个这样的数量级。你说的场景我不了解哦。

**Comment by maodong2056** [comment]
这个也是经过了NMS的，只是剩的确实比较多，我也尝试每个视频生成50/100个proposal这样的，结果更低了，我再研究研究~谢谢回复~
