### ISSUE TITLE
语义分割miou的计算

### ISSUE THREAD

**Issue by ily666666** [WZMIAOMIAO/deep-learning-for-image-processing#431]
1、大佬给的语义分割脚本中似乎是连背景一起算了miou，我觉得是不是应该只算前景部分？
2、大佬的语义分割脚本中，每个epoch都保存了模型，应该保存best比较合理

**Comment by WZMIAOMIAO** [comment]
1. 验证过程中不仅给了所有类别的mean iou，也给了每个类别的iou，你如果只想显示前景的自己重新计算下就行了。
2. 这个best模型的定义方法并不唯一，你可以按照你自己认为的方式去改代码，只保留你自己认为的best model。
