### ISSUE TITLE
关于FCN网络中miou为0的问题

### ISSUE THREAD

**Issue by xurui-111** [WZMIAOMIAO/deep-learning-for-image-processing#433]
up主您好，想请教您一个问题，就是我在用FCN网络做医学肿瘤分割时，输出的结果文档第二类的miou始终为0，具体是下面这个样子:
[epoch: 7]
train_loss: 0.00193
lr: 0.00780
global correct: 99.8
average row correct: ['100.0', '0.0']
IoU: ['99.8', '0.0']
mean IoU: 49.9

我已经做了以下修改:
*未载入resnet50预训练权重
*将初始学习率修改为0.001或0.01

并且我发现train_loss在不断下降，下降的速率不快，想请教一下为什么会这样以及可能的解决方法

**Comment by WZMIAOMIAO** [comment]
1. 载入提供的预训练模型权重。
2. 不要改学习率。

**Comment by xurui-111** [comment]
> 1. 载入提供的预训练模型权重。
> 2. 不要改学习率。

谢谢up回复，试试先

**Comment by xurui-111** [comment]
> 1. 载入提供的预训练模型权重。
> 2. 不要改学习率。

不过up能大概说下原因嘛😃

**Comment by WZMIAOMIAO** [comment]
一般迁移学习的效果要比重头训练效果要好很多。

**Comment by xurui-111** [comment]
> 一般迁移学习的效果要比重头训练效果要好很多。

嗯嗯懂up的意思，但是我这个是灰度图像，听有的小伙伴说预训练权重是用于自然图像，所以才修改了一下

**Comment by WZMIAOMIAO** [comment]
灰度直接复制成三通道就能用预训练权重了。

**Comment by xurui-111** [comment]
> 灰度直接复制成三通道就能用预训练权重了。

啊我突然意识到一个问题，人家VOC的原图像是RGB模式3通道，而我的原图是L模式单通道，会不会是这个原因导致训练不出来东西

**Comment by yinshuisiyuan123** [comment]
老哥，你解决吗了吗？我的数据集是缺陷检测，数据集的标签是单通道（640，360）,像素点是0和1，训练出来的结果IOU也是0，我总共就一个类别。
![image](https://user-images.githubusercontent.com/91045571/177004247-bc886bf4-6a68-44d9-a6ee-c082bdf1ff1d.png)

**Comment by lws111** [comment]
问题该怎么解决呢求回复

**Comment by csuhp201** [comment]
我也是，权重载入了，也没有修改学习率，miou一直为0

**Comment by Zqsmy** [comment]
为什么我的背景值一直为0呀
2024-03-31 15:05:24,222 - mmseg - INFO - Epoch(val) [1][100]    aAcc: 0.2471, mIoU: 0.1235, mAcc: 0.5000, IoU.background: 0.0000, IoU.skin: 0.2471, Acc.background: 0.0000, Acc.skin: 1.0000
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100/100, 3.1 task/s, elapsed: 32s, ETA:     0s2024-03-31 15:05:57,061 - mmseg - INFO - per class results:
2024-03-31 15:05:57,061 - mmseg - INFO -
+------------+-------+-------+
|   Class    |  IoU  |  Acc  |
+------------+-------+-------+
| background |  0.0  |  0.0  |
|    skin    | 24.71 | 100.0 |
+------------+-------+-------+
2024-03-31 15:05:57,062 - mmseg - INFO - Summary:
2024-03-31 15:05:57,062 - mmseg - INFO -
+-------+-------+------+
|  aAcc |  mIoU | mAcc |
+-------+-------+------+
| 24.71 | 12.35 | 50.0 |
+-------+-------+------+
2024-03-31 15:05:57,062 - mmseg - INFO - Epoch(val) [1][100]    aAcc: 0.2471, mIoU: 0.1235, mAcc: 0.5000, IoU.background: 0.0000, IoU.skin: 0.2471, Acc.background: 0.0000, Acc.skin: 1.0000

**Comment by lws222** [comment]
建议你查看你的初始输入值，如果没问题建议改小学习率继续观察





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月31日(星期天) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 关于FCN网络中miou为0的问题 (Issue #433)





 
为什么我的背景值一直为0呀
 2024-03-31 15:05:24,222 - mmseg - INFO - Epoch(val) [1][100]    aAcc: 0.2471, mIoU: 0.1235, mAcc: 0.5000, IoU.background: 0.0000, IoU.skin: 0.2471, Acc.background: 0.0000, Acc.skin: 1.0000
 [&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;] 100/100, 3.1 task/s, elapsed: 32s, ETA:     0s2024-03-31 15:05:57,061 - mmseg - INFO - per class results:
 2024-03-31 15:05:57,061 - mmseg - INFO -
 +------------+-------+-------+
 |   Class    |  IoU  |  Acc  |
 +------------+-------+-------+
 | background |  0.0  |  0.0  |
 |    skin    | 24.71 | 100.0 |
 +------------+-------+-------+
 2024-03-31 15:05:57,062 - mmseg - INFO - Summary:
 2024-03-31 15:05:57,062 - mmseg - INFO -
 +-------+-------+------+
 |  aAcc |  mIoU | mAcc |
 +-------+-------+------+
 | 24.71 | 12.35 | 50.0 |
 +-------+-------+------+
 2024-03-31 15:05:57,062 - mmseg - INFO - Epoch(val) [1][100]    aAcc: 0.2471, mIoU: 0.1235, mAcc: 0.5000, IoU.background: 0.0000, IoU.skin: 0.2471, Acc.background: 0.0000, Acc.skin: 1.0000

**Comment by xubucai** [comment]
失败了
