### ISSUE TITLE
pad_if_smaller对target, image mode = 'P', 报错

### ISSUE THREAD

**Issue by lee910213** [WZMIAOMIAO/deep-learning-for-image-processing#434]
def pad_if_smaller(img, size, fill=0):
    # 如果图像最小边长小于给定size，则用数值fill进行padding
    min_size = min(img.size)
    if min_size < size:
        ow, oh = img.size
        padh = size - oh if oh < size else 0
        padw = size - ow if ow < size else 0
        # img = F.pad(img, (0, 0, padw, padh), fill=fill)
        img.show()
        img = F.pad(img, (0, 0, padw, padh), fill=fill)
        img.show()
        # img = F.pad(img, 【0, 0, padw, padh】, fill=fill)
    return img
这个函数，在处理Image mode = P的调色板target图片时报错，TypeError: an integer is required (got type tuple)
torchvision.transforms.functional.pad()这个函数，没法pad调色板图片？
原图fill = 0, image mode='RGB'时正常
target图，fill = 255， image mode = 'P'时，报错，TypeError

B站视频下提问了，喆哥回答一个即可，万分感谢！

**Comment by lee910213** [comment]
def pad_if_smaller(img, size, fill=0):
    # 如果图像最小边长小于给定size，则用数值fill进行padding
    min_size = min(img.size)
    if min_size < size:
        ow, oh = img.size
        padh = size - oh if oh < size else 0
        padw = size - ow if ow < size else 0
        # img.show()
        if fill == 0:
            img = F.pad(img, (0, 0, padw, padh), fill=fill)
        if fill == 255:
            img = F.pad(img.convert('RGB'), (0, 0, padw, padh), fill=0)
            img = img.convert('P')
        # img.show()
        # img = F.pad(img, [0, 0, padw, padh], fill=fill)
    return img

修改后走通，但是报错如下：
C:\Users\lee\anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [928,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [929,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [930,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [931,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [932,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [933,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [934,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [935,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [936,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [937,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [938,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [939,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [940,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [941,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [942,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [943,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [944,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [945,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [946,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [947,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [948,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [949,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [950,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [951,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [952,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [953,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [954,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [955,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [956,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [957,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [958,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [959,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [960,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [961,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [962,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [963,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [964,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [965,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [966,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [967,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [968,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [969,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [970,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [971,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [972,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [973,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [974,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [975,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [976,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [977,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [978,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [979,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [980,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [981,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [982,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [983,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [984,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [985,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [986,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [987,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [988,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [989,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [990,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [3,0,0], thread: [991,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [978,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [979,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [980,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [981,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [982,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [983,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [984,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [985,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [986,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [987,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [988,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [989,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [990,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [991,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [838,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [839,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [840,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [841,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [842,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [843,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [844,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [845,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [846,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [847,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [848,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [849,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [850,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [851,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [852,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [853,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [854,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [855,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [856,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [857,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [858,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [859,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [860,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [861,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [862,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [863,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [928,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [929,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [930,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [931,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [932,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [933,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [934,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [935,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [936,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [937,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [938,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [939,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [940,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [941,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [942,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [943,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [944,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [945,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [946,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [947,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [948,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [949,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [950,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [951,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [952,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [953,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [954,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [955,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [956,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [957,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [958,0,0] Assertion `t >= 0 && t < n_classes` failed.
C:/cb/pytorch_1000000000000/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:105: block: [1,0,0], thread: [959,0,0] Assertion `t >= 0 && t < n_classes` failed.
Traceback (most recent call last):
  File "D:/PycharmProjects/pythonProject/deep-learning-for-image-processing-master/pytorch_segmentation/deeplab_v3/train.py", line 197, in <module>
    main(args)
  File "D:/PycharmProjects/pythonProject/deep-learning-for-image-processing-master/pytorch_segmentation/deeplab_v3/train.py", line 137, in main
    mean_loss, lr = train_one_epoch(model, optimizer, train_loader, device, epoch,
  File "D:\PycharmProjects\pythonProject\deep-learning-for-image-processing-master\pytorch_segmentation\deeplab_v3\train_utils\train_and_eval.py", line 48, in train_one_epoch
    loss.backward()
  File "C:\Users\lee\anaconda3\envs\pytorch\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\lee\anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

是我的torchvision版本问题么，我用的
torchvision 0.10.0
pytorch 1.9.0
python 3.8.0

**Comment by lee910213** [comment]
pillow                               8.3.1-py38h4fa10fc_0 --> 8.4.0-py38hd45dc43_0
问题解决

**Comment by WZMIAOMIAO** [comment]
请按照requirements.txt配置环境：
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_segmentation/fcn/requirements.txt

**Comment by lee910213** [comment]
pillow                               8.3.1-py38h4fa10fc_0 --> 8.4.0-py38hd45dc43_0
问题解决了，感谢喆哥！
