### ISSUE TITLE
AlexNet compile中loss和metrics的设置

### ISSUE THREAD

**Issue by linfz94** [WZMIAOMIAO/deep-learning-for-image-processing#44]
如果使用ImageDataGenerator生成数据集，那么产生的真实标签是one-hot标码，如果模型的输出层用的是softmax，那么预测值标签是概率分布，loss是categorical_crossentropy，那么metrics也应该是categorical_accurary而不是accuracy吧。

**Comment by WZMIAOMIAO** [comment]
建议你去看下官方的文档，文档中关于categorical_accurary和accuracy方法的输入格式说的很清楚。
