### ISSUE TITLE
coco的标注是中心点和宽高，并不是xmin,ymin,w,h哦

### ISSUE THREAD

**Issue by philiperss** [WZMIAOMIAO/deep-learning-for-image-processing#445]
您好，
deep-learning-for-image-processing/blob/master/pytorch_object_detection/train_coco_dataset/my_dataset.py中第116行，这里有问题吧，coco数据集的标注是x,y,w,h。这里的x,y是bounding box的中心点吧，并不是左上角(xmin, ymin)点。

**Comment by WZMIAOMIAO** [comment]
我不知道你是听谁说的，建议你自己做个实验就知道到底是什么格式了。
有兴趣看下我之前写的博文: [https://blog.csdn.net/qq_37541097/article/details/113247318](https://blog.csdn.net/qq_37541097/article/details/113247318)
