### ISSUE TITLE
 faster rcnn 预测map和训练不一致

### ISSUE THREAD

**Issue by violet2422** [WZMIAOMIAO/deep-learning-for-image-processing#448]
我使用自己数据集进行训练后打印map:0.5为0.755，使用val.py进行测试后发现map:0.5为0.757

**Comment by WZMIAOMIAO** [comment]
将验证的batch_size都设置成1

**Comment by violet2422** [comment]
都是1啊 但是出现的警告
![image](https://user-images.githubusercontent.com/73391269/147757944-6dc45ac5-45e9-44ae-94d7-06ddf6a55a73.png)

**Comment by WZMIAOMIAO** [comment]
你用最新代码试下吧

**Comment by violet2422** [comment]
好吧！我是用的最新的代码，好像我找到规律了，验证map比训练map差不多低0.11%

**Comment by WZMIAOMIAO** [comment]
按理说应该是一样的才对。我之前没有关注过这个问题，如果找到问题原因可以和我说下哈。
