### ISSUE TITLE
FCN train.py文件中params_to_optimize 这个list里面放的几个字典为什么key都是params?训练的参数更新时候怎么区别呢

### ISSUE THREAD

**Issue by xdboost** [WZMIAOMIAO/deep-learning-for-image-processing#451]
![image](https://user-images.githubusercontent.com/34634428/148335753-17a1bdec-a37e-4374-ae5d-dc8a605f9fab.png)

**Comment by WZMIAOMIAO** [comment]
这里就是针对不同的训练参数设置不同的学习率，具体使用方法自己看Pytorch官方文档。

**Comment by xdboost** [comment]
您好，您的来信我已收到，由于我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WZMIAOMIAO** [comment]
https://pytorch.org/docs/stable/optim.html#per-parameter-options

**Comment by xdboost** [comment]
谢谢大神回复！！
