### ISSUE TITLE
IndexError: too many indices for tensor of dimension 1

### ISSUE THREAD

**Issue by jiaerfei** [WZMIAOMIAO/deep-learning-for-image-processing#462]
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/530945542ead8c63bb275b0e6bf85bfcc20f58fb/pytorch_object_detection/ssd/src/utils.py#L599
Up您好，在用ssd跑自己的数据集时，会出现题目所示的错误，报错位置是上面这段代码，请问您知道是什么原因嘛？

**Comment by WZMIAOMIAO** [comment]
没遇到过，大概率是你自己数据的问题

**Comment by jiaerfei** [comment]
> 没遇到过，大概率是你自己数据的问题

好的，谢谢up，我再去检查一下
