### ISSUE TITLE
关于模型初始化的问题

### ISSUE THREAD

**Issue by ioyy900205** [WZMIAOMIAO/deep-learning-for-image-processing#472]
尊敬的老师好，

         ConvNeXt网络中，在构建的时候，有权重初始化的操作。我在网上查询了相关的问题，一般都是解决梯度消失和梯度爆炸的问题。我想知道，这里为什么要进行权重初始化的操作。另外为什么不使用xavier或者kaiming初始化呢？

**Comment by WZMIAOMIAO** [comment]
关于权重初始化的选择，我也不太了解，应该是根据哪篇论文设置的（应该是和VIT相关的论文），你可以自己找找，或者去原项目里提issue。
