### ISSUE TITLE
向Up请教些关于swintransformers的问题

### ISSUE THREAD

**Issue by WandernForte** [WZMIAOMIAO/deep-learning-for-image-processing#474]
请问要怎么用swin来替换ResNet呢？
因为输入输出的类型和维度都有些不一样，不太清楚要怎么灵活变换，希望Up拨冗交流指教。

**Comment by WandernForte** [comment]
![31)WT3D)G64~$JAHD{R7ZGF](https://user-images.githubusercontent.com/81891513/152789104-ad95dd48-4078-475d-92ed-75e90479bfcd.png)
请问在basiclayer前传中出现这样的维度是正常的吗

**Comment by WZMIAOMIAO** [comment]
关于HW问题，自己可以根据`BasicLayer`类的正向传播过程得到，针对自己想要的输出，自己reshape下就行了。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/596afa984d52a20752a82f1bd33093cfde1c868c/pytorch_classification/swin_transformer/model.py#L455-L467
