### ISSUE TITLE
博主好，vision transformer 能不能给一版一运行就能跑的[笑哭]，prediect，train各种配置，配了一下午，不知道你的代码是怎么设置的，原b站视频链接下方一大把同学都评论跑你的代码跑不起来，哪怕写个readme告诉我们怎么一步一步配置也ok呀

### ISSUE THREAD

**Issue by linhuixiao** [WZMIAOMIAO/deep-learning-for-image-processing#479]
博主好，vision transformer 能不能给一版一运行就能跑的[笑哭]，prediect，train各种配置，配了一下午，不知道你的代码是怎么设置的，原b站视频链接下方一大把同学都评论跑你的代码跑不起来。

哪怕写个readme告诉我们怎么一步一步配置也ok呀

**Comment by WZMIAOMIAO** [comment]
我视频里说的很清楚啊，把数据集准备好，把`--data-path`指向数据集根目录，下载好对应模型权重，将`--weights`指向下载好的权重就行了。

**Comment by linhuixiao** [comment]
谢谢博主。不过我们都不是从头开始看视频，博主讲vision transformer视频后面也没有实际运行代码，一笔带过。问题再具体一点，predict.py里面 ./class_indices.json，     img_path = "../tulip.jpg" 怎么配置？flower_photo数据集好像也没有提供 class_indices

**Comment by WZMIAOMIAO** [comment]
`class_indices.json`文件是训练模型时自动生成的，不需要管。预测时`img_path`指向你自己要预测的图片就行了。后续我会在代码中加个readme。
