### ISSUE TITLE
coco数据集简介 ppt的密码有误

### ISSUE THREAD

**Issue by vansin** [WZMIAOMIAO/deep-learning-for-image-processing#488]
coco数据集简介 链接：https://pan.baidu.com/s/1HfCvjt-8o9j5a916IYNVjw[](https://github.com/WZMIAOMIAO/deep-learning-for-imageprocessing/tree/master/course_ppt#%E5%9B%BE%E5%83%8F%E5%88%86%E5%89%B2%E7%BD%91%E7%BB%9C%E7%9B%B8%E5%85%B3) 密码：6rec
图像分割网络相关

**Comment by WZMIAOMIAO** [comment]
没有啊，我访问时正常的。
链接：https://pan.baidu.com/s/1HfCvjt-8o9j5a916IYNVjw 密码：6rec
