### ISSUE TITLE
噼里啪啦大佬，请问下您的这个画出他的聚类散点图怎么画呢？修改了您的代码，能力有限改不了。可以说明一下怎么修改码？发paper要用到

### ISSUE THREAD

**Issue by nit-chick** [WZMIAOMIAO/deep-learning-for-image-processing#490]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by nit-chick** [comment]
噼里啪啦大佬，请问下您的这个画出他的聚类散点图怎么画呢？修改了您的代码，能力有限改不了。可以说明一下怎么修改码？发paper要用到 

![VR8{Z{C3~6(D4$AHQHV BE4](https://user-images.githubusercontent.com/101462914/158020800-b002d5f8-7c6a-4e4b-a1ee-db136cfb9823.png)
>

**Comment by nit-chick** [comment]
这种聚类结果图

**Comment by WZMIAOMIAO** [comment]
我能提供的都已经提供了，改代码的问题自行解决吧。
