### ISSUE TITLE
目标检测faster rcnn数据增强貌似没有？

### ISSUE THREAD

**Issue by wstchhwp** [WZMIAOMIAO/deep-learning-for-image-processing#495]
目标检测faster rcnn数据增强貌似没有？

**Comment by WZMIAOMIAO** [comment]
就用了一个随机水平翻转
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/7b36c76a5f355f6d254211e88354a99f2e1ca02b/pytorch_object_detection/faster_rcnn/train_res50_fpn.py#L48

**Comment by wstchhwp** [comment]
是的，数据增强方式少，感觉效果不太好。

**Comment by WZMIAOMIAO** [comment]
你可以根据自己的需求增加相应的数据增强策略。
