### ISSUE TITLE
继续训练好像少一个epoch

### ISSUE THREAD

**Issue by qingjianbuyi** [WZMIAOMIAO/deep-learning-for-image-processing#499]
pytorch版本中yolov3-spp的train.py中的126行：epochs += ckpt['epoch'] 
是不是应该为：epochs += start_epoch

**Comment by WZMIAOMIAO** [comment]
是的，你说的确实是个问题。如果要在原来的基础上训练更多的epoch，建议还是设置成：`epoch_new = epoch_old + 5`

**Comment by qingjianbuyi** [comment]
好的 谢谢！
