### ISSUE TITLE
预训练权重如何下载呢

### ISSUE THREAD

**Issue by lyj-de-husband** [WZMIAOMIAO/deep-learning-for-image-processing#509]
导 能否出一期如何下载预训练权重的视频呀 您的efficientnetv2的 预训练权重是您自己训练的还是网上找的

**Comment by WZMIAOMIAO** [comment]
自己看下论文呀，论文里都给了项目地址，里面写的清清楚楚每个权重在哪下载：https://github.com/google/automl/tree/master/efficientnetv2

**Comment by lyj-de-husband** [comment]
好的 谢谢导！
