### ISSUE TITLE
IndexError: too many indices for tensor of dimension 0

### ISSUE THREAD

**Issue by jiaerfei** [WZMIAOMIAO/deep-learning-for-image-processing#517]
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/a0e73a739df5c7b1e3a6c1f2b55f8ed24e6a1d90/pytorch_object_detection/ssd/src/utils.py#L500
up你好，在跑ssd模型时，会报“IndexError: too many indices for tensor of dimension 0”这样的错误，指向位置如上，我并没有对代码进行修改，请问您知道这是什么原因吗？是因为没有预测结果吗？但前面有下面这样的判断语句呀
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/a0e73a739df5c7b1e3a6c1f2b55f8ed24e6a1d90/pytorch_object_detection/ssd/src/utils.py#L485

**Comment by WZMIAOMIAO** [comment]
你跑pascal voc数据集有问题吗？如果pascal voc数据集没报错，跑自己的数据集报错了，那就是你自己数据问题。

**Comment by jiaerfei** [comment]
好的，确实是我自己的数据集，我再检查检查，之前就出过类似问题，谢谢up！
