### ISSUE TITLE
类别字典key是int型，不用转成str

### ISSUE THREAD

**Issue by weekstudy** [WZMIAOMIAO/deep-learning-for-image-processing#518]
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/a0e73a739df5c7b1e3a6c1f2b55f8ed24e6a1d90/pytorch_object_detection/faster_rcnn/draw_box_utils.py#L54

**Comment by WZMIAOMIAO** [comment]
最近更新了`draw_box_utils.py`方法，忘记兼容之前的代码了，稍后会进行修改，谢谢提醒。

**Comment by WZMIAOMIAO** [comment]
已经修复了，可以在试一下。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/4323473f91f1ddbfab06be145e9d9b7d75dc1ada/pytorch_object_detection/faster_rcnn/predict.py#L66
