### ISSUE TITLE
predict.py 运行报错 

### ISSUE THREAD

**Issue by punk1** [WZMIAOMIAO/deep-learning-for-image-processing#520]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by punk1** [comment]
，我先运行了  train_mobilenetv2 ,再运行predict 时 ，加载预训练权重 报错 KeyError: 'model'

**Comment by WZMIAOMIAO** [comment]
运行predict文件时怎么会加载预训练权重呢，肯定是要读取你自己训练好得到的权重呀。

**Comment by punk1** [comment]
> 运行predict文件时怎么会加载预训练权重呢，肯定是要读取你自己训练好得到的权重呀。

说错了 就是 训练好的权重  model.load_state_dict(torch.load(train_weights, map_location=device)["model"])然后报错   KeyError: 'model'

**Comment by WZMIAOMIAO** [comment]
那就说明你载入的权重不对，你知道训练保存的权重的位置在哪吗？你载入的权重名称又是什么？

**Comment by punk1** [comment]
> 

![image](https://user-images.githubusercontent.com/38909715/163172048-dc5ff81d-8f8e-44db-9ea2-60540b2d2af3.png)
我加载的权重文件，将文件改为model名称

**Comment by WZMIAOMIAO** [comment]
你要把`weights_path`指向你自己训练好的权重路径，不是`mode`而是`./save_weights/mobile-model-24.pth`

**Comment by punk1** [comment]
> 你要把`weights_path`指向你自己训练好的权重路径，不是`model`而是`./save_weights/mobile-model-24.pth`
> 
> https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/4323473f91f1ddbfab06be145e9d9b7d75dc1ada/pytorch_object_detection/faster_rcnn/predict.py#L55

好了，多谢了
