### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by QianquanChina** [WZMIAOMIAO/deep-learning-for-image-processing#523]
**System information**
* Have I written custom code: 没有
* OS Platform(e.g., window10 or Linux Ubuntu 16.04): ArchLinux 5.17.1
* Python version:3.8.12
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):Pytorch 1.11
* Use GPU or not:是
* CUDA/cuDNN version(if you use GPU):cuda11.3 cudnn8.2.2.0_0
* The network you trained(e.g., Resnet34 network):SwinTransformer

**Describe the current behavior**
model.py 260行 在上下文没有发现self.relative_position_index 只发现了relative_position_index 我看了官方例程也是这样，这是为什么呢？谢谢~
**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
229行，仔细看。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/4323473f91f1ddbfab06be145e9d9b7d75dc1ada/pytorch_classification/swin_transformer/model.py#L229

**Comment by QianquanChina** [comment]
谢谢
