### ISSUE TITLE
There is a error in mask rcnn

### ISSUE THREAD

**Issue by renxuzhiqiuyue** [WZMIAOMIAO/deep-learning-for-image-processing#527]
in train_multi_gpu.py

    # 基于上次的训练结果接着训练
    parser.add_argument('--resume', default='', help='resume from checkpoint')
    parser.add_argument('--aspect-ratio-group-factor', default=3, type=int)
    parser.add_argument('--test-only', action=store_tyre, help="test only")

Maybe:
    parser.add_argument('--test-only', action=**store_true**, help="test only")

**Comment by WZMIAOMIAO** [comment]
> in train_multi_gpu.py
> 
> ```
> # 基于上次的训练结果接着训练
> parser.add_argument('--resume', default='', help='resume from checkpoint')
> parser.add_argument('--aspect-ratio-group-factor', default=3, type=int)
> parser.add_argument('--test-only', action=store_tyre, help="test only")
> ```
> 
> Maybe: parser.add_argument('--test-only', action=**store_true**, help="test only")

Fixed, thanks for feedback
