### ISSUE TITLE
faster rcnn中的nms操作

### ISSUE THREAD

**Issue by 745234332** [WZMIAOMIAO/deep-learning-for-image-processing#53]
rpn_pre_nms_top_n_train=2000, rpn_pre_nms_top_n_test=1000,    # rpn中在nms处理前保留的proposal数(根据score)

                 rpn_post_nms_top_n_train=2000, rpn_post_nms_top_n_test=1000,  # rpn中在nms处理后保留的proposal数
为什么您的代码中nms处理前和处理后的proposal数是一样的呢？这样设置有什么作用吗？

**Comment by WZMIAOMIAO** [comment]
没有什么作用哦，我是看官方代码这么写的，你也可以根据自己的需求进行设置。

**Comment by 745234332** [comment]
好的，谢谢您，一般nms操作后proposal数不是应该减少吗？

**Comment by WZMIAOMIAO** [comment]
一般是的，但这里为什么这么设置我也没看懂。

**Comment by 745234332** [comment]
好的，感谢感谢

**Comment by WZMIAOMIAO** [comment]
更正下我之前说的错误，对于具有FPN的Faster RCNN网络，在NMS之前会在每个特征层上选取前2000个（假设有4个特征层每个特征层都有超过2000个anchor，那么总共会得到8000个），然后再NMS后会在从中再选取其中前2000个。如果是对于没有RPN结构的Faster RCNN那么确实就没什么作用了。
