### ISSUE TITLE
Mask R-CNN如何只做目标检测

### ISSUE THREAD

**Issue by XylonXu01** [WZMIAOMIAO/deep-learning-for-image-processing#535]
请问导师，Mask R-CNN的代码如何使用自己的训练集（在你faster-rcnn的代码上跑通了）只做目标检测，不做图像分割

**Comment by WZMIAOMIAO** [comment]
只做目标检测用faster rcnn就行了，为什么要用mask rcnn，任务不一样，对数据的标注要求也不一样

**Comment by XylonXu01** [comment]
好的，非常感谢

**Comment by huahuabai** [comment]
请问导师，我有如下问题需要向您请教：
1.maskrcnn掩膜怎么画出来的，因为我是做文字的，直接用bbox的检测框会有误差，我想根据掩膜求个最小矩形框
2.训练之后得到的det_results.json这个文件存放的bbox内容是最后的检测框吗？我直接提取bbox坐标出来与gt进行匹配，发现匹配不上啊，那seg_results.json这个文件存放的是什么信息呢
希望收到您的回复！！！非常感谢

**Comment by WZMIAOMIAO** [comment]
> 请问导师，我有如下问题需要向您请教： 1.maskrcnn掩膜怎么画出来的，因为我是做文字的，直接用bbox的检测框会有误差，我想根据掩膜求个最小矩形框 2.训练之后得到的det_results.json这个文件存放的bbox内容是最后的检测框吗？我直接提取bbox坐标出来与gt进行匹配，发现匹配不上啊，那seg_results.json这个文件存放的是什么信息呢 希望收到您的回复！！！非常感谢

1. 绘制相关代码`draw_box_utils.py`里面写的清楚，自己看下。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_object_detection/mask_rcnn/draw_box_utils.py

2. 是最后的检测的结果，匹配不上是因为你对存储数据的格式不了解。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/87a31d3db4baa5a693c59cab66cb232357c326c9/pytorch_object_detection/mask_rcnn/train_utils/coco_eval.py#L50-L86
