### ISSUE TITLE
AssertionError:./VOCdevkit\VOC2007/Annotations2860.xml lack of object information.

### ISSUE THREAD

**Issue by huawang400** [WZMIAOMIAO/deep-learning-for-image-processing#541]
hello :
 Thanks for you share ,It's very good code ,I have a problem ,hope you can give me a solution ,thank you very much!

CODE Dir :
./pytorch_object_detection/faster_rcnn/train_res50_fpn.py

ERROR:
 File "D:\rsrc\deep-learning-for-image-processing-master\pytorch_object_detection\faster_rcnn\my_dataset.py", line 75, in __getitem__
    assert "object" in data, "{} lack of object information.".format(xml_path)
AssertionError: ./VOCdevkit\VOC2007\Annotations\SXwindpower20220413_V1_train_2860.xml lack of object information.

because I  have much background pics ,so when I don't  perform you code ,I have try modify it ,but it's have a new problem ,I have spend more time ,Hope you can give a suggestion ,Thanks!!

**Comment by EM7097** [comment]
Hi,
Great instruction and thanks for share it helps a lot! 

But I get a question about this network. As for the VOC dataset, I tried to use pretrained weights and train_mobile_net.py to train the network. 
What I want to ask is that if I use my own dataset which has 5 classes less than 21 of the VOC, could I use the same pre_trained weight? Or I need to retrain the whole network?
