### ISSUE TITLE
Question about the train part 

### ISSUE THREAD

**Issue by EM7097** [WZMIAOMIAO/deep-learning-for-image-processing#543]
Hi,
Great instruction and thanks for share it helps a lot!

But I get a question about this network. As for the VOC dataset, I tried to use pretrained weights and train_mobile_net.py to train the network.
What I want to ask is that if I use my own dataset which has 5 classes less than 21 of the VOC, could I use the same pre_trained weight? Or do I need to retrain the whole network?

**Comment by EM7097** [comment]
I though I can just use the weight but I am not quite sure about it

**Comment by WZMIAOMIAO** [comment]
> Hi, Great instruction and thanks for share it helps a lot!
> 
> But I get a question about this network. As for the VOC dataset, I tried to use pretrained weights and train_mobile_net.py to train the network. What I want to ask is that if I use my own dataset which has 5 classes less than 21 of the VOC, could I use the same pre_trained weight? Or do I need to retrain the whole network?

you can use backbones pre-trained weights.
