### ISSUE TITLE
Batch size of the validation/test set for Faster RCNN

### ISSUE THREAD

**Issue by lfangyu09** [WZMIAOMIAO/deep-learning-for-image-processing#544]
Hi, 

Thanks a lot for your very helpful code. I have a question about the batch size of the validation/test set for Faster RCNN. When I evaluate the validation/test set for Faster RCNN, I got the mAP of 0 if the batch size of the validation/test set was higher than 1. If the batch size was changed to 1, the mAP would be higher than 0. Why does the batch size of the validation/test set for Faster RCNN need to be set as 1? Thanks a lot.

**Comment by WZMIAOMIAO** [comment]
If batch_size is not 1, edge of some images will be pad 0 for same input size. This will make small changes to the mAP.
refer batch_images function:
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/74386042f675de59228be42ff420dc85ec15dc7b/pytorch_object_detection/faster_rcnn/network_files/transform.py#L156-L166
