### ISSUE TITLE
有人报这个错吗 怎么解决呀 网上查了好久都没有 RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8

### ISSUE THREAD

**Issue by wys2929** [WZMIAOMIAO/deep-learning-for-image-processing#545]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
应该是你的GPU环境有问题，检查下Pytorch版本+CUDA版本+GPU Driver版本是否对应以及正确。

**Comment by wys2929** [comment]
非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月30日(星期六) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 有人报这个错吗 怎么解决呀 网上查了好久都没有 RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8 (Issue #545)





 
应该是你的GPU环境有问题，检查下Pytorch版本+CUDA版本+GPU Driver版本是否对应以及正确。

**Comment by littlerookie6990** [comment]
解决了吗？

**Comment by wys2929** [comment]
唔&nbsp;我用的是学校的超算&nbsp;但我没有权限访问学校超算的CUDA版本等信息的权利 也无法更改&nbsp;所以在我这里可能暂时无解辽




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月3日(星期二) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 有人报这个错吗 怎么解决呀 网上查了好久都没有 RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:518, unhandled system error, NCCL version 2.4.8 (Issue #545)





 
解决了吗？
