### ISSUE TITLE
Up大大，运行predict时导入模型出现错误

### ISSUE THREAD

**Issue by superYeah123** [WZMIAOMIAO/deep-learning-for-image-processing#549]
up大大您好，我使用了您的Faster R-CNN代码，我使用规范的VOC数据集保存的方式组织了自己的文件夹，同时运行train_res50_fpn.py这个脚本成功生成了15个epoch的权重文件（已正确指定检测的类别数），但是在使用predict.py预测脚本时，在导入自己的模型这一步出现了问题，我查询了很多资料也没能解决该问题，所以通过这种方式打扰您
![image](https://user-images.githubusercontent.com/105659230/168627374-218697dd-5c21-4735-a7f3-d132ed103659.png)
![image](https://user-images.githubusercontent.com/105659230/168627379-9105fc83-0d94-4daa-843a-15adc0a9b2e8.png)

**Comment by YunWaiHe** [comment]
你好，请问这个问题怎么解决呢？
