### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by xdd12135** [WZMIAOMIAO/deep-learning-for-image-processing#553]
target_category = np.argmax(output.cpu().data.numpy(), axis=-1)

加载的是自己的模型，类别数设置的None
在这一句报错，能问一下是为什么吗

**Comment by WZMIAOMIAO** [comment]
请按照问题模板提问。

**Comment by chengjorange** [comment]
请问解决了吗，我也遇到同样的问题

**Comment by learning-art** [comment]
您给我发的信息已收到！ 我会及时回复信息！

祝您健康、快乐！

哈尔滨工业大学

**Comment by xdd12135** [comment]
已经毕业一年啦，这件事我都忘掉了，建议你换个其他的试试。
&nbsp;


冬凌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月21日(星期三) 上午10:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] AttributeError: &#39;dict&#39; object has no attribute &#39;cpu&#39; (Issue #553)





 
请问解决了吗，我也遇到同样的问题
