### ISSUE TITLE
retinaNet num_classes

### ISSUE THREAD

**Issue by yufangbo** [WZMIAOMIAO/deep-learning-for-image-processing#558]
我用博主的retinaNet代码训练自己的数据，设置num_classes不包含背景类会报错，然后去pytorch官方看官方实现的代码是包含背景类的

**Comment by WZMIAOMIAO** [comment]
包不包含没有什么影响，我个人觉得没必要包含。

**Comment by yufangbo** [comment]
> 包不包含没有什么影响，我个人觉得没必要包含。但两者对应的json文件是有区别的，如果不包含，类别索引是从0开始，如果包含，类别索引是从1开始（0留给背景）。

懂了 导师
