### ISSUE TITLE
train_multi_gpu_using_launch.py 中，如果weights_path为True，会导致checkpoint_path未定义，而导致删除错误。

### ISSUE THREAD

**Issue by balala8** [WZMIAOMIAO/deep-learning-for-image-processing#563]
train_multi_gpu_using_launch.py 中，如果weights_path为True，会导致checkpoint_path未定义，而导致删除错误。

**Comment by WZMIAOMIAO** [comment]
weights_path是str类型代表加载的权重路径，你设置成True干嘛？

**Comment by balala8** [comment]
> weights_path是str类型代表加载的权重路径，你设置成True干嘛？

说错了。就大概是这个意思。如果有这个参数，那么就不会初始化checkpoint_path。在训练结束的时候就会导致删除临时文件时checkpoint_path不存在。

**Comment by WZMIAOMIAO** [comment]
已修复
