### ISSUE TITLE
大佬，请问Mask RCNN中的数据集是怎么处理的啊？或者说我在labelme标注好的数据集怎么在您的代码中运行啊

### ISSUE THREAD

**Issue by Haoyue-code** [WZMIAOMIAO/deep-learning-for-image-processing#565]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
转成coco数据格式，仿照coco数据集训练就行了。
