### ISSUE TITLE
图片找不到

### ISSUE THREAD

**Issue by opencvlearn** [WZMIAOMIAO/deep-learning-for-image-processing#566]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):windows10
* Python version:3.9
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):pytorch1.10
* Use GPU or not:gpu
* CUDA/cuDNN version(if you use GPU):cuda10.2
* The network you trained(e.g., Resnet34 network):Faster rcnn

**Describe the current behavior*
使用东北大学带钢数据集，voc中图片文件读取不了，显示以下内容感觉都没有错误不知道为啥就读取不了

**Error info / logs**
![Screenshot 2022-06-01 185633](https://user-images.githubusercontent.com/98160737/171388992-5e17993e-483b-4fa6-a2f3-e231d2e171bd.jpg)
![Screenshot 2022-06-01 185756](https://user-images.githubusercontent.com/98160737/171389205-68943370-ca81-4925-ac6e-92d9fe28f60f.jpg)

**Comment by WZMIAOMIAO** [comment]
parches_203对应xml的filename有问题，根据报错信息说明filename没有`.jpg`文件后缀。总而言之，你的数据标注文件不是严格按照pascal voc数据集来的。

**Comment by opencvlearn** [comment]
感谢你的回复，我用的是东北大学带钢数据集，他是直接标注好的xml文件，他的filename就是完全的带有jpg格式的文件名，我感觉你的方法并没有错，但是不知为何就是识别不出来，我在网上借鉴一下别人的读取改成了&nbsp;data["filename"].split(".")[0] + ".jpg"这个样子就解决了问题，但是今天我训练完成我的模型后，然后打开预测文件结果报错
Traceback (most recent call last):
&nbsp; File "D:\pycharm\PyCharm Community Edition 2021.3.1\plugins\python-ce\helpers\pydev\pydevd.py", line 1483, in _exec
&nbsp; &nbsp; pydev_imports.execfile(file, globals, locals)&nbsp; # execute the script
&nbsp; File "D:\pycharm\PyCharm Community Edition 2021.3.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
&nbsp; &nbsp; exec(compile(contents+"\n", file, 'exec'), glob, loc)
&nbsp; File "D:/pycharm/pycharmwenjian/Faster_R-CNN/faster_rcnn_20220523/predict.py", line 112, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "D:/pycharm/pycharmwenjian/Faster_R-CNN/faster_rcnn_20220523/predict.py", line 57, in main
&nbsp; &nbsp; model.load_state_dict(torch.load(weights_path, map_location='cpu')["model"])
&nbsp; File "D:\anaconda\envs\pytorch1.10.1+cuda10.2\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
&nbsp; &nbsp; raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

RuntimeError: Error(s) in loading state_dict for FasterRCNN:
	size mismatch for roi_heads.box_predictor.cls_score.weight: copying a param with shape torch.Size([7, 1024]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
	size mismatch for roi_heads.box_predictor.cls_score.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([21]).
	size mismatch for roi_heads.box_predictor.bbox_pred.weight: copying a param with shape torch.Size([28, 1024]) from checkpoint, the shape in current model is torch.Size([84, 1024]).
	size mismatch for roi_heads.box_predictor.bbox_pred.bias: copying a param with shape torch.Size([28]) from checkpoint, the shape in current model is torch.Size([84]).
python-BaseException

好像是格式问题，我也不知道问题出在哪里了，辛苦老哥看看能否有什么建议！
非常感谢up主的分享，（真导师）哈哈哈！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月2日(星期四) 上午8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 图片找不到 (Issue #566)





 
parches_203对应xml的filename有问题，根据报错信息说明filename没有.jpg文件后缀。总而言之，你的数据标注文件不是严格按照pascal voc数据集来的。

**Comment by WZMIAOMIAO** [comment]
我不是说所有的xml文件filename都有问题，是有的xml文件有问题，就比如说你报错的那个xml文件`parches_203`， 你自己看看就知道了。
