### ISSUE TITLE
建议将课程ppt放到语雀上

### ISSUE THREAD

**Issue by wwdok** [WZMIAOMIAO/deep-learning-for-image-processing#567]
谢谢作者的分享，我建议将课程ppt放到语雀上，省去了用户输入密码的步骤，而且还可以把所有pdf整合到一起，通过大纲快速切换，效果如下：
![image](https://user-images.githubusercontent.com/43233772/171994971-62660758-e817-4dbb-9eab-dd58d7e0b00e.png)

**Comment by WZMIAOMIAO** [comment]
谢谢你的提议，暂时不考虑哈。
