### ISSUE TITLE
非极大值抑制问题

### ISSUE THREAD

**Issue by flyzxm5177** [WZMIAOMIAO/deep-learning-for-image-processing#568]
作者您好！在跑fasterRCNN和SSD源码过程中，发现生成结果有很多重叠的框，如下图，而输出却表示有NMS，应该是没经过这一步吧
![1738](https://user-images.githubusercontent.com/36351639/172158058-2f1490af-6d0d-43ac-9b97-21a42169f28a.jpg)
![image](https://user-images.githubusercontent.com/36351639/172158393-03983eb6-5c54-4344-b8d0-891b9bf68eb0.png)

**Comment by WZMIAOMIAO** [comment]
有的，视频里都有讲，代码里也有自己仔细看。

https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/75514a3995d02508331769311377f11b4fdab31f/pytorch_object_detection/faster_rcnn/network_files/roi_head.py#L334-L336

https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/75514a3995d02508331769311377f11b4fdab31f/pytorch_object_detection/ssd/src/utils.py#L605-L606
