### ISSUE TITLE
问导师两个简单的问题哈，希望对其他人也有些帮助

### ISSUE THREAD

**Issue by LKssssZz** [WZMIAOMIAO/deep-learning-for-image-processing#569]
1. 首先就是训练的时候，loss后面 （） 里面的数值和前面的是不同的，所以（）里面代表的是什么呢？一直有这个疑惑
Epoch: [60]  [100/213]  eta: 0:00:45.299039  lr: 0.000000  loss: 0.0776 (0.0802)  bbox_regression: 0.0660 (0.0670)  classification: 0.0116 (0.0132)  time: 0.3978  data: 0.0067  max mem: 7906

2. 假设单卡的学习率是0.01(batch_size=8)，为什么多卡的学习率要根据卡数进行调整呢？比如我4张卡(每张卡batch_size=8)，是不是就设为0.04？  这个原则的文章原理和出处是哪里呢？没有搜索到相关文章内容。

麻烦导师一起回答下，感谢

**Comment by WZMIAOMIAO** [comment]
1.  `loss: 0.0776 (0.0802) ` 其中`0.0776`是当前step的损失，`0.0802`是训练当前epoch的平均损失
2. 一般根据batch_size倍增即可，文章可参考：《Accurate, large minibatch SGD: training imagenet in 1 hour》

**Comment by LKssssZz** [comment]
> 1. `loss: 0.0776 (0.0802) ` 其中`0.0776`是当前step的损失，`0.0802`是训练当前epoch的平均损失
> 2. 一般根据batch_size倍增即可，文章可参考：《Accurate, large minibatch SGD: training imagenet in 1 hour》

感谢回答
