### ISSUE TITLE
关于MobileNetV3的训练问题

### ISSUE THREAD

**Issue by myfeet2cold** [WZMIAOMIAO/deep-learning-for-image-processing#572]
您好，我在使用MobileNetV3进行自定义数据集训练时，调用
`net = MobileNetV3(num_classes=16)`
时报错如下：

> TypeError: __init__() missing 2 required positional arguments: 'inverted_residual_setting' and 'last_channel'

请问如何解决？感谢。

**Comment by WZMIAOMIAO** [comment]
mobilenetv3不是这么导入的，我视频里都有讲，仔细看下：
```python
from model_v3 import mobilenet_v3_small, mobilenet_v3_large
model = mobilenet_v3_large(num_classes=16)
```
