### ISSUE TITLE
数据集存放位置

### ISSUE THREAD

**Issue by 20000131** [WZMIAOMIAO/deep-learning-for-image-processing#580]
博主您好！第一次看您的视频，使用Pytorch版的Msak R-CNN，下载并解压了VOC2012数据集。请问是要新建文件夹data，将解压的数据集直接放到data文件夹中，然后修改成default='/data/VOCdevkit'就可以了吗？我这么做报错：找不到文件'/data/VOCdevkit'，问题有点蠢...但还是麻烦您抽空解答一下，谢谢！

**Comment by WZMIAOMIAO** [comment]
`/data/`是`linux`操作系统的路径，你随便解压在哪，只要把路径的`default`指向你解压后的`VOCdevkit`路径就行了。如果还不了解就自己网上搜下路径相关知识。
