### ISSUE TITLE
split_data.py语句缺失

### ISSUE THREAD

**Issue by Sirwenhao** [WZMIAOMIAO/deep-learning-for-image-processing#583]
**split_data.py**
* 问题：脚本语句缺失
* 具体：验证集划分部分(line39)缺失一行代码，如下：
* mk_file(os.path.join(val_root, cla))

烦请UP查阅验证

**Comment by WZMIAOMIAO** [comment]
我没看懂您说的问题，我看了下代码好像也没有问题。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/75f81bff3f2ca53866ece59042ad0a473f2fb930/data_set/split_data.py#L36-L41
