### ISSUE TITLE
关于mask rcnn训练coco数据集

### ISSUE THREAD

**Issue by yjcreation** [WZMIAOMIAO/deep-learning-for-image-processing#587]
![image](https://user-images.githubusercontent.com/22938656/177148216-4eefe182-04c8-405c-a5c9-6026e8c7a532.png)
up，请问使用coco数据集训练出现这个问题，查了好久不知道怎么解决？
使用在网上找到的minicoco的数据集

**Comment by WZMIAOMIAO** [comment]
这个我也不清楚，没听说过minicoco

**Comment by yjcreation** [comment]
好的，谢谢up。minicoco就是从coco数据集划分出来的小型coco数据集，就是在训练过程中evaluate的时候出现的问题

**Comment by WZMIAOMIAO** [comment]
建议还是在标准coco数据集上跑吧，其他非官方的数据集可能标注信息格式不规范或者其他问题。
