### ISSUE TITLE
efficientnetv2模型参数

### ISSUE THREAD

**Issue by Llululu** [WZMIAOMIAO/deep-learning-for-image-processing#588]
请问，如果只要特征提取层，是不是从head开始后面的参数都要删去呢？
![image](https://user-images.githubusercontent.com/54887611/177236957-01b98fa7-35ef-4d71-b868-fa30b15154b2.png)

**Comment by WZMIAOMIAO** [comment]
提取特征层不需要删改任何东西

**Comment by Llululu** [comment]
如果是做分割任务不需要全连接层呢

**Comment by WZMIAOMIAO** [comment]
自己设计网络看需要哪些就保留哪些，其他的的都可以删掉。
