### ISSUE TITLE
.npz to .h5

### ISSUE THREAD

**Issue by DingDinmao** [WZMIAOMIAO/deep-learning-for-image-processing#589]
请问，在图像分类的vision_transformer模型中，您是如何把原 .npz 文件转成 .h5文件的呢？

**Comment by WZMIAOMIAO** [comment]
参考：https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/tensorflow_classification/vision_transformer/trans_weights.py

**Comment by DingDinmao** [comment]
谢谢 谢谢
