### ISSUE TITLE
老师您好，Faster-RCNN自己标注的数据训练时出现 Loss is nan, stopping training

### ISSUE THREAD

**Issue by franklinbill** [WZMIAOMIAO/deep-learning-for-image-processing#59]
老师您好！我看了您的视频感觉讲的非常好，我这边使用您的代码在VOC2012数据集上可以正常运行，但是我使用我自己标注的数据集就出现了这个问题：Loss is nan, stopping training。我不太确定这个问题产生的原因，想来咨询您一下。我使用的是Windows，1块2060的CPU、用的是res50_fpn。
![image](https://user-images.githubusercontent.com/18572115/95061896-ccc0a780-072e-11eb-867a-02c4cdeba5a7.png)

**Comment by WZMIAOMIAO** [comment]
你检查下数据的标注格式是否与pascal voc数据集一致

**Comment by franklinbill** [comment]
老师您好！我检查了一下，是一样的。我用您的my_dataset.p也可以正常运行没有问题

**Comment by WZMIAOMIAO** [comment]
你尝试把batch_size设置成1，然后把训练集的dataloader的shuffle设置为False，在my_dataset.py文件中每次读取一张图片print一下文件的名称，定位到是哪张训练图像对应的标注文件出现的问题，我在帮你排查。

**Comment by franklinbill** [comment]
非常感谢老师，我找到问题了，是由张图片的标注出现了问题，改之后就解决了，非常感谢！
