### ISSUE TITLE
Faster RCNN 使用 torch.nn.DataParallel的问题

### ISSUE THREAD

**Issue by wha-cloud** [WZMIAOMIAO/deep-learning-for-image-processing#591]
当我想给模型加上torch.nn.DataParallel，以便于可以使用更大batchsize，当时当这样做后，图片传入模型后通道数变为了2。也就是说，上一步图像还是正常的3通道，只是经历了loss = model（images，target）这一步，进入forward，图片就变成了2通道。您知道是为什么吗？

**Comment by WZMIAOMIAO** [comment]
如果是DDP，batchsize是每块GPU输入的图片数量，关于DP我没用过，建议还是自己去看官方文档吧。
