### ISSUE TITLE
我想问tensorflow-gpu版本你们用哪个版本能成功train起来呢

### ISSUE THREAD

**Issue by STU-ECHO** [WZMIAOMIAO/deep-learning-for-image-processing#592]
我想问tensorflow-gpu版本你们用哪个版本能成功train起来呢，因为有的时候报错可能只是因为环境配置问题，可不可以出一个issues，里面大家列出能成功运行的对于某个任务关键的配置环境信息呢

**Comment by STU-ECHO** [comment]
> 我想问tensorflow-gpu版本你们用哪个版本能成功train起来呢，因为有的时候报错可能只是因为环境配置问题，可不可以出一个issues，里面大家列出能成功运行的对于某个任务关键的配置环境信息呢

我想完成swin-trasformer,基于tensorflow版的，因为我的cuda自动更新到很新的版本，目前我的tensorflow-gpu=2.9.1,而且只有这时候我才能够cuda available,

**Comment by WZMIAOMIAO** [comment]
tf2.4

**Comment by STU-ECHO** [comment]
谢谢您的回复，但是我用tf2.4依旧发生错误，附件是我的环境配置，错误提示，还有运行目录


如果是发生了很愚蠢很浅显的错误很抱歉耽搁您的时间但也请为我指明哪里有问题
谢谢您的阅读
祝今天愉快
















在 2022-07-09 13:20:41，"WuZhe" ***@***.***> 写道：

Closed #592 as completed.

**Comment by WZMIAOMIAO** [comment]
没有看到附件，你可以先安装CPU版本看能不能正常跑，如果能的话，就说明你GPU环境配置有问题。
