### ISSUE TITLE
Faster RCNN 源码理解：train_sampler

### ISSUE THREAD

**Issue by guyueyanfeng** [WZMIAOMIAO/deep-learning-for-image-processing#593]
先感谢作者的源码讲解和源码实现。以下是我的疑问。

`    if aspect_ratio_group_factor >= 0:
        train_sampler = torch.utils.data.RandomSampler(train_dataset)
        # 统计所有图像高宽比例在bins区间中的位置索引
        group_ids = create_aspect_ratio_groups(train_dataset, k=aspect_ratio_group_factor)
        # 每个batch图片从同一高宽比例区间中取
        train_batch_sampler = GroupedBatchSampler(train_sampler, group_ids, batch_size)`

在train_mobilenetv2.py，行71~78行提出了这样一个将训练集按宽高比分割的方法。我对这个操作有点疑惑。
①这样分割注释中说是这样做的原因是为了减少训练中的显存使用。我的理解是：将相似宽高比的图片进行分割，可以避免大宽高比图片和小宽高比图片在同一个batch，使得统一宽高比时，整体的平均宽高比比较高进而增加显存。
②将宽高比进行排列然后打包成batch是可以降低显存，但是为何要划分成8个bins，然后统计在间隔内的图片数量呢？不应该是排列好之后，直接按batch_size打包图片进行宽高比统一吗？

**Comment by WZMIAOMIAO** [comment]
这里是参考的Pytorch官方的代码，有什么问题建议去官方仓库提issue提问。
https://github.com/pytorch/vision/blob/e75a333782bb5d5ffdf5355e766eb5937fc6697c/references/detection/train.py#L191-L195

**Comment by guyueyanfeng** [comment]
好的，谢谢。
