### ISSUE TITLE
Faster RCNN中添加validation loss的问题

### ISSUE THREAD

**Issue by chenyuuu0705** [WZMIAOMIAO/deep-learning-for-image-processing#597]
请问，我如果想在faster rcnn 中添加训练过程中 validation的loss的话，像图中这样的写法是正确的吗？
![image](https://user-images.githubusercontent.com/80811609/179720736-e37f70de-f966-439a-8f06-5ab93d511606.png)

**Comment by WZMIAOMIAO** [comment]
不行，这样做验证集也会参与训练

**Comment by chenyuuu0705** [comment]
@WZMIAOMIAO 
你好，我在vgg的代码中想要计算train accuracy,然后进行了修改，如图所示，请问这样可以吗？
![image](https://user-images.githubusercontent.com/80811609/179902717-ea382ab8-0fa2-422c-9c2b-866c9c06475b.png)

**Comment by WZMIAOMIAO** [comment]
你直接参考我提供的项目代码改吧。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/309520fb600b24eafebed3834fcee52ef1ba4e6e/pytorch_classification/Test11_efficientnetV2/train.py#L106-L109

**Comment by chenyuuu0705** [comment]
@WZMIAOMIAO 
非常感谢 ：）
