### ISSUE TITLE
环境配置问题

### ISSUE THREAD

**Issue by asapple** [WZMIAOMIAO/deep-learning-for-image-processing#599]
**System information**
* Have I written custom code: pip install -r .\requirements.txt
* OS Platform(e.g., window10 or Linux Ubuntu 16.04): window10
* Python version: Python 3.7.13
**Describe the current behavior**
Wz学长，您好！
我在配置yolov3spp的环境过程中，运行pip install -r .\requirements.txt，问题显示：无法找到版本为0.8.2的torchvision。请问我该如何解决这个问题？
**Error info / logs**
ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.0rc1 Requires-Python >=3.8; 1.22.0rc2 Requires-Python >=3.8; 1.22.0rc3 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.2 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0)
ERROR: No matching distribution found for torchvision==0.8.2

**Comment by asapple** [comment]
我通过运行pip install -r .\requirements.txt -f https://download.pytorch.org/whl/torch_stable.html解决了这个问题。参考的是https://stackoverflow.com/questions/60137572/issues-installing-pytorch-1-4-no-matching-distribution-found-for-torch-1-4

**Comment by WZMIAOMIAO** [comment]
安装pytorch以及torchvision时需要指定安装源，详情参考我之前写的博文：https://blog.csdn.net/qq_37541097/article/details/120951214

**Comment by bAi-dUe** [comment]
你好，我想用激活图CAM来激活多标签，使用训练好的模型，这里想要激活的target是指我模型里面的类别吗？应该不是imagnet 1k了吧。对于CV图像如voc这种，选择不同的target激活区域看到是不一样，但是遥感图像感觉都是一样的，而且是全部激活，您能帮我解惑吗

**Comment by WZMIAOMIAO** [comment]
> 你好，我想用激活图CAM来激活多标签，使用训练好的模型，这里想要激活的target是指我模型里面的类别吗？应该不是imagnet 1k了吧。对于CV图像如voc这种，选择不同的target激活区域看到是不一样，但是遥感图像感觉都是一样的，而且是全部激活，您能帮我解惑吗

target是你自己训练模型中感兴趣的类别，和imagnet 1k无关，我在视频里提到imagenet 1k的标签文件是因为视频里演示的模型载入的权重是在imagenet 1k上训练的。如果有其他问题请单独提issue，不要在别人的问题下提，谢谢。
