### ISSUE TITLE
类激活图使用

### ISSUE THREAD

**Issue by bAi-dUe** [WZMIAOMIAO/deep-learning-for-image-processing#600]
你好，我想用激活图CAM来激活多标签，使用训练好的模型，这里想要激活的target是指我模型里面的类别吗？应该不是imagnet 1k了吧。对于CV图像如voc这种，选择不同的target激活区域看到是不一样，但是遥感图像感觉都是一样的，而且是全部激活，您能帮我解惑吗，下面是遥感的一张图（训练模型所用数据集里的）和两个不同的target
![image](https://user-images.githubusercontent.com/49230907/180601667-4ddb7103-ab21-4d8b-a1a3-3d410ee4acdd.png)
![image](https://user-images.githubusercontent.com/49230907/180601673-70cd4a79-47da-4e85-9cce-f0114712a5d8.png)
![image](https://user-images.githubusercontent.com/49230907/180601677-c3bd4495-8c36-4eaf-9799-c53a54288cc1.png)

**Comment by WZMIAOMIAO** [comment]
target是你自己训练模型中感兴趣的类别，和imagnet 1k无关，我在视频里提到imagenet 1k的标签文件是因为视频里演示的模型载入的权重是在imagenet 1k上训练的。并且我提供的代码仅针对图像分类任务，如果是其他任务，如分割、检测等请参考原项目文档：https://github.com/jacobgil/pytorch-grad-cam。
