### ISSUE TITLE
Vision Transformer image_size 以及 patch_size修改问题

### ISSUE THREAD

**Issue by Liqq1** [WZMIAOMIAO/deep-learning-for-image-processing#601]
您好！
1.请问在ViT中，加上def resize_pos_embed(posemb, posemb_new) ，对pos embedding进行插值后，就可以改变image_size 和patch_size了吗？（仍使用作者原来提供的权重文件）。

2.在Patch Embedding 中的2dConv,在训练时权重更新了吗？ 好像不需要对这个卷积进行训练，如果这个卷积的权重不在权重文件里的话，感觉应该可以修改patch_size大小了？

**Comment by WZMIAOMIAO** [comment]
> 您好！ 1.请问在ViT中，加上def resize_pos_embed(posemb, posemb_new) ，对pos embedding进行插值后，就可以改变image_size 和patch_size了吗？（仍使用作者原来提供的权重文件）。
> 
> 2.在Patch Embedding 中的2dConv,在训练时权重更新了吗？ 好像不需要对这个卷积进行训练，如果这个卷积的权重不在权重文件里的话，感觉应该可以修改patch_size大小了？

1.可以，但改变输入图片尺寸后一般会对精度产生一定影响。
2.训练。

**Comment by Liqq1** [comment]
了解，谢谢
