### ISSUE TITLE
Faster RCNN显存，内存要求是否过高，bs大小设多少，环境是32G内存，48GB显存

### ISSUE THREAD

**Issue by diplomatist** [WZMIAOMIAO/deep-learning-for-image-processing#604]
CPU：32核64线   GPU：双3090
sys：Ubuntu 18.04
Python version: 3.6
Deep learning framework and version:pytorch1.10
The network you trained(e.g., Resnet34 network): resnet50

![image](https://user-images.githubusercontent.com/74148589/180920459-76283ba7-9b66-40e1-8505-4d11d5a02cf6.png)

线程worker设置为0，进程world-size也设置为0，bs为8，此时内存占了17G，显存双卡显存状态如下图：
![image](https://user-images.githubusercontent.com/74148589/180920724-fd6a9338-df5a-4dbb-9ebf-090d51dd78c2.png)

如果按照worker设置为8，world-size设置为4，bs设置为32，内存不够，因此我在此基础上加了32GB的swap虚拟内存，但还是不够，再将swap修改成64GB，但显存爆了。

于是我将bs设置为16，但显存还是爆了，我只能设置为8才能运行。

我的问题是，该模型是需要这么高的硬件要求吗？模型输入是否是固定的600x600？我是否需要resize我的数据集

**Comment by WZMIAOMIAO** [comment]
word_size会根据GPU数量自己设置的，不需要你去设置。建议bs设置成8就行了，如果想设置更大bs建议把amp开启。训练时主要占用GPU显存，和你说的swap无关。修改输入图片尺寸是在`FasterRCNN`类中初始化函数中设置的，和你对不对图片进行resize无关，我在视频里都讲的很清楚，麻烦仔细看下视频。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/309520fb600b24eafebed3834fcee52ef1ba4e6e/pytorch_object_detection/faster_rcnn/network_files/faster_rcnn_framework.py#L247-L249

**Comment by diplomatist** [comment]
@WZMIAOMIAO 谢谢导师的耐心答复，现在以bs=8去运行了。
