### ISSUE TITLE
关于validation.py中的验证集以及Map

### ISSUE THREAD

**Issue by wujihua628** [WZMIAOMIAO/deep-learning-for-image-processing#607]
你好，感谢您提供这么好的资源让我们学习。现在我有一个问题：在faster rcnn -- validation.py（图1）文件中，用到的是验证集，那么得到的应该是验证集的Map，现在我想得到**测试集**的Map，即得到论文中用来评价模型好坏的Map（图2），是不是要把validation.py中用的验证集换成测试集呢（图3）？    或者我该如何得到测试集的Map呢？

万分盼望您的回复，感谢！

![image](https://user-images.githubusercontent.com/90367095/181215100-eee2f641-fc7a-446e-a89a-a911ac199756.png)

![image](https://user-images.githubusercontent.com/90367095/181217055-15571b09-eec5-4a40-88a2-13c8b0674fcd.png)

![image](https://user-images.githubusercontent.com/90367095/181217225-65ea97b3-28af-458b-aafb-0dac2b593fb7.png)

**Comment by WZMIAOMIAO** [comment]
如果你有测试集的数据和GT可以将validation.py中用的验证集换成测试集就行了。如果是像Pascal VOC或者MS COCO官方数据集，需要自己把预测结果提交到官网进行评估，具体方法自己看对应官网。

**Comment by wujihua628** [comment]
嗯嗯，我用的是自己的数据，感谢您的回复，祝好~
