### ISSUE TITLE
UNET 修改单通道数据集输入

### ISSUE THREAD

**Issue by logic1999sun** [WZMIAOMIAO/deep-learning-for-image-processing#609]
导， 求解如何修改 unet项目为 单通道灰度数据集进行训练  
我尝试修改model的channel=1 程序报错TypeError: Input tensor should be a float tensor. Got torch.int32.
在normalize处设置断点得到
tensor([[[2410, 2395, 2418,  ..., 2110, 2111, 2160],
         [2406, 2432, 2418,  ..., 2120, 2133, 2166],
         [2359, 2384, 2389,  ..., 2138, 2153, 2155],
         ...,
         [2090, 2088, 2104,  ..., 2195, 2208, 2228],
         [2088, 2136, 2133,  ..., 2257, 2242, 2257],
         [2072, 2111, 2103,  ..., 2245, 2227, 2209]]], dtype=torch.int32)
请问接下来如何修改才能实现单通道的数据训练

**Comment by WZMIAOMIAO** [comment]
1. 创建模型时`in_channels=1`
```python
def create_model(num_classes):
    model = UNet(in_channels=1, num_classes=num_classes, base_c=32)
    return model
```

2. `mean`和`std`需要自己重新计算，并且都只有一个元素
```python
mean = (0.709,)
std = (0.127,)
```

3. 自己重写自定义数据集读取`__getitem__`部分，在该项目默认将读入图片转成RGB图片
```python
img = Image.open(self.img_list[idx]).convert('L')
```

**Comment by logic1999sun** [comment]
感谢回复，已经解决了，并且由于我的数据集比较特殊，所以convert（‘L’）的方法不能很好地将数据转化为浮点类型，因此需要进一步处理。再次感谢回复
