### ISSUE TITLE
colab上运行tf版的mobilenet中的predict.py文件报错

### ISSUE THREAD

**Issue by heart6622** [WZMIAOMIAO/deep-learning-for-image-processing#615]
# 训练的结果：
![image](https://user-images.githubusercontent.com/91278105/183301135-33894f23-f98c-441c-8fe3-519cdad92ece.png)
# 权重文件：
![image](https://user-images.githubusercontent.com/91278105/183301120-da950c04-6746-453a-a708-bd9b85ff78ab.png)
# 运行预测文件报错：
![image](https://user-images.githubusercontent.com/91278105/183301171-e791863c-3b5b-4c64-b0b3-bb08070d7c12.png)

**Comment by WZMIAOMIAO** [comment]
麻烦你按照问题模板提供详细信息，谢谢。
