### ISSUE TITLE
关于训练结果

### ISSUE THREAD

**Issue by wujihua628** [WZMIAOMIAO/deep-learning-for-image-processing#619]
你好，我用您的代码faster_rcnn中的train_res50_fpn.py进行图片的训练，一共是6000+张图片，batch_size=8，运行得到如下的结果：

![image](https://user-images.githubusercontent.com/90367095/184146636-0903f64c-1c16-4c8b-b421-8556b5fcfbc8.png)

想问一下您，图中画红色圆圈的数字代表什么意思呢？代码位于哪一部分呢？关于运行结果B站上是否有讲解呢？（关于训练结果，代码和B站我都没有找到，希望您能告诉我一下）

希望得到您的解答，您的任何建议都会对我有帮助，十分感谢您精彩的内容！

**Comment by EulerBlind** [comment]
![image](https://user-images.githubusercontent.com/15968740/184270924-2d44f4b2-4d9b-4219-9720-5b47eb3b2b1b.png)
![image](https://user-images.githubusercontent.com/15968740/184270960-3532121c-7b5b-4b0b-9ce6-468426f7c16c.png)

**Comment by wujihua628** [comment]
好的，感谢您的回答

**Comment by WZMIAOMIAO** [comment]
你标的数字是总step数，等于总样本数除以batch_size，这都是基本常识。没有专门去讲。

**Comment by wujihua628** [comment]
我的基础不太好，谢谢您的解答，感谢
