### ISSUE TITLE
这个for循环存在的意义是什么,是否应该把strides的计算和 anchors_over_all_feature_maps移动到第一层for循环呢

### ISSUE THREAD

**Issue by littlebaibear** [WZMIAOMIAO/deep-learning-for-image-processing#62]
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/0a1cce2cfd32939483a8902bef1a08fa80d13d62/pytorch_object_detection/faster_rcnn/network_files/rpn_function.py#L196
  
![image](https://user-images.githubusercontent.com/49135396/96069955-d4701100-0ed1-11eb-8bf3-c206bc332b46.png)

**Comment by WZMIAOMIAO** [comment]
因为之前经过预处理了，所以每张图像的strides和anchors_over_all_feature_maps都是一样的。所以只用计算一次就行了，没必要移至for循环里重复计算。

**Comment by littlebaibear** [comment]
这个我了解了,只是有疑问:映射回原图,这里所谓"原图"为什么不是真正原始图像,而是batch之后的统一大小的图像,最后显示检测框应该是在未处理的图像上,后续代码是针对这个有重新映射吗(指postprocess方法),不知道理解对不对

**Comment by WZMIAOMIAO** [comment]
有的，在postprocess中会还原回去
