### ISSUE TITLE
训练好的权重

### ISSUE THREAD

**Issue by EthanCodesss** [WZMIAOMIAO/deep-learning-for-image-processing#63]
感谢您做的这个教程!太棒了!
有已经训练好的weights吗 出于学习目的不想去训练

**Comment by WZMIAOMIAO** [comment]
链接:https://pan.baidu.com/s/1YmC_VhMyaYrHTQIfYumbcw 提取码:yw0r 
这是我用**resnet_fpn**网络训练的。**注意：训练过程中采用的是官方提供的基于COCO数据集的预训练权重，训练集是poscal voc2012 的train.txt，验证是val.txt**

**Comment by EthanCodesss** [comment]
> 链接:https://pan.baidu.com/s/1YmC_VhMyaYrHTQIfYumbcw 提取码:yw0r
> 这是我用**resnet_fpn**网络训练的。**注意：训练过程中采用的是官方提供的基于COCO数据集的预训练权重，训练集是poscal voc2012 的train.txt，验证是val.txt**

太感谢辽

**Comment by Thrill-Peng** [comment]
谢谢发自我的华为手机-------- 原始邮件 --------发件人： WZMIAOMIAO <notifications@github.com>日期： 2020年10月16日周五 中午12:22收件人： WZMIAOMIAO/deep-learning-for-image-processing <deep-learning-for-image-processing@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [WZMIAOMIAO/deep-learning-for-image-processing] 训练好的权重 (#63)
Closed #63.
