### ISSUE TITLE
负样本（无目标样本或背景图）

### ISSUE THREAD

**Issue by wujihua628** [WZMIAOMIAO/deep-learning-for-image-processing#632]
用您写的ssd算法跑的，我用的总的数据集一共6000+张图片，按8：1：1比例分配训练集、测试机、验证集，测试集跑出来的map最高的竟然达到了99.9%！

![image](https://user-images.githubusercontent.com/90367095/186898896-0418953a-ab24-4552-a6d7-929bd47bd932.png)

想知道是什么原因，怀疑是我自己的数据集中训练集和测试集的图片样子太像，没有太多的变化

或许还有别的原因，我该怎么做呢？

希望得到您的回复，谢谢

**Comment by WZMIAOMIAO** [comment]
你自己的数据集我不太清楚，可能任务比较简单，或者像你说的训练集和测试集中有很多类似的。

**Comment by wujihua628** [comment]
好的，谢谢您。

想再请教您一个问题：不训练，直接用预训练的权重来进行我自己图片的测试可不可以呢？（我试了一下，会报错，是需要对模型进行修改嘛？下面是报错提示）

![image](https://user-images.githubusercontent.com/90367095/187141430-da7be9a4-2786-4896-a34f-d518ea2cf724.png)

感谢感谢

**Comment by wujihua628** [comment]
嗯嗯谢谢了
