### ISSUE TITLE
绘制PR曲线

### ISSUE THREAD

**Issue by wujihua628** [WZMIAOMIAO/deep-learning-for-image-processing#633]
作者您好，我想借鉴您的ssd代码，现在有个难题就是您的论文中好像没有绘制P曲线或R曲线或者PR曲线，请问我该在validation.py中操作还是在plot_curve.py中操作呢？

或者不绘制曲线，单纯得到Recall和Precision的值也可以，我该怎么改呢？

感谢感谢

**Comment by WZMIAOMIAO** [comment]
我平时不怎么用PR曲线，也没什么推荐的，你自己可以在github上找找开源的项目用。还有你说看过我的论文，我觉得你可能看到了个假论文或者你认错人了。

**Comment by wujihua628** [comment]
哈哈写错了，应该是您的代码中

谢谢回答
