### ISSUE TITLE
Assignment- image processing

### ISSUE THREAD

**Issue by sihamalna** [WZMIAOMIAO/deep-learning-for-image-processing#636]
import cv2
import numpy as np

import cv2
def load_image(image_path):
    coloured_image = cv2.imread(image_path)
    grey_image = cv2.cvtColor(coloured_image, cv2.COLOR_BGR2GRAY)
    print('image matrix size: ', grey_image.shape)
    print('\n First 5 columns and rows of the image matrix: \n', grey_image[:5, :5])
    cv2.imwrite('TopLeft5x5.jpg', grey_image[:5, :5])
    return grey_image

input_image = load_image('input_image.jpg')

def my_gamma(s,c,gam,mode):
   invgamma = 1 / gam
   pixel = np.zeros(s.shape)
   rows, cols = pixel.shape
   if LUT == true:
      Table = {k: (C* (k + gam) ** mode) for k in range (256)}
      for i in range(rows):
          for j in range(cols): 
              pixel[[i][j]] = Table[s[i][j]]
       return pixel
    else:
         for i in range(rows):
             for j in range(cols):
                 pixel[i][j] = C* (s[i][j] + gam) ** mode
         return pixel.

def my_imfilter(s, filter):

filter = np.flipud (np.fliplr (filter))
output = np. zeros_like(s)

image_padded = np.zeros ((s.shape[0] + 2, s.shape[1] + 2))
image_padded[1:-1, 1:-1] = s

   for x in range(s.shape[1]):
        for y in range(s.shape[0]):
           
            output[y, x]=(filter * image_padded[y: y+3, x: x+3]).sum()

    return output

filter = np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]])
image_sharpen = imfilter ( s , filter_size = 1)
cv2.imwrite('sharpened_image.jpg', image_sharpen)

**Comment by WZMIAOMIAO** [comment]
what are you doing.
