### ISSUE TITLE
boxes与losses不对应

### ISSUE THREAD

**Issue by littlebaibear** [WZMIAOMIAO/deep-learning-for-image-processing#64]
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/0a1cce2cfd32939483a8902bef1a08fa80d13d62/pytorch_object_detection/faster_rcnn/network_files/rpn_function.py#L628
这里返回的经过nms等操作处理的boxes,而losses是未经这些处理的所有anchors的loss,是在后面roipooling删减保留了对应boxes的losses吗
后面的roipooling部分因为B站没视频还没看,所以先来问问up

**Comment by WZMIAOMIAO** [comment]
这里的losses是针对RPN部分的，和后面的Fast RCNN部分没关系，后面的Fast RCNN会根据这里的提供的box计算出Fast RCNN部分的losses。这里的boxes和loss是没有对应关系的。

**Comment by littlebaibear** [comment]
噢，的确是这样，光看RPN部分都把脑袋看昏了😓
