### ISSUE TITLE
resnet中训练代码求解答

### ISSUE THREAD

**Issue by leehaining** [WZMIAOMIAO/deep-learning-for-image-processing#65]
在resnet的train.py中 missing_keys, unexpected_keys = net.load_state_dict(torch.load(model_weight_path), strict=False)这句代码没搞明白，注释掉程序可以进行训练，但是加上后会报错TypeError: 'NoneType' object is not iterable

**Comment by WZMIAOMIAO** [comment]
安装pytorch1.3或以上版本

**Comment by leehaining** [comment]
谢谢解答。已经正常训练了
