### ISSUE TITLE
训练精度问题

### ISSUE THREAD

**Issue by adminmyw** [WZMIAOMIAO/deep-learning-for-image-processing#651]
博主：
您好！
我用自己的数据去训练U2net，显示“[epoch: 0] val_MAE: 0.067 val_maxF1: 0.000
Epoch: [1]  [ 0/48]  eta: 0:05:28  lr: 0.000511  loss: 1.3729 (1.3729)  time: 6.8397  data: 6.2014  max mem: 3338”
这是什么问题？然后预测的时候预测图全为黑色。
加载数据的时候，可以加载tif格式的数据吗？
感谢您的分享!
期待你的回答！

**Comment by WZMIAOMIAO** [comment]
你有加载预训练权重吗？其他格式的数据集可以自己通过自定义数据集的方式实现。

**Comment by Harper-d** [comment]
博主，你好我用自己的数据去从头训练VGG16，代码用的就是您写的那个，然后我是分10个类，所以train就改了一下实例化时类的参数，但是准确率最高只有0.36左右这正常吗？我是不是哪里弄错了

**Comment by WZMIAOMIAO** [comment]
vgg模型参数规模太大了，不适合用自己的数据集从头训，除非你数据集数量和imagnet一样。建议用pytorch官方提供的模型做迁移学习，要么换个别的模型。
