### ISSUE TITLE
训练权重问题

### ISSUE THREAD

**Issue by Zrs1171757736** [WZMIAOMIAO/deep-learning-for-image-processing#652]
作者好，我是按照您的讲解进行的代码训练，数据集也是用的DUTS官方数据集，为什么每次训练保存的权重都是504M

**Comment by WZMIAOMIAO** [comment]
训练脚本中除了保存权重外还会保存优化器等信息，详情可以看下代码。
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/acac98bffe1b82719019951dcbbf0a49e555707b/pytorch_segmentation/u2net/train.py#L91-L97
