### ISSUE TITLE
在course ppt中加入讲解pytorch实现Swin-transformer实现时的ppt吧

### ISSUE THREAD

**Issue by xiaopanchen** [WZMIAOMIAO/deep-learning-for-image-processing#653]
在course ppt中加入讲解pytorch实现Swin-transformer实现时的ppt吧，我看视频的时候您用的是swin-transformer_code.pptx，谢谢。

**Comment by learning-art** [comment]
您给我发的信息已收到！ 我会及时回复信息！

祝您健康、快乐！

哈尔滨工业大学

**Comment by WZMIAOMIAO** [comment]
> 在course ppt中加入讲解pytorch实现Swin-transformer实现时的ppt吧，我看视频的时候您用的是swin-transformer_code.pptx，谢谢。


没有保留那个PPT哦

**Comment by xiaopanchen** [comment]
> > 在course ppt中加入讲解pytorch实现Swin-transformer实现时的ppt吧，我看视频的时候您用的是swin-transformer_code.pptx，谢谢。
> 
> 没有保留那个PPT哦

真遗憾哈，您画的图那么易懂。
