### ISSUE TITLE
faster rcnn相关问题

### ISSUE THREAD

**Issue by 745234332** [WZMIAOMIAO/deep-learning-for-image-processing#66]
您好，想问下您再faster rcnn里面是怎么划分数据集的呢？我看您视频里讲的是划分了训练集和测试集，但是我看您在训练时每一个epoch都使用测试集进行测试了，这似乎是验证集的用法，那么您这里划分的测试集的功能到底是什么呢？

**Comment by WZMIAOMIAO** [comment]
训练自己数据集时没必要划分一个验证集和一个测试集(又不是打比赛)，所以只要一个验证集就够了。

**Comment by 745234332** [comment]
所以在最后取结果的时候是取每个epoch验证的平均值吗？还有就是您的验证集在每个epoch后进行验证时会不会对某些参数进行调整，从而影响到下次epoch的训练过程（因为我看有的博客上说验证集可以在每次训练后对模型进行微调，使模型更好）。如果我不是每个epoch后都验证，二是所有epoch完成后再验证（或者说测试）这样有没有什么影响呢？

**Comment by WZMIAOMIAO** [comment]
不是取均值。验证集不参与训练，对模型没任何影响。

**Comment by 745234332** [comment]
好的，谢谢您得解答，对于每次验证得结果可以作为我选择最终模型得一个参考是吧？简单得来说，就是我可以选择map最高的那一轮的训练结果作为最终模型，使这样吗？

**Comment by WZMIAOMIAO** [comment]
是的

**Comment by 745234332** [comment]
好的，谢谢您！
