### ISSUE TITLE
MaskRCNN图像预处理

### ISSUE THREAD

**Issue by Yuhuoo** [WZMIAOMIAO/deep-learning-for-image-processing#662]
大佬您好，请教一下MaskRCNN算法在将图像输入网络前的预处理，并没有把图像缩放到同一大小，像语义分割FCN等等都有将图像缩放到同一大小的处理，请问这个缩放是对算法精度有影响么？所以才没有选择将图像缩放到同一大小

**Comment by WZMIAOMIAO** [comment]
都是按照原论文来的，你可以自己改改试试。另外FCN并不是缩放到同一尺寸，训练时只是将最小边按照等比例缩放到某一尺寸然后随机裁剪到某一固定尺寸。

**Comment by Yuhuoo** [comment]
> 都是按照原论文来的，你可以自己改改试试。另外FCN并不是缩放到同一尺寸，训练时只是将最小边按照等比例缩放到某一尺寸然后随机裁剪到某一固定尺寸。

好的，感谢大佬回复
