### ISSUE TITLE
关于训练个人数据集训练结果

### ISSUE THREAD

**Issue by zxy-0714** [WZMIAOMIAO/deep-learning-for-image-processing#663]
博主，您好。我想通过您提供的U2net网络代码，训练自己的数据集（合成数据集：一万张），但是训练的过程中出现了一些问题。我发现训练的loss在一个epoch后下降到了（0.8492），10个epoch下降到了（0.0488），且maxF1达到了0.995.而后在小数点4位变化，这看起来有点奇怪。然后用predict.py进行预测的时候，预测结果并不理想。以下是几点我的疑问：
1：训练自己的数据集，是否应对模型做出相应修改？（我的分割任务是分割前景和背景，感觉不用改吧）
2：学习率过高（我把学习率从原先0.001调整为0.0001，好像并不是很理想）
3：数据集有问题（感觉也没啥问题，mask为8位二进制图片，前景位置像素为255，背景为0；还是说图片归一化的mean，和std要根据数据集重新得出）
4：损失函数（是否是因为目标在前景中占比较小，损失函数得做出相应修改？）
（这是训练结果）
![image](https://user-images.githubusercontent.com/113298426/196626179-a87d39ef-4f5a-498d-bd7f-7e8896db6555.png)
（这是我的合成数据集部分图片）
![image](https://user-images.githubusercontent.com/113298426/196626370-86f777f1-3a58-468c-9fbd-5561bcf9b95f.png)

**Comment by WZMIAOMIAO** [comment]
根据你提供的验证结果效果应该很理想了，应该不是训练问题。但具体为什么效果不好，你或许应该检查下是不是自己预测脚本使用的不对。
