### ISSUE TITLE
请教MaskRCNN 算法预处理Pascal VOC数据集的问题

### ISSUE THREAD

**Issue by Yuhuoo** [WZMIAOMIAO/deep-learning-for-image-processing#666]
大佬你好，冒昧请教。我在看你的mask rcnn算法处理Pascal VOC数据集的代码时候，发现你是这样将每个目标拆分出来形成单独的通道

    def parse_mask(self, idx: int):
        mask = self.masks[idx]
        c = mask.max()  # 有几个目标最大索引就等于几
        masks = []
        # 对每个目标的mask单独使用一个channel存放
        for i in range(1, c+1):
             masks.append(mask == i)
        masks = np.stack(masks, axis=0)
        return torch.as_tensor(masks, dtype=torch.uint8)

这里的拆解是不是有点问题，因为我在看你csdn上关于Pascal VOC博文的时候，我记得Pascal VOC数据集是将类别存储到对应的像素上，边界和背景为0。那这里如果一张图片分别由（10、13、19...）等几个类别组成，用 c = mask.max() 拿到个数，然后用range(1, c)的方式好像并不能取到对应的类别，随后输出的mask也就不是由（0、1）组成的结果，这样一来计算最后的损失的时候是不是有点问题？

**Comment by WZMIAOMIAO** [comment]
没有问题，这里是将pascal voc数据格式转成coco标注格式

**Comment by Yuhuoo** [comment]
> 没有问题，这里是将pascal voc数据格式转成coco标注格式

好的，不好意思是我看错了，语义分割图是存的对应类别，实例分割图是存的目标序号
