### ISSUE TITLE
positive = torch.where(torch.ge(matched_idxs_per_image, 1))[0]

### ISSUE THREAD

**Issue by EudicL** [WZMIAOMIAO/deep-learning-for-image-processing#667]
**System information**
* Have I written custom code:
* OS Platform Linux Ubuntu 18.04): Ubuntu 18.04
* Python version:3.7
* Deep learning framework and version  Pytorch1.8.1
* Use GPU or not: GPU
* CUDA/cuDNN version(if you use GPU): cuda11.1
* The network you trained(e.g., Resnet34 network):fasterrcnn-resnet50_fpn

**Describe the current behavior**
Hi, when i train on the VOC2007, the error is belows:
      
      positive = torch.where(torch.ge(matched_idxs_per_image, 1))[0]
      RuntimeError: CUDA error: device-side assert triggered

**Error info / logs**
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [0,0,0], thread: [33,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

**Comment by WZMIAOMIAO** [comment]
You can try to use the CPU device to run. If there is no error when executing the program with CPU, it means that the GPU environment is not configured correctly.
