### ISSUE TITLE
关于swintransformer的输入shape问题

### ISSUE THREAD

**Issue by PrShi113** [WZMIAOMIAO/deep-learning-for-image-processing#669]
老师您好，想请教一下，如果调用**class SwinTransformer**,输入Tensor的尺寸应该是[B, L, C]吗？还是[B, H, W, C].

**Comment by WZMIAOMIAO** [comment]
[B, C, H, W]

**Comment by PrShi113** [comment]
谢谢老师 但我有点不理解 为什么**class SwinTransformer**的forward函数里面 **x: [B, L, C]** ...？按照输入不应该是 **[B, C, H, W]**嘛

**Comment by WZMIAOMIAO** [comment]
网络里会将数据格式由B, C, H, W]转到[B, L, C]
