### ISSUE TITLE
PyTorch_objectDetection中的网络训练时出现：KeyError:

### ISSUE THREAD

**Issue by GKCON** [WZMIAOMIAO/deep-learning-for-image-processing#671]
OS Platform: window10:
Python version:3.8.13
Deep learning framework and version: Pytorch1.11.0
Use GPU :
CUDA/cuDNN version(if you use GPU):11.7.89
* The network you trained):
Faster R-CNN,SSD,RetinaNet
**Describe the current behavior**
老师，您好，当我使用您的pytorch_object_detection中的神经网络训练自己制作的VOC数据集时，都出现了KeyError：’‘这个错误，学生也尝试过用labelImage重新标注，却依然出现这个错误，没有解决，麻烦老师能解答一下学生的疑惑吗？
**Error info / logs**
![CL((60_UD%H9(PG(}8BOF~G](https://user-images.githubusercontent.com/87354033/198635241-8d0f1bc8-d9ab-401d-9051-b23c7cc4d587.png)
![R_HZZ1 G5{C2I LSOC_TV{T](https://user-images.githubusercontent.com/87354033/198635767-0346077f-167b-45ae-ba35-77b35af534f6.jpg)
下面是学生制作数据集的xml文件：
![image](https://user-images.githubusercontent.com/87354033/198637280-41f71db4-3222-4c67-80bf-6b93fed5be6c.png)

**Comment by WZMIAOMIAO** [comment]
说明你没有改id和对应类别信息的json文件，https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_object_detection/faster_rcnn/pascal_voc_classes.json

**Comment by GKCON** [comment]
收到！谢谢导师解答，已解决
