### ISSUE TITLE
val_loss

### ISSUE THREAD

**Issue by xiaohongzaizhe** [WZMIAOMIAO/deep-learning-for-image-processing#672]
怎么样去写验证集的loss呢非常感谢

**Comment by xiaohongzaizhe** [comment]
u2net网络的

**Comment by WZMIAOMIAO** [comment]
自己参考训练集是这么算loss的，https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_segmentation/u2net/train_utils/train_and_eval.py#L49
