### ISSUE TITLE
维度错误

### ISSUE THREAD

**Issue by wangzhao-11a** [WZMIAOMIAO/deep-learning-for-image-processing#673]
![e43da86e06be5504401ace242783a8a](https://user-images.githubusercontent.com/73340653/198816828-0d3099e1-ad97-4391-a47c-93e364821c4e.jpg)
预测的类别和标签类别对不上，都是五类标签却显示4类

**Comment by WZMIAOMIAO** [comment]
这个错误好像和类别无关，检查你自己是不是改动了什么代码导致的。
