### ISSUE TITLE
关于retinanet anchor refine的问题

### ISSUE THREAD

**Issue by Bobby-youngking** [WZMIAOMIAO/deep-learning-for-image-processing#674]
博主，想问问retinanet中每次如何生成新anchor的？

**Comment by WZMIAOMIAO** [comment]
参考项目代码：https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/80681e81327320a37cfc35b754d8204a5156e9c2/pytorch_object_detection/retinaNet/network_files/retinanet.py#L505
