### ISSUE TITLE
混淆矩阵计算评价指标ACC的代码有错？

### ISSUE THREAD

**Issue by 112wl** [WZMIAOMIAO/deep-learning-for-image-processing#677]
在pytorch_segmentation/fcn/train_utils/distributed_utils.py文件里的第99行，混淆矩阵计算评价指标ACC时，分母是TP+FP，而这里的混淆矩阵h的列为预测值，行为真实值，那分母不是应该写成h.sum(0)（按列求和）吗？为什么这里写的是h.sum(1)呢？这样计算出来的应该是recall吧。感谢解答！

**Comment by WZMIAOMIAO** [comment]
建议你看下这个视频：https://www.bilibili.com/video/BV19q4y1971Q/?p=4

**Comment by WZMIAOMIAO** [comment]
这里计算的acc是按照论文中定义来的，没有问题，之前在讲语义分割前言时讲过：https://www.bilibili.com/video/BV1ev411P7dR，确实和recall计算方法一致。

**Comment by 112wl** [comment]
好的，感谢解答。我认为是FCN论文里的公式写错了，acc应该就是精确率（Precision）

**Comment by 112wl** [comment]
学习你的解答。我Google了一下, 好像很多人都是直接将精准率（Precision）当做类别像素准确率（CPA）。要么就是FCN论文里写错了；要么就是网上的这些代码有误。你怎么看这个问题呢？

**Comment by 112wl** [comment]
谢谢你的解答。我Google了一下, 好像很多人都是直接将精准率（Precision）当做类别像素准确率（CPA）。要么就是FCN论文里写错了；要么就是网上的这些代码有误。你怎么看这个问题呢？

**Comment by WZMIAOMIAO** [comment]
Pytorch官方代码里就是这么实现的，我也没啥看法。对于语义分割网络有很多其他的评价指标，如果你觉得这里的acc不合适，可以采用其他评价指标。
