### ISSUE TITLE
FCN训练时报错

### ISSUE THREAD

**Issue by SoBeit0209** [WZMIAOMIAO/deep-learning-for-image-processing#678]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04): Ubuntu18
* Python version: 3.8
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): pytorch
* Use GPU or not: yes
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network): FCN

**Describe the current behavior**
首先谢谢大佬的代码

训练一开始非常顺利，但是训练到69epoch的时候突然报错
"distributed_utils.py" line136
assert isinstance（v，（float，int））
AssertionError

我print这里的v发现会输出复数，不知道怎么回事，我没有改动网络，只是更改了训练数据集

**Error info / logs**
![image](https://user-images.githubusercontent.com/88532300/200159398-13fefc8c-8679-4610-aff3-a89b52648b5c.png)

**Comment by SoBeit0209** [comment]
经过我的一些观察，好像在某一轮训练时学习率降到了0，再下一轮学习率就变为复数了，为什么会这样呢？谢谢

**Comment by WZMIAOMIAO** [comment]
我不清楚你到底改动了什么代码，按理说最后一个epoch学习率才会降到零。你这提前降到零了肯定有问题。
