### ISSUE TITLE
up提供的代码中，要求样本中至少有一个待检测目标，请问如果想要用不含待检测目标的纯负样本如何读取

### ISSUE THREAD

**Issue by LITturtlee** [WZMIAOMIAO/deep-learning-for-image-processing#679]
主要是希望能够在验证集中添加一些纯负样本，请问应该如何修改代码。我目前在dataset的文件中修改，尝试将纯负样本的target中的box设置为(-1,-1,-1,-1)，label设置为0。
这样能够跑通程序，但是我不知道是否正确，求大佬指点

**Comment by WZMIAOMIAO** [comment]
你可以自己参考pytorch/vision仓库中的faster rcnn代码自己修改下：https://github.com/pytorch/vision/tree/main/torchvision/models/detection
