### ISSUE TITLE
混淆矩阵

### ISSUE THREAD

**Issue by hehaiyang111** [WZMIAOMIAO/deep-learning-for-image-processing#68]
您好：
    请问混淆矩阵精度算出来的有nan。混淆矩阵里有一行全是0？
    劳烦有时间回答，谢谢！

**Comment by WZMIAOMIAO** [comment]
说明某一个类别中是没有任何图像的，可能是你num_classes设置错了，也可能是你标签json文件是错的

**Comment by hehaiyang111** [comment]
感谢！
  测试图片52类都有图像，num_classes和对应的json文件都是好的。 
  混淆矩阵的一行都为0是否表示的是，没有图片预测到该类，该类的图片又都预测成了别的类。这个时候精度(precision  TP/(TP+FP))是不是就没法算了?

**Comment by WZMIAOMIAO** [comment]
你说的情况确实也存在，那你在计算precision的代码中，加上如果分母为0就直接令precision=0

**Comment by hehaiyang111** [comment]
谢谢！麻烦了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 下午3:51
收件人:&nbsp;"WZMIAOMIAO/deep-learning-for-image-processing"<deep-learning-for-image-processing@noreply.github.com&gt;;
抄送:&nbsp;"何海洋"<1464751753@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 混淆矩阵 (#68)





 
你说的情况确实也存在，那你在计算precision的代码中，加上如果分母为0就直接令precision=0
