### ISSUE TITLE
Error of using generator

### ISSUE THREAD

**Issue by XZHSTAX** [WZMIAOMIAO/deep-learning-for-image-processing#680]
My env: Ubuntu 20.04+python3.10.6
In the file `pytorch_classification/Test1_official_demo/train.py`:
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/5d35dd4782968f817e08d866f6e304f483d704ae/pytorch_classification/Test1_official_demo/train.py#L28

you use generator，but`.next()` is no longer supported for Python3, you should use `.__next__` or `next(---)` like:
```python
val_image, val_label = val_data_iter.__next__()
```
or
```python
val_image, val_label = next(val_data_iter)
```
thanks for your code :)

**Comment by WZMIAOMIAO** [comment]
thank you for your advice, I will fix this issue.
