### ISSUE TITLE
多卡训练准确度比单卡低

### ISSUE THREAD

**Issue by balala8** [WZMIAOMIAO/deep-learning-for-image-processing#682]
**System information**
* Have I written custom code:
* OS Platform(Linux Ubuntu 18.04):
* Python version:
* Deep learning framework and version(Pytorch1.8):
* Use GPU or not: 2 * 3070
* The network you trained(Resnet50 network and mobilenet v3 large):

**Describe the current behavior**
您好，目前我是在做分类任务。在我们自己的数据集上，训练集8k张224*224的图片，测试集2k。然后我就发现单张3070的准确度有90，91。而双卡3070却只有84、84。请问您是否这是什么原因呢？或者我应该从哪些方面去排查？

**Comment by WZMIAOMIAO** [comment]
你用双卡时就将学习率翻倍吗

**Comment by balala8** [comment]
是的，学习率乘上卡的数量。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月20日(周日) 中午11:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WZMIAOMIAO/deep-learning-for-image-processing] 多卡训练准确度比单卡低 (Issue #682)




 
你用双卡时就将学习率翻倍吗
