### ISSUE TITLE
vit的某些模型参数没有提供下载 不知道是否可以增加模型权重链接 感谢~

### ISSUE THREAD

**Issue by Arsmart1** [WZMIAOMIAO/deep-learning-for-image-processing#683]
比如。。。vit_base_patch16_224_in21k等？没有看到链接。。。啊 以及非常感谢这份代码，很好用！

**Comment by WZMIAOMIAO** [comment]
代码里这不都写的有嘛：
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/80681e81327320a37cfc35b754d8204a5156e9c2/pytorch_classification/vision_transformer/vit_model.py#L307-L313

**Comment by DavidYanAnDe** [comment]
你好，请问这个链接下载的应该是jx参数吧，修改文件名称之后pytorch可以直接使用吗？
