### ISSUE TITLE
aten::zeros_like.dtype(Tensor self, *, int dtype, int layout, Device device, bool pin_memory=False) -> (Tensor):   Argument layout not provided.

### ISSUE THREAD

**Issue by EthanCodesss** [WZMIAOMIAO/deep-learning-for-image-processing#69]
你好我在GPU训练，运行到这段代码的时候
`            pos_idx_per_image_mask = torch.zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )
            neg_idx_per_image_mask = torch.zeros_like(
                matched_idxs_per_image, dtype=torch.uint8
            )`
出现  aten::zeros_like(Tensor self) -> (Tensor):
  Keyword argument dtype unknown.
  
  aten::zeros_like.dtype(Tensor self, *, int dtype, int layout, Device device, bool pin_memory=False) -> (Tensor):
  Argument layout not provided.

我该怎么解决，新手小白，万分感谢🙏！

**Comment by WZMIAOMIAO** [comment]
pytorch版本升到1.6

**Comment by EthanCodesss** [comment]
> pytorch版本升到1.6

好的!已解决,感谢感谢
