### ISSUE TITLE
HRNet代码中是否没必要再判断kps_weights[kp_id] > 0.5

### ISSUE THREAD

**Issue by DaMiBear** [WZMIAOMIAO/deep-learning-for-image-processing#691]
**System information**
* Have I written custom code: No
* OS Platform(e.g., window10 or Linux Ubuntu 16.04): Ubuntu20.04
* Python version: 3.8
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3): Pytorch1.11
* Use GPU or not: GPU
* CUDA/cuDNN version(if you use GPU): CUDA
* The network you trained(e.g., Resnet34 network): HRNet

**Describe the current behavior**
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/5d35dd4782968f817e08d866f6e304f483d704ae/pytorch_keypoint/HRNet/transforms.py#L404-L433
请问Up，在HRNet代码中的`430行:if kps_weights[kp_id] > 0.5:`是不是可以去掉呢？

因为之前在`405行`已经判断过`v < 0.5`就跳过了，能运行到后面代码段的肯定是满足`kps_weights[kp_id] >= 0.5`条件的（除非等于0.5的情况），即使在`418`行被重新赋值为0，但也会跳过。

**Comment by WZMIAOMIAO** [comment]
好的，谢谢提醒，这里的判断看上去确实有些冗余。
