### ISSUE TITLE
可以提供一下多GPU并行章节的讲解PPT吗？

### ISSUE THREAD

**Issue by Lonicer** [WZMIAOMIAO/deep-learning-for-image-processing#692]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
不好意思，这个ppt没保留哈

**Comment by Lonicer** [comment]
没事，23333，不过还是谢谢你的讲解

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WZMIAOMIAO/deep-learning-for-image-processing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月20日(星期天) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WZMIAOMIAO/deep-learning-for-image-processing] 可以提供一下多GPU并行章节的讲解PPT吗？ (Issue #692)





 
不好意思，这个ppt没保留哈
