### ISSUE TITLE
Add new transformation class to save memory in training MaskRCNN

### ISSUE THREAD

**Issue by r-matsuzaka** [WZMIAOMIAO/deep-learning-for-image-processing#693]
Hi. Thank you for the informative notebook:) For my environment(RTX2080 and RTX2080 super), I could not run even with small COCO dataset available from https://github.com/giddyyupp/coco-minitrain  
So I cropped images with new `FixedSizeCrop` class added in `transforms.py`.
Then I could train model with no memory issue.

The snippets comes from original pytorch repository https://github.com/pytorch/vision/blob/main/references/detection/transforms.py which is BSD 3-Clause License.  
If this feature is convenient, I will make a PR.

- https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/compare/master...r-matsuzaka:deep-learning-for-image-processing:master

**Comment by WZMIAOMIAO** [comment]
No Thansk, Mask  RCNN doesn't need `FixedSizeCrop`

**Comment by r-matsuzaka** [comment]
Ok. Thank you for response.
