### ISSUE TITLE
ONNX文件 读取问题 

### ISSUE THREAD

**Issue by Lexiaotian** [WZMIAOMIAO/deep-learning-for-image-processing#699]
yolov3-spp中的onnx文件读取程序 需要怎么改成使用gpu计算的呢     save_path = "yolov3spp.onnx"
    onnx.model = onnx.load(save_path)
    provider = ort.get_available_providers()[1 if ort.get_device() == 'GPU' else 0]
    print('设备:', provider)
    # 声明 onnx 模型
    model = ort.InferenceSession(save_path, providers=[provider])
    # check onnx model
    # onnx.model = onnx.load(save_path)
    # onnx.checker.check_model(onnx.model)
    onnx.checker.check_model(model)
    # print(onnx.helper.printable_graph(onnx_model.graph))
    ort_session = onnxruntime.InferenceSession(save_path)
    img_size = 512

**Comment by WZMIAOMIAO** [comment]
关于onnx gpu使用请参考onnx官方文档，这里不做解答谢谢。
