### ISSUE TITLE
How to let custom datasets support the fast path for computing the aspect ratio?

### ISSUE THREAD

**Issue by uniyushu** [WZMIAOMIAO/deep-learning-for-image-processing#70]
**Describe the current behavior**
My custom dataset doesn't support the fast path, iterating the full dataset is too slow, do you have any ideas?
**Error info / logs**
![image](https://user-images.githubusercontent.com/20262193/96952391-55a65400-1521-11eb-9072-af7aca1b7d68.png)

**Comment by WZMIAOMIAO** [comment]
这是因为你没有在my_dataset.py文件中实现获取img_sieze的功能，建议你直接关闭aspect-ratio-group功能。
直接将```--aspect-ratio-group-factor```值改为-1，关闭此功能
```python
parser.add_argument('--aspect-ratio-group-factor', default=-1, type=int)
```

**Comment by uniyushu** [comment]
感谢up，我直接关闭aspect-ratio-group功能，会报RuntimeError: received 0 items of ancdata错误，加入了get_height_and_width功能，将--workers设置为0之后就不用加载了。
`    def get_height_and_width(self, idx):
        data = self.img_data[idx]
        data_height = int(data["heigh"])
        data_width = int(data["width"])
        return data_height, data_width`
![image](https://user-images.githubusercontent.com/20262193/97278092-44887a80-1874-11eb-8ce9-c5fdc7eec55d.png)

**Comment by WZMIAOMIAO** [comment]
恩，自己实现下get_height_and_width方法，不让它自动去挨个读取图像然后统计height和width是最好的。
