### ISSUE TITLE
YOLOv3-SPP运行报错：索引不在CPU上。麻烦老师帮忙看看！

### ISSUE THREAD

**Issue by Iamdaodao** [WZMIAOMIAO/deep-learning-for-image-processing#702]
**YOLOv3-SPP运行报错：索引不在CPU上**
* 报错信息:
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
* 报错位置:
pytorch_object_detection\yolov3_spp\build_utils\utils.py", line 299, in build_targets
    a, t = at[j], t.repeat(na, 1, 1)[j]  # filter
* 配置及环境:
i5+单张RTX3060 12G
python                    3.9.13
pytorch-cuda              11.6
torch                     1.12.1+cu116
* 已尝试方法：
将torch及相关版本降级，已试过1.12、1.11都未解决问题
在build_target函数中添加语句device = targets.device，无用
* 其他信息:
能正常训练及测试Faster-RCNN网络

最近跟着从分类网络学到检测网络，收获良多，再次感谢！

**Comment by FujieLuo** [comment]
请问下，最后是怎么解决的呢，我也遇到了

**Comment by Lw1244204021** [comment]
同问，怎么解决的呢？

**Comment by Lw1244204021** [comment]
> 同问，怎么解决的呢？
解决了。
**解决办法**：
1）utils的 287行将数据放到device上，at = torch.arange(na).view(na, 1).repeat(1, nt).to(device=targets.device)  # anchor tensor, same as .repeat_interleave(nt)
2）或者不使用gpu
**原因**：原先297行a = at[j]，at在cpu上，j在gpu上

**Comment by Keep-Doing-guoguo** [comment]
![image](https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/assets/54124850/189bc6a0-fd25-4316-ad52-8ec21fe7bcf6)
