### ISSUE TITLE
vit模型加载权重时的bug

### ISSUE THREAD

**Issue by tangjingfeng1105** [WZMIAOMIAO/deep-learning-for-image-processing#727]
导师好，
https://github.com/WZMIAOMIAO/deep-learning-for-image-processing/blob/master/pytorch_classification/vision_transformer/train.py
在vit的train.py的第69行发现一个bug

# 源码
        # 删除不需要的权重
        del_keys = ['head.weight', 'head.bias'] if model.has_logits \
             else ['pre_logits.fc.weight', 'pre_logits.fc.bias', 'head.weight', 'head.bias']

# 报错
    del weights_dict[k]
    KeyError: 'pre_logits.fc.weight'
第一次训练时has_logits就为False，那么第一次保存的weight文件中就不存在'pre_logits.fc.weight'，
第二次训练时载入第一次的weight文件，代码执行到这里has_logit还是False，他就会去删除'pre_logits.fc.weight'，然而第一次训练时权重不存在'pre_logits.fc.weight'

# 修改
        del_keys = ['head.weight', 'head.bias'] if model.has_logits or ~('pre_logits.fc.weight' in weights_dict)\
            else ['pre_logits.fc.weight', 'pre_logits.fc.bias', 'head.weight', 'head.bias']

**Comment by tangjingfeng1105** [comment]
@ZHMMP 我没有遇到你的错误，我的cuda版本是12.0

**Comment by ZHMMP** [comment]
非常感谢您，
如果方便可否分享一下您的pip/conda list，
小白处理各种冲突人快傻了

**Comment by tangjingfeng1105** [comment]
@ZHMMP 我没有为这个项目单独建一个环境，所以安装的包有点多，你可以自己找一下
absl-py                  1.4.0
cachetools               5.3.0
certifi                  2022.12.7
charset-normalizer       3.1.0
cycler                   0.11.0
filelock                 3.9.1
fonttools                4.38.0
fvcore                   0.1.5.post20221221
google-auth              2.16.2
google-auth-oauthlib     0.4.6
grpcio                   1.51.3
huggingface-hub          0.13.2
idna                     3.4
imageio                  2.26.0
importlib-metadata       6.0.0
iopath                   0.1.10
joblib                   1.2.0
kiwisolver               1.4.4
Markdown                 3.4.1
MarkupSafe               2.1.2
matplotlib               3.5.3
numpy                    1.21.6
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
oauthlib                 3.2.2
opencv-contrib-python    4.7.0.72
opencv-python            4.7.0.72
packaging                23.0
Pillow                   9.4.0
pip                      22.3.1
portalocker              2.7.0
protobuf                 3.20.3
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pyparsing                3.0.9
python-dateutil          2.8.2
PyYAML                   6.0
requests                 2.28.2
requests-oauthlib        1.3.1
rsa                      4.9
scikit-learn             1.0.2
scipy                    1.7.3
setuptools               65.6.3
six                      1.16.0
sklearn                  0.0.post1
tabulate                 0.9.0
tb-nightly               2.12.0a20230113
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
termcolor                2.2.0
texttable                1.6.7
threadpoolctl            3.1.0
timm                     0.6.12
torch                    1.13.1
torchaudio               0.13.1
torchvision              0.14.1
tqdm                     4.65.0
typing_extensions        4.5.0
urllib3                  1.26.15
Werkzeug                 2.2.3
wheel                    0.38.4
yacs                     0.1.8
zipp                     3.15.0

**Comment by ZHMMP** [comment]
非常感谢

**Comment by wbbmm** [comment]
大佬们好，请问按照大佬给的语句    del_keys = ['head.weight', 'head.bias'] if model.has_logits or ~('pre_logits.fc.weight' in weights_dict)\
        else ['pre_logits.fc.weight', 'pre_logits.fc.bias', 'head.weight', 'head.bias']修改后，
又报错：del weights_dict[k]
KeyError: 'head.weight'
是为什么呀

**Comment by wbbmm** [comment]
@ZHMMP 大佬好，请问按照大佬给的语句 del_keys = ['head.weight', 'head.bias'] if model.has_logits or ~('pre_logits.fc.weight' in weights_dict)
else ['pre_logits.fc.weight', 'pre_logits.fc.bias', 'head.weight', 'head.bias']修改后，
又报错：del weights_dict[k]
KeyError: 'head.weight'
是为什么呀

**Comment by wbbmm** [comment]
@Jingfeng-Tang 大佬好，请问按照大佬给的语句 del_keys = ['head.weight', 'head.bias'] if model.has_logits or ~('pre_logits.fc.weight' in weights_dict)
else ['pre_logits.fc.weight', 'pre_logits.fc.bias', 'head.weight', 'head.bias']修改后，
又报错：del weights_dict[k]
KeyError: 'head.weight'
是为什么呀

**Comment by Jingfeng-Tang** [comment]
> @Jingfeng-Tang 大佬好，请问按照大佬给的语句 del_keys = ['head.weight', 'head.bias'] if model.has_logits or ~('pre_logits.fc.weight' in weights_dict) else ['pre_logits.fc.weight', 'pre_logits.fc.bias', 'head.weight', 'head.bias']修改后， 又报错：del weights_dict[k] KeyError: 'head.weight' 是为什么呀
权重字典的key错误，你可以把weight_dict的key输出出来看一下，也许你的head.weight前面还有前缀，比如“model.head.weight",这样代码就找不到”head.weight",就会报错。
