### ISSUE TITLE
LeNet第一次训练

### ISSUE THREAD

**Issue by Sang-Ze** [WZMIAOMIAO/deep-learning-for-image-processing#753]
为什么会一直报错·？
pydev debugger: New process is launching (breakpoints won't work in the new process).
pydev debugger: To debug that process please enable 'Attach to subprocess automatically while debugging?' option in the debugger settings.
我已经把.idea文件删除了，结果还是不断重复报错？
求指导

**Comment by WZMIAOMIAO** [comment]
你不开debug直接跑可以吗？
