### ISSUE TITLE
Unet训练和测试代码为什么这么复杂？

### ISSUE THREAD

**Issue by SuoniLiu** [WZMIAOMIAO/deep-learning-for-image-processing#754]
与分类任务相比，Unet的训练、评估和测试代码看起来非常复杂，写了很多utils的代码文件，请问这是必要的吗？还是说可以简化代码呢？
另外，请问为什么分割任务的Loss计算是Dice Loss加上交叉熵损失呢？可以只使用Dice Loss吗？

**Comment by WZMIAOMIAO** [comment]
因为distributed_utils.py文件里包含了一些多卡训练的代码，如果只是用单卡训练的话可以不用管。Loss的设置是按照论文里来的，具体原因可以在论文中找下。
