### ISSUE TITLE
目录结构怎么变得呀大佬，pytorch_learning文件夹怎么没了啊

### ISSUE THREAD

**Issue by PowerKaly** [WZMIAOMIAO/deep-learning-for-image-processing#778]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
挪到pytorch_classification里了
