### ISSUE TITLE
yolov3_spp运行报错，运行到datasets.py中line259报错：

### ISSUE THREAD

**Issue by xin1347764176** [WZMIAOMIAO/deep-learning-for-image-processing#785]
发生异常: ValueError
setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5717,) + inhomogeneous part.
  File "D:\file\objectsegmentation\yolov3_spp\build_utils\datasets.py", line 259, in __init__
    np.save(np_labels_path, self.labels)  # save for next time
  File "D:\file\objectsegmentation\yolov3_spp\train.py", line 153, in train
    train_dataset = LoadImagesAndLabels(train_path, imgsz_train, batch_size,
  File "D:\file\objectsegmentation\yolov3_spp\train.py", line 302, in <module>
    train(hyp)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5717,) + inhomogeneous part.

**Comment by ppppppppyyyy** [comment]
注释掉即可

**Comment by Z-shuaihu** [comment]
还真是，把   ”np.save(np_labels_path, self.labels) # save for next time  “    这行代码注释掉即可，可能保存的东西并不是用于训练的。
等我明白了这行代码什么意思再来
