### ISSUE TITLE
PPT放一个地方不好吗？ 一个个分开，整理也够累的

### ISSUE THREAD

**Issue by FirminSun** [WZMIAOMIAO/deep-learning-for-image-processing#786]
PPT放一个地方不好吗？ 一个个分开，整理也够累的

**Comment by Charly168** [comment]
哈哈哈我也这么想过

发自 Android 版 Yahoo 邮箱 
 
  2024 年 1 月 24 日周三上午 ***@***.***> 写道：   


PPT放一个地方不好吗？ 一个个分开，整理也够累的

**Comment by WZMIAOMIAO** [comment]
所有PPT都放在该文件夹中 链接：https://pan.baidu.com/s/1VL6QTQ86sfY2aMDVo4Z-kg 提取码：4ydw
