### ISSUE TITLE
SSD代码中draw_box_utils.py的小问题

### ISSUE THREAD

**Issue by heyhang** [WZMIAOMIAO/deep-learning-for-image-processing#80]
1、在复现代码的过程中发现，本仓库SSD代码中draw_box_utils.py文件的91行，存入的坐标为相对坐标，所以在绘制框的时候应该乘以图像的宽高，恢复成正常坐标。否则在裁剪操作后的绘图会出现一些问题。
    for box, color in box_to_color_map.items():
        xmin, ymin, xmax, ymax = box
        (left, right, top, bottom) = (xmin * 1, xmax * 1,
                                      ymin * 1, ymax * 1)
        draw.line([(left, top), (left, bottom), (right, bottom),
                   (right, top), (left, top)], width=line_thickness, fill=color)

2、裁剪操作完是否应该把裁剪后的宽高存入target['height_width']中呢？不过不存入也不影响

**Comment by WZMIAOMIAO** [comment]
1）我在调用draw_box函数前已经将坐标转为绝对坐标了，建议仔细看下我在predict_test.py中的代码。

2）预测时我没有对图像进行裁剪
