### ISSUE TITLE
大佬vit那个项目的requirments.txt是啥呀，按照你readme中的要求下载了，遇到了很多版本不兼容的问题，球球了 

### ISSUE THREAD

**Issue by Paddi-zyx** [WZMIAOMIAO/deep-learning-for-image-processing#800]
**System information**
* Have I written custom code:
* OS Platform(e.g., window10 or Linux Ubuntu 16.04):
* Python version:
* Deep learning framework and version(e.g., Tensorflow2.1 or Pytorch1.3):
* Use GPU or not:
* CUDA/cuDNN version(if you use GPU):
* The network you trained(e.g., Resnet34 network):

**Describe the current behavior**

**Error info / logs**

**Comment by WZMIAOMIAO** [comment]
之前好像是用的torch1.10跑的，可以参考这个文档配置下环境：https://blog.csdn.net/qq_37541097/article/details/120951214
