### ISSUE TITLE
VGG模型分类后训练找不到文件

### ISSUE THREAD

**Issue by ParadiseF** [WZMIAOMIAO/deep-learning-for-image-processing#810]
“FileNotFoundError: Found no valid file for the classes Aaron_Eckhart, Aaron_Guiel, Aaron_Patterson, Aaron_Peirsol, Aaron_Pena, Aaron_Sorkin, Aaron_Tippin, Abba_Eban, Abbas_Kiarostami, Abdel_Aziz_Al-Hakim, Abdel_Madi_Shabneh. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp"
用ORL的数据集就行，LFW的就找不到文件。训练集和验证集也划分没问题。

**Comment by WZMIAOMIAO** [comment]
只支持 .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp这几种图片后缀的格式，你检查下你用的数据集是否满足需求。
