### ISSUE TITLE
验证模块

### ISSUE THREAD

**Issue by xxq-pioneer** [WZMIAOMIAO/deep-learning-for-image-processing#82]
在SSD中想获得每个类ap，我根据原SSD的eval代码进行修改，验证时发现得到的map比你使用的coco评价准则所获得的map降了3,4个点，请问你觉得是哪些地方有可能出问题（请问方便的话你可以添加获得每个类别的ap方法吗，感激不尽）

**Comment by WZMIAOMIAO** [comment]
map不同的原因太多了，可能backbone不同，可能匹配正负样本方式不同，可能计算损失的方式不同，可能预训练权重不同，可能训练优化器不同，可能训练的数据选取不同，等等。所以你这没什么可参考的，我是直接使用pycocotools计算的，还没仔细研究过怎么通过pycocotools获取每个类别的ap。
