### ISSUE TITLE
What does the mean of self.include_top?

### ISSUE THREAD

**Issue by tureliuyaohua** [WZMIAOMIAO/deep-learning-for-image-processing#9]
I'm confused about "self.include_top" in Test5/model in class ResNet(nn.Module), could you please show me some information about it?
Thank you in advance~

**Comment by WZMIAOMIAO** [comment]
就是说在实例化模型的时候是否把后面的全连接层添加进去，在后面如果想基于rennet网络搭建更加复杂的网络我们就可以设置self.include_top为false，也就不会将后面的全连接层添加进网络，方便我们在resnet后面添加其他的结构。

**Comment by tureliuyaohua** [comment]
感谢大佬的回复~

**Comment by WZMIAOMIAO** [comment]
不客气
